### ISSUE TITLE
Where to export schedules and output writers from?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1131]
Currently schedules are exported from `Oceananigans.Diagnostics` and `Oceananigans.OutputWriters` while being defined in `Oceananigans.Utils`.

I guess an inconsistency is that we export output writers from the top-level `Oceananigans` module so users can end up with access to output writers via `using Oceananigans` but without any schedules/intervals, leading to errors like

```
ERROR: LoadError: UndefVarError: TimeInterval not defined
```
cc @mukund-gupta @qwert2266

Might make sense to either export schedules at the top-level or stop exporting output writers at the top-level. Both seem like consistent solutions to me but I'll argue

**Comment by glwagner** [comment]
What would you argue?

We discussed how exporting from submodules can be nice for readability.

But after working with this paradigm for a while it actually feels like a major source of boilerplate. I would support exporting more stuff from the top level so that we don't have to import from submodules. I would also support removing all export statements from submodules (this would require some internal refactoring of import statements).
