### ISSUE TITLE
Abstraction for domains tilted with respect to `gravitational_acceleration`

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1151]
We currently assume that the vertical direction (z) is aligned with gravity, eg:

https://github.com/CliMA/Oceananigans.jl/blob/d008f382eceebfd6c4a5c5ea78cd41dc3054513d/src/TimeSteppers/update_hydrostatic_pressure.jl#L14

This is reflected by the API for `SeawaterBuoyancy`, which assumes that `gravitational_acceleration` is a scalar:

https://github.com/CliMA/Oceananigans.jl/blob/d008f382eceebfd6c4a5c5ea78cd41dc3054513d/src/Buoyancy/seawater_buoyancy.jl#L37-L42

It'd be nice to support vector `gravitational_acceleration`s that specify the gravitational acceleration in `x, y, z` independently. For this we can dispatch on whether gravitational acceleration is a `Number` to assume vertical gravity, and more generally suppor the case that `length(gravitational_acceleration) = 3`.

We can mirror this support in the API for `BuoyancyTracer`; however for that case we may want to normalize the `gravitational_acceleration` vector so that the definition of buoyancy remains the same.

This will require adding buoyancy forces to the horizontal momentum equations.

We may also want to have a discussion about using dispatch to distinguish between hydrostatic versus non-hydrostatic physics (which we do for every term _except_ pressure). Calculating the hydrostatic pressure even when the model is non-hydrostatic is both a more convoluted algorithm as well as being more memory / computationally expensive. This change could be easily dealt with in the same PR that adds buoyancy terms to the horizontal momentum equation by also adding a buoyancy term to the vertical momentum equation, setting `pHY = nothing`, and providing both 

```julia
update_hydrostatic_pressure!(::Nothing, args...) = nothing
```

and operators like

```julia
∂xᶠᵃᵃ(i, j, k, grid::AbstractGrid{FT}, ::Nothing) where FT = zero(FT) 
```

Thus switching to having a single pressure field only requires a handful of new lines, and we can keep the kernel for calculating hydrostatic pressure if/when we implement a hydrostatic-only model.

**Comment by glwagner** [comment]
@ali-ramadhan another possibility is to write a special term for horizontal hydrostatic pressure gradients that does the right thing when `pHY=nothing`.

**Comment by tomchor** [comment]
Dropping by because I need this example to run a tilted bottom boundary layer for my research. Is anyone currently working on this issue?

**Comment by ali-ramadhan** [comment]
@tomchor Ah I was considering working on it last week to simulate plumes under sloping Antarctic ice shelves. I'll post back in a bit with a more complete reply!

**Comment by tomchor** [comment]
Thank you! I appreciate it. I'm assuming this is a relatively simple issue to resolve?

**Comment by ali-ramadhan** [comment]
> I'm assuming this is a relatively simple issue to resolve?

Unfortunately not due to our current algorithm that we inherited from MITgcm, but which we hope to change pretty soon.

Right now Oceananigans splits up the pressure into the hydrostatic pressure anomaly and the non-hydrostatic pressure (see https://clima.github.io/OceananigansDocumentation/stable/numerical_implementation/pressure_decomposition/).

MITgcm did this to facilitate easy switching between a hydrostatic mode and a non-hydrostatic mode: to turn a non-hydrostatic model into a hydrostatic one, just don't compute the non-hydrostatic pressure and recompute w from the continuity equation. But we feel we can use multiple dispatch to implement a hydrostatic model in Julia. This algorithm also requires extra memory (2 pressure fields instead of just 1). So we're hoping to change the algorithm to only use 1 pressure field and get rid of this pressure decomposition.

The algorithm also makes it difficult to implement tilted gravity because the hydrostatic pressure anomaly is computed as

```
pHY′ = ∫ buoyancy_perturbation dz from z=0 down to z=-Lz
```

where `buoyancy_perturbation = g * (αT - βS)` if you're using a linear equation of state. So now if gravity is tilted it's not just a vertical integral. I'm actually not sure how to modify the vertical integral if gravity is tilted...

Seemed easier to move away from this vertical integral by not decomposing pressure then we should be able to easily add in support for tilted gravity via a `bg⃗` in the momentum equation where `g⃗ = g⃗(x, y, z)` can be whatever the user wants.

Not sure if we have an issue discussing this change to the pressure decomposition, but if it doesn't exist then I can open one to track progress on it.

**Comment by ali-ramadhan** [comment]
@glwagner may have some thoughts here. I may be overstating the difficulty of implementing tilted gravity.

**Comment by glwagner** [comment]
Might be best if I just submit a PR?

**Comment by glwagner** [comment]
Was mostly trying to figure out the user API; implementation is clear.

**Comment by ali-ramadhan** [comment]
For user API, we could allow the `gravitational_acceleration` `SeawaterBuoyancy` kwarg to accept multiple types of inputs:

1. `gravity::Number` would set a constant z-component gravitational acceleration.
2. `gravity::Function` will assume a `g_z(x, y, z)` z-component gravitational acceleration.
3. `gravity::Tuple{Number,Number,Number}` will assume constant tilted gravity `(g_x, g_y, g_z)`.
4. `gravity::Tuple{Function,Function,Function}` will assume arbitrary tilted gravity where each component is a function of (x, y, z).

I'm guessing we just want 1 and 3 for now (should be easy to implement 2 and 4 later).

**Comment by wenegrat** [comment]
I am of course very interested in tilted domains, so have been following along on this discussion. 

Two comments:
- I wanted to flag for @glwagner and @ali-ramadhan the issue that the above changes to the pressure solver would impact issue #1036, which relies on the decomposition of pressure into hydrostatic and non-hydrostatic components. I'm not sure how big an issue this would be, but good to be aware.

- If you rotate gravity, you likely also want to allow the planetary rotation vector to also be rotated. 

- For most slope angles of ocean relevance (where small angle approximations hold), the only change to the vertical momentum equation due to rotation is an additional term of order $`f\theta/\Lambda`$ where $`\Lambda`$ is the vertical shear. So if $\theta \sim O(f/\Lambda)$ then this term is also of the same order as other non-hydrostatic terms, thus, potentially possible to leave the pressure solver as is (with the limit of small-ish slope angles)?

**Comment by glwagner** [comment]
> I wanted to flag for @glwagner and @ali-ramadhan the issue that the above changes to the pressure solver would impact issue #1036, which relies on the decomposition of pressure into hydrostatic and non-hydrostatic components. I'm not sure how big an issue this would be, but good to be aware.

As far as I can tell there is no impact of tilting on the pressure solver. Because we eventually solve for the non-hydrostatic pressure in all cases, the treatment for hydrostatic pressure amounts for us to a rearrangement of the buoyancy term in the vertical momentum equation. I think we can also eliminate the separate hydrostatic pressure solve if we want. The only consideration here is whether, somehow, roundoff errors affect the quality of the unsplit nonhydrostatic pressure solve for large-scale problems that in almost perfect hydrostatic balance. But this consideration is not important for the problems with tilted domains, which are typically small scale and feature large non hydrostatic pressure contributions.

> If you rotate gravity, you likely also want to allow the planetary rotation vector to also be rotated.

We currently support this: https://clima.github.io/OceananigansDocumentation/latest/model_setup/coriolis/#Non-traditional-f-plane
