### ISSUE TITLE
Positive preserving WENO scheme

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1173]
This paper shows how to define a postive preserving WENO scheme.  

Very useful for ensuring positivity of tracers in general and height in a Shallow Water Model.

https://www.sciencedirect.com/science/article/pii/S0377042711002548

**Comment by glwagner** [comment]
Awesome. It looks like it'd require a bit of serious concentration / squinting. But hopefully the existing 5th order WENO implementation:

https://github.com/CliMA/Oceananigans.jl/blob/master/src/Advection/weno_fifth_order.jl

is helpful.

To use this we need to resolve #1015 (simple fix, but requires a bit of logic in the constructor for `IncompressibleModel` similar to what's done for viscosities and diffusivities) so that we can use different schemes for different fields.

**Comment by navidcy** [comment]
@simone-silvestri is this implemented now? should we close this?

**Comment by glwagner** [comment]
We have bounds preserving WENO now. @simone-silvestri open if this is closed in error.
