### ISSUE TITLE
Output writer schedules should be checkpointed

### ISSUE THREAD

**Issue by qwert2266** [CliMA/Oceananigans.jl#1280]
When attempting to run after checkpoint, it seems to think that the last iteration it wrote to output writers was time=0, so it tries to take an enormous negative timestep so that it can write before the next time it was supposed to. Obviously this causes an error, in this case it gave a "illegal memory access" in a CUDA array

**Comment by qwert2266** [comment]
@suyashbire1

**Comment by glwagner** [comment]
A simple fix might write an `initialize_schedule!` method for `TimeInterval` that sets the `previous_actuation_time` to the current `model.clock.time`. The schedules are initialized here:

https://github.com/CliMA/Oceananigans.jl/blob/81db22f4a26396142e8cd5b5a4c50c75790c1d50/src/Simulations/run.jl#L140

`initialize_schedule!` for `TimeInterval` goes to the fallback:

https://github.com/CliMA/Oceananigans.jl/blob/81db22f4a26396142e8cd5b5a4c50c75790c1d50/src/Utils/schedules.jl#L10

I think you'll also want to change the syntax of `initialize_schedule` to take `model` as an input, so all the functions will look like `initialize_schedule!(schedule, model)`. This also affects the one non-trivial `initialize_schedule!` method here:

https://github.com/CliMA/Oceananigans.jl/blob/81db22f4a26396142e8cd5b5a4c50c75790c1d50/src/Utils/schedules.jl#L92

Ultimately I think @qwert2266 is right. We need to checkpoint both models and output writers, or, better yet, the entire `simulation`. This checkpointing issue also affects time-averages since they have to be checkpointed too.

**Comment by ali-ramadhan** [comment]
Yeah that would work but might be worth spending the extra work to support checkpointing and pickup for schedules (and time averages).

I guess we will have to pass the `simulation` when constructing a `Checkpointer` but then we're stuck with the `write_output!(output_writer, model)` function signature. We could just fully switch to passing the simulation to output writers and diagnostics?

I think we also need to nuke `restore_from_checkpoint`.

**Comment by glwagner** [comment]
> We could just fully switch to passing the simulation to output writers and diagnostics?

Doesn't seem like there's much of a downside to that?

If `OutputWriters` are basically fancy functions of `model`, but checkpointing depends on the `Simulation`, then a `Checkpointer` might not be an output writer at all...

We may want have a pow wow and rethink the whole concept of checkpointing?

**Comment by glwagner** [comment]
I'm closing this because it's unclear if it's still a concern... please open if it is. There are likely quite a few outstanding issues with checkpointing...
