### ISSUE TITLE
Initial and boundary condition setting for a channel flow along y-direction

### ISSUE THREAD

**Issue by qiangdeng** [CliMA/Oceananigans.jl#1294]
Hi there,

I'm trying to rum a simulation for a channel flow along the y-direction, but there are some problems about the initial and boundary condition setting. 

Currently, I set the north and south boundary condition for 'v' to be a constant -0.5, and set the initial condition for 'v' also to be constant -0.5, but after using 'set!(model,...)', the value of 'v' still be 0 inside the whole domain. 

I have attached the code here. Is there any mistake in my setting?

Thank you very much.

Qiang
---------------------------------------------------------------
```julia
using Oceananigans
using Oceananigans.Fields
using Oceananigans.Utils
using Oceananigans.BoundaryConditions
using Oceananigans.Grids
using Oceananigans.Advection: UpwindBiasedFifthOrder
using Oceananigans.Diagnostics: FieldMaximum
using Oceananigans.OutputWriters: JLD2OutputWriter, FieldSlicer, TimeInterval

grid = RegularCartesianGrid( topology=(Periodic, Bounded, Bounded), size=(16, 16, 128), x=(0, 1), y=(0, 1), z=(-0.5, 0.5))

closure = IsotropicDiffusivity(κ=1.0)

v_bcs = VVelocityBoundaryConditions(grid, 
    north = NormalFlowBoundaryCondition(-0.5),
    south = NormalFlowBoundaryCondition(-0.5)
    #north = ValueBoundaryCondition(0.5),
    #south = ValueBoundaryCondition(0.5)
)

model = IncompressibleModel(grid=grid, 
    closure=closure,  
    boundary_conditions = (v=v_bcs)
)

set!(model, v=-0.50)

v_0=model.velocities.v
v_0[:,:,128]
```

**Comment by ali-ramadhan** [comment]
Hi @qiangdeng!

I think the v boundary conditions weren't being applied due to an unfortunate typo: I think you need to pass `boundary_conditions = (v=v_bc,)` (a named tuple):

```julia
julia> model = IncompressibleModel(grid=grid,
                       closure = closure,
           boundary_conditions = (v=v_bcs)
       )

julia> model.velocities.v.boundary_conditions.north
BoundaryCondition: type=NormalFlow, condition=nothing
```

```julia
julia> model = IncompressibleModel(grid=grid,
                       closure = closure,
           boundary_conditions = (v=v_bcs,)
       )

julia> model.velocities.v.boundary_conditions.north
BoundaryCondition: type=NormalFlow, condition=-0.5
```

Oceananigans should have produced an error asking for a `NamedTuple`: https://github.com/CliMA/Oceananigans.jl/blob/f16989d69030b61ea1b1fdf7fe5659b5fa25aadd/src/Models/IncompressibleModels/incompressible_model.jl#L91

This might be a bug. Which version of Oceananigans are you using? To print the status of your Julia environment including your Julia version and the version of Oceananigans you're using, you can do use the `Pkg.status()` command: julialang.github.io/Pkg.jl/v1/repl/#repl-status

PS: When posting code on GitHub it's nice to enclose the code in triple backticks (```) so it gets formatted as code making it easier to read. I edited your post to do this.

**Comment by ali-ramadhan** [comment]
I'm really confused why but when I use `boundary_conditions = (v=v_bcs,)` now `set!(model, v=-0.5)` works just fine and `v = -0.5` everywhere.

**Comment by ali-ramadhan** [comment]
Ah ok I see why your original script didn't work now.

When executing

```julia
model = IncompressibleModel(grid=grid,
                closure = closure,
    boundary_conditions = (v=v_bcs)
)
```

this assigned `v_bcs` to the new variable `v` and passes it to the `IncompressibleModel` function. `v_bc` itself is a `NamedTuple` containing `x, y, z` properties so the `IncompressibleModel` constructor does not complain.

Since the named tuple that is passed does not not have a `v` property, the velocities get the default boundary conditions (free slip and no normal flow).

Then when you call `set!(model, v=-0.5)` it fills v to be -0.5 everywhere but then `update_state!(model)` is called to ensure that the velocity field is incompressible (divergence-free) by performing a pressure projection step. Since the default boundary condition enforces no-normal flow, the velocity cannot be -0.5 everywhere so the pressure field updates it to be zero to enforce incompressibility.

This is a pretty subtle bug... Since the proper named tuple can't be checked for in the constructor function signature, I wonder if it's worth adding a manual check to make sure a `NamedTuple{(:x,:y,:z)}` was not passed to the model constructor.

**Comment by glwagner** [comment]
> This is a pretty subtle bug (related to #1204)... Since the proper named tuple can't be checked for in the constructor function signature, I wonder if it's worth adding a manual check to make sure a NamedTuple{(:x,:y,:z)} was not passed to the model constructor.

I think this is the right band-aid for now.

A cleaner but maybe more intensive solution is to use a distinguishable type for `FieldBoundaryConditions` rather than a `NamedTuple`. This would probably work fine, especially if we define `getindex` for `i=1, 2, 3` for `FieldBoundaryConditions` so that it functions identically to a `NamedTuple` with fields `x, y, z` (not sure we need `iterate` but we could define that too).

**Comment by glwagner** [comment]
I guess this is resolved after a fashion.
