### ISSUE TITLE
cell_advection_timescale should dispatch on `Flat` topologies

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1309]
`cell_advection_timescale` calculates the minimum time-scale associated with advection across a cell:

https://github.com/CliMA/Oceananigans.jl/blob/7d3f25e99fbe03ba019de77208e08cf42840ffc8/src/Utils/cell_advection_timescale.jl#L2-L12

but in the case that a dimension is `Flat`, there is no associated time-scale for that dimension.

We probably need three functions of the form `cell_advection_timescale(topo::AbstractTopology, u, dx)` that return `Inf` when `topo` is `Flat` and `maximum(abs, u) / dx` otherwise, so that velocities across `Flat` dimensions don't end up limiting the time step.

**Comment by glwagner** [comment]
cc @tomchor

**Comment by francispoulin** [comment]
Should also restructure the new `ShallowWaterModel` version in a similar way.

**Comment by glwagner** [comment]
> Should also restructure the new `ShallowWaterModel` version in a similar way.

Quite! In the context of `ShallowWaterModel`, this will only effect 1D models where adaptive time-stepping may not be that useful (because the vertical dimensions is `Flat` _a priori_). But we can add it there too if we think that's important.

**Comment by navidcy** [comment]
Is this ongoing?

**Comment by glwagner** [comment]
I don't know.

**Comment by tomchor** [comment]
I don't think so because this function now uses `min_Δx` and friends:

https://github.com/CliMA/Oceananigans.jl/blob/87270dea8d1553339bb8f806034df462604111d2/src/Utils/cell_advection_timescale.jl#L10-L12

These functions should now return `Inf` when used on a `Flat` dimension:

https://github.com/CliMA/Oceananigans.jl/blob/87270dea8d1553339bb8f806034df462604111d2/src/Grids/regular_rectilinear_grid.jl#L278-L285
