### ISSUE TITLE
implicit free-surface for `ShallowWaterModel`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1378]
I think it would be helpful to allow for an implicit free-surface in `ShallowWaterModel` to allow us to use larger time-steps when simulating the solution.

@glwagner : how difficult do you think this would be?

**Comment by glwagner** [comment]
I'm not sure how this can be done --- the free surface equation is coupled to the transport equations, which are nonlinear. Doesn't this mean we need to be able to solve a nonlinear problem iteratively in order to use an implicit time-stepping method?

@christophernhill is working on an iterative conjugate gradient solver. It's possible this will work for nonlinear problems as well as linear problems. But we have to wait until that work is complete.

**Comment by francispoulin** [comment]
The evolution equation for the free surface is the same for the `HydrostaticFreeSurface` and `ShallowWater` models so that would not require anythinng differently.  It would just mean that `ShallowWaterModel` would use the solver that the other model uses.  

The other part, I think, is to include the pressure terms implicitly.  I thought that's what the implicit version of `HydrostaticFreeSurfaceModel` did, but if I'm mistaken, my apologies.

**Comment by glwagner** [comment]
Ah! In `HydrostaticFreeSurfaceModel`, the implicit free surface algorithm uses a pressure correction / operator splitting method. It's really a sort of pseudo-implicit treatment (because the velocity field is _corrected_ rather than time-stepped concurrently with the free surface.

I think it would be possible to implement an operator splitting method in `ShallowWaterModel`.

But is this useful? This could lead to a loss of accuracy (I'm not sure). In the even that the pressure / free surface displacement is passive (so one doesn't care about accuracy), it might be better to use a rigid lid approximation (and thus a two-dimensional `IncompressibleModel`, rather than `ShallowWaterModel`). But I am ready to stand corrected.

**Comment by glwagner** [comment]
By the way, the implicit free surface algorithm is not yet fully implemented. However, the details of what will be implemented are here:

https://mitgcm.readthedocs.io/en/latest/algorithm/algorithm.html#pressure-method-with-implicit-linear-free-surface

**Comment by christophernhill** [comment]
@francispoulin and @glwagner once we have linear case running we could look at the variations described here https://mitgcm.readthedocs.io/en/latest/algorithm/nonlinear-freesurf.html?highlight=non-linear . They all use similar building blocks, so they can leverage the linear case as a starting point - but then some extra pieces/tweaks will be needed.

**Comment by francispoulin** [comment]
Thanks @glwagner and @christophernhill for the information and help.  I agree it's probably better that I until `HydrostaticFreeSurfaceModel` matures a but more and then we can discuss how some of this might be used in `ShallowWaterModel`.  

The basic problem that I'm having is that the CFL condition seems rather right and I thought that implicit time stepping might be helpful, but I will certainly wait for now and we can discuss this more later.  Thanks!

**Comment by glwagner** [comment]
@francispoulin do you mean that you have to take time-steps well below what CFL would otherwise dictate for stability?

**Comment by francispoulin** [comment]
Yes, I am getting `NaN's` and a bit puzzled as to why.  I will try the biharmonic diffusion you mentioned, in case that fixes things.  Also, I will try setting up the same initial conditions in `HydrostaticModel` and see how that compares.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
