### ISSUE TITLE
Document the parameters that users can change and their default values

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1427]
For things like the Coriolis parameter, rotation rate, expansion coefficient for linear equations of state, gravitational acceleration, etc. it would be good to document them in a table showing where all these parameters are set, what their default value is, etc.

I guess there is some overlap between this goal and https://github.com/CliMA/CLIMAParameters.jl but not sure what or how much to take from it.

I guess one advantage of old-school namelists is that when you have tons of parameters, it's easy to understand and control their values with a well-documented namelist.

Maybe a start would be a function like `physical_parameters(model)` defined for each model type that returns a named tuple of values for the important physical parameters so you can see what's being used. This function can then also be used to document all the physical parameters as metadata in JLD2 or NetCDF.

cc @sandreza

**Comment by francispoulin** [comment]
I like this idea and `physical_parameters(model)` seems like a good name as it is very descriptive

**Comment by glwagner** [comment]
That's a nice concept. We can use

```julia
function physical_parameters(model::AbstractModel)
    parameter_list = [physical_parameters(getproperty(model, component)) for component in propertynames(model)]
    return merge(parameter_list...)
end

physical_parameters(component) = NamedTuple()
```

and then each component can opt-in to define a `NamedTuple` of physical parameters implemented therein.

**Comment by glwagner** [comment]
As far as I can tell the main purpose of `CLIMAParameters` is to provide a central / global place to specify common parameters found in different model components. For example, `HydrostaticFreeSurfaceModel` has a `gravitational_acceleration` for both `buoyancy` and `free_surface`.

On the other hand, it turns out that it's sometimes convenient for these to be different for testing and experimentation, which may impose additional requirements on `CLIMAParameters` that were not part of the original design.

One possible solution might be to build a global `CLIMAParameters` instance in `Oceananigans` that's referenced in model constructors for default parameter values (but we can still let users change parameters when instantiating various model components if they want).

A possible implicit goal of CLIMAParameters is to _restrict_ the user interface so that users "can't mess up"; eg users can't accidentally set `gravitational_acceleration` in `free_surface` and erroneously expect that this also changes `gravitational_acceleration` for buoyancy.

Food for thought...

**Comment by francispoulin** [comment]
Hmmm, lots to think about.  I don't know CLIMAParameters so can't say anything about that.  However, I will add that in principle, I think that each parameter should only be set once, and then shared where needed.  I have used codes before where you needed to set a parameter on multiple locations, and it strikes me as there is a lot of potential for bugs to arise.   I would hope that the user specifies them at the begining of their script and then Oceananigans does all the hard work from there on.

Sorry if i misunderstood something here.

**Comment by glwagner** [comment]
I'm closing this issue because I'm judging that it's not of current, timely relevance to Oceananigans development. If you would like to make it a higher priority or if you think the issue was closed in error please feel free to re-open.
