### ISSUE TITLE
Basic Documentation for ShallowWaterModel?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#1460]
I think it's time to have something there. At lease a docs page that writes down the equations solved and the state variables...

cc @francispoulin

**Comment by francispoulin** [comment]
Excellent idea @navidcy and I'm happy to write something up.  Considering there is also `HydrostaticFreeSurfaceModel` that has been developed, we should probalby think about where to present the equations for all three.  

Were you thinking on the main page?  I think we could have something under Oceananigans.jl and before getting help for each model: IncompressibleModel, HydrostaticFreeSurface and ShallowWater.  

It occurs to me that all models are incompressible in three-dimensions but I am not going to suggest we change the name since IncompressibleModel appears everywhere.  But in the description we could describe it as Nonhydrostatic rigid lid, or something.  

I'm happy to write model equations for all three, after I have an idea as to where we want to put it.

**Comment by navidcy** [comment]
Tbh I didn't give it as much thought as you may be implying with your message above :)

But I just realized that the ShallowWater example talks about "equations in conservative form" and some users may have no idea what we are talking about...

Let's see what @glwagner and @ali-ramadhan think on this. Perhaps with the current status of fast development it makes sense to hold on Docs for later..?

**Comment by francispoulin** [comment]
I am very curious to hear what people think but do think it would make sense to have a tab called Models where we state briefly the model equations.  This way the user knows exactly what their getting themselves into.  We have that for `IncompressibleModel` in the `Physics` section, and feel the other two models should get a bit of converge.  Even though the numerical methods will evolve, the governing equations will not change.  Or if they do we'll be adding more into them.

**Comment by ali-ramadhan** [comment]
Would definitely be good to have some documentation of the equations solved and numerical methods for the shallow water model.

I feel that having a maintained example might be more important than detailed docs right now since people might want to just use the model first (e.g. #1362).

This issue probably overlaps with the discussion in #1414.
