### ISSUE TITLE
Fusing kernels for calculating diagnostics to improve performance

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1483]
So, I've been running some simulations with a bunch of diagnostics, which make the simulation slower. I think some of the diagnostics that I'm calculating are already being calculated by Oceananigans (like derivatives). If I understand correctly, in each of those cases Oceananigans calculates that variable once to get the tendencies and then does the same calculation again when for my diagnostics, which seems wasteful.

Is it possible (or desirable) to create a way for the code not to do the calculation twice if the user wants that diagnostic specifically? Maybe pass options when creating the model like:

```julia
model = IncompressibleModel(grid, computed_fields=(:dudz, :dvdz,))
```
so that those fields get stored just like the velocity and the tracers do?

Thoughts?

**Comment by francispoulin** [comment]
The library computes the derivatives that are required to compute the tendencies, but they are not stored since that would not be very efficient.  Getting some of these values but I don't know what that would look like.  Also, if you are not computing this field at every time step, the cost of computing it sepratelyl might not be that high, but that of course depends on the particular problem you are dealing with.

**Comment by glwagner** [comment]
For better or for worse, Oceananigans currently does not store intermediate terms in the computation of a PDE's right hand side (with notable exceptions hydrostatic pressure and eddy diffusivities). In other words, a single, sometimes large kernel that evaluates the right hand side at each grid point `i, j, k` is compiled for each PDE in a user's model, and there's no way to pull out intermediate steps in that calculation to use elsewhere.

It's important to note when considering optimization strategies that our computations are probably memory-limited, rather than compute-limited. In other words, we think the process of transferring data from global memory to local thread memory is a bottleneck for our computations (we can really only know this through profiling a particular application, however, since all models are different...) Storing intermediate components of the tendency terms would probably create more memory accesses overall (since rather than immediately using intermediate results for subsequent calculations, we would have to send them to global memory, and then back, to complete the evaluation of a tendency) --- and thus could slow down tendency evaluations that are performed 1-3 times per time-step. For example, our best idea for speeding up tendency evaluations is to better manage memory movement using GPU shared memory (unfortunately, we haven't had the time to explore such optimization strategies...)

I think there may be other ways to optimize diagnostics calculations, however.

# Fusing `ComputedField` kernels

One possibility to speed up diagnostics is to "fuse" kernels for different `ComputedField` diagnostics. The kernel for a `ComputedField` is

https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/Fields/computed_field.jl#L112-L115

where `operand` is an `AbstractOperation`. But different `ComputedField`s may somehow depend on the same underlying data in memory. Thus if the kernels for differnet `ComputedField`s are fused into one, we overlap memory accesses for different computations. Our computations are usually memory-limited... so its possible this strategy could produce significant speed ups. For example, for two `ComputedField`s we might have something like

```julia
function compute!(field1, field2)
    # calls _compute_two(field1.data, field2.data, field1.operand, field2.operand)
end
```

and the kernel

```julia
@kernel function _compute_two!(data1, data2, operand1, operand2)
    i, j, k = @index(Global, NTuple)
    @inbounds data1[i, j, k] = operand1[i, j, k]
    @inbounds data2[i, j, k] = operand2[i, j, k]
end
```

There should also be a way to generalize to the nth case using some `ntuple` magic.

(Note that we tried this with tracer kernels previously without obtaining any speed up, but overlapping `ComputedField`s could be a more promising application of this technique.)

# Using `mapreduce` for averaging `AbstractOperations`

We also might be able to apply `mapreduce` directly to `AbstractOperations`, rather than using our currently strategy of storing the intermediate result of an operation in a `ComputedField`, and then averaging the intermediate result. This technique is discussed on #1422 .

**Comment by tomchor** [comment]
> The library computes the derivatives that are required to compute the tendencies, but they are not stored since that would not be very efficient

Oh yeah, for sure! The idea is that they would be stored only if the user specified interest in them. That way instead of calculating twice and storing once, the code would calculate and store once. The default behavior still would be calculating and not storing though.

**Comment by tomchor** [comment]
> In other words, a single, sometimes large kernel that evaluates the right hand side at each grid point i, j, k is compiled for each PDE in a user's model, and there's no way to pull out intermediate steps in that calculation to use elsewhere.

That's interesting. I wasn't aware there was only one kernel for the whole RHS. That's pretty smart.

> One possibility to speed up diagnostics is to "fuse" kernels for different ComputedField diagnostics. 

That's a really cool idea. I can see how we could do that with `KernelComputedField`s, but I can't really see how to do it for `ComputedFields`. It would definitely be great if that could be easily automatized.

**Comment by glwagner** [comment]
> That's a really cool idea. I can see how we could do that with KernelComputedFields, but I can't really see how to do it for ComputedFields.

I think we understand how to write a `compute!` function that fuses the kernels for multiple `ComputedField`s or `KernelComputedField`s. But the harder part is designing an API that implements fusion for an output writer. We might need to add a property called something like `fused_compute` to both `OutputWriter`s. For example, `JLD2OutputWriter` fetches output in a loop:

https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/OutputWriters/jld2_output_writer.jl#L195-L196

where `fetch_and_convert_output` calls `fetch_output`:

https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/OutputWriters/fetch_output.jl#L13-L16

which in turn calls `compute_at!`.

But we want to trigger _one_ call to `compute_at!` for all the outputs at the same time ... I think ... so that requires some refactoring and API design.

**Comment by glwagner** [comment]
And whatever we come up with it also has to work with `WindowedTimeAverage`, which calls `fetch_output` here:

https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/OutputWriters/windowed_time_average.jl#L135

**Comment by glwagner** [comment]
> I wasn't aware there was only one kernel for the whole RHS.

For example, the kernel for "u" (x-velocity) is

https://github.com/CliMA/Oceananigans.jl/blob/9b52f3f911d26a66c75f1c3cb58fdd0a1cecb131/src/Models/IncompressibleModels/velocity_and_tracer_tendencies.jl#L44-L66

**Comment by glwagner** [comment]
Maybe a cleaner solution than adding a property to `OutputWriter`s is to create a new type for a collection of `ComputedField`s whose kernels are fused, something like `FusedComputedFields`. Then we need to generalize the output writers and time-averaging machinery to permit dispatch for correct behavior for this special case.
