### ISSUE TITLE
Field slicers and StepRange

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1512]
Is there any special reason `FieldSlicer`s/`parent_slice_indices` aren't defined for `StepRange`s?

**Comment by glwagner** [comment]
None other than it requires typing the code and adding a test or two. Are you suggesting extending the capabilities of `FieldSlicer`? I think that's a nice idea if so!

**Comment by tomchor** [comment]
I am. I think it should be useful when you're running a very big simulation but you wanna same space on disk and not necessarily write every single grid point. (Which is exactly why I tried to use this feature and found out it didn't exist haha)

**Comment by glwagner** [comment]
It might be reasonable to simply generalize `parent_slice_indices` for `AbstractRange`s:

https://github.com/CliMA/Oceananigans.jl/blob/a4be062049b096ce20ac0908ee40f0b81b16d5ae/src/Diagnostics/field_slicer.jl#L61

We might want to use `minimum(rng)` rather than `rng[1]`:

https://github.com/CliMA/Oceananigans.jl/blob/a4be062049b096ce20ac0908ee40f0b81b16d5ae/src/Diagnostics/field_slicer.jl#L64

And we can return `StepRange(left, step(rng), right)` rather than `UnitRange(left, right)`:

https://github.com/CliMA/Oceananigans.jl/blob/a4be062049b096ce20ac0908ee40f0b81b16d5ae/src/Diagnostics/field_slicer.jl#L71

**Comment by glwagner** [comment]
Note that functionality for reduced fields also would need to be generalized from `UnitRange` to `AbstractRange`:

https://github.com/CliMA/Oceananigans.jl/blob/a4be062049b096ce20ac0908ee40f0b81b16d5ae/src/Diagnostics/field_slicer.jl#L54

**Comment by glwagner** [comment]
On #1521 I'm trying to move `FieldSlicer` to the `Fields` submodule.

**Comment by glwagner** [comment]
@tomchor see if https://github.com/CliMA/Oceananigans.jl/pull/1526 fits your needs.

**Comment by tomchor** [comment]
Yeah, that's great! Thanks! Also I just tested it and it appears to work fine so kudos for get that working so fast
