### ISSUE TITLE
Immersed boundaries for tracers

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1548]
Probably a question for @whitleyv or @glwagner but how hard would it be to support tracers with the current immersed boundary implementation?

My understanding is that currently the velocity tendencies are corrected inside the immersed boundary but not tracer tendencies (which seems to work fine in 2D?).

Is it as simple as adding a new kernel like [`_correct_immersed_tendencies!`](https://github.com/CliMA/Oceananigans.jl/blob/6bfc1551c57403268138b85620d88dba8114a4c0/src/Models/IncompressibleModels/correct_incompressible_immersed_tendencies.jl#L43) but for tracers?

cc @gianlisi @wanyingkang

**Comment by francispoulin** [comment]
I am also very curious to know the answer as I'd like to add immersed boundaries to shallow water, and would very much like to include tracers if possible.

**Comment by glwagner** [comment]
I think the next step is a fully-fledged implementation that supports `Flux` boundary conditions (and possibly others). We are almost there with the latest `TurbulenceClosures` refactor.

If `correct_immersed_tendencies!` is copy/pasted for tracers then all tracers will be set to zero inside a boundary.

The algorithm I am thinking of would have the following components:

1. Implement a "mask" that replaces `correct_immersed_tendencies!` that forcibly overwrites immersed regions to specified values in `update_state!` (this is effectively what `correct_immersed_tendencies!` does now)
2. Extend `calculate_boundary_tendency_terms!` to adjust tendencies in cells adjacent to immersed boundaries. This involves a) subtracting out the "spurious" component associated with a diffusive flux across an immersed boundary and b) adding in the "true" boundary flux that's either specified by the user, or implied by a `Value` / `Gradient` boundary condition.

**Comment by whitleyv** [comment]
@ali-ramadhan I believe tracers are something that should not be hard to implement. I have been working on an arbitrary IBM method, on the branch [vw/arbitrary_immersedboundary](https://github.com/CliMA/Oceananigans.jl/tree/vw/arbitrary_immersedboundary). I would prefer to add tracers to this instead of the version in the main branch, since this new version will be pretty different in form. It will also be easier on this new arbitrary version to implement non-dirchlet BCs. I have a couple things to fix on this branch, and then I hope to add tracers within the next month.

**Comment by glwagner** [comment]
We support tracers now.
