### ISSUE TITLE
User interface for specifying stretched coordinates and curvilinear grids

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1551]
This issue picks up a conversation on #1544 about user interface design for stretched grids.

On that PR various proposals for specifying the nodes / cell interfaces of `VerticallyStretchedRectilinearGrid` were proposed. To preface: we don't need to have a _single_ interface, since it may actually be useful to have various options for specification. Some users may want to provide arrays that specify cell interface locations, others may want to use generating functions.

The currently proposed options require some understanding of the staggered grid. The current interface requires a keyword argument `zF` that specifies the location of vertical cell interfaces. #1544 proposed to change the name of this argument to `z_faces` or `z_stretch`. For this interface the meaning of the keyword argument needs to be explained in terms of the staggered grid.

An alternative possibility is an interface that uses a mapping or warping function that maps from a continuous, unstretched coordinate to a stretched coordinate. This interface would then resemble the interface for `RegularRectilinearGrid` in that users would provide both `size` and `z` to specify the number of grid points and the end points of the interval. However, an additional argument such as `z_stretching` would be used to specify how the grid is compressed or stretched.

One example is to generate a grid with Chebyshev spacing in z. For this a user writes

```julia
grid = VerticallyStretchedRectilinearGrid(size = (Nx, Ny, Nz), 
                                          x = (0, 2π),
                                          y = (0, 2π),
                                          z = (-1, 1),
                                          z_stretching = z -> cos(π / 2 * (z - 1)))
```

The main difference between this type of interface and an interface using a generating function with keyword argument `z_faces` is that the number of grid points is not a parameter in the continuous map `z_stretching`.

cc @francispoulin @kburns @tomchor @ali-ramadhan

**Comment by glwagner** [comment]
For completeness I think the same grid could be generated with the current interface using

```julia
grid = VerticallyStretchedRectilinearGrid(size = (Nx, Ny, Nz), 
                                          x = (0, 2π),
                                          y = (0, 2π),
                                          zF = k -> cos(π * (2k - 1) / 2Nz))
```

I suppose the main difference is that the syntax with `z_stretching` makes the bounds of the domain explicit, whereas when using `zF` a code-reader has to compute the domain bounds by plugging `k = 1` and `k = Nz + 1` into the generating function.

**Comment by francispoulin** [comment]
Thanks @glwagner for carrying the discussion here.  I think you have presented two options very nicely.  Good to know that we could possibly have both, but that might be a bit more work to put together and maintain.

Personally, I prefer the first approach of specifying the size, the domain and the faces.  I have come around and think that using `z_Faces`, might be nice since the grid doesn't need to be stretched necessarily.  It can be anything.  I prefer this for the following reasons,

- It's consistent with how we define a regular grid so easy to switch between the two grids
- We don't have to specify `Nz` in the definition of `stretch` or `Faces`

I don't think either method can do any more or less than the other.  The PR in question currently does something like the first option, but it should be easy enough to modify it do the second.
 
I was going to fix up #1532 yesterday but then I thougth I would hold off to see what people say in this discussion.

**Comment by glwagner** [comment]
A tidbit: I'd advocate for `z_faces` rather than `z_Faces`. I don't think we capitalize any of our other keyword arguments.

> We don't have to specify Nz in the definition of stretch or Faces

Is `z_faces` different from `zF`? (Is this more than just changing the name of the keyword argument?) Perhaps I don't understand how `z_faces` works?

**Comment by glwagner** [comment]
Another important point is that this discussion is not about "deciding" on a _single_ user interfaces, but rather deciding what interfaces we want to put into the code. We can and perhaps should have multiple ways of specifying stretched grids. We have already agreed that specifying cell interface locations with an array (loaded from file, for example) is an important pattern to support.

**Comment by francispoulin** [comment]
`z_faces` sounds good to me.

As a newish user who will be reading examples and trying to figure things out, I think this is clearer than `zF`.  Certainly people can learn to use either without much difficulty.  Also, I thought that `zF` is mostly used for a face, wheres we want multiple, so plural.  I suppose even `zFs` would be better in my mind.

**Comment by glwagner** [comment]
I agree. Originally `zF` was chosen because this kwarg specifies the property `grid.zF`.

**Comment by francispoulin** [comment]
It's spelled out but I'm happy to use `zF` if that's the consensus. I am prepared to make the change in the PR, #1532 , if people like.

**Comment by glwagner** [comment]
What's the difference in terms of functionality between `zF` and `z_faces`? Is there a difference?

**Comment by francispoulin** [comment]
A cosmetic difference as I thought it might be easier to read, but I could be wrong.  I am not suggesting a functional difference.

**Comment by glwagner** [comment]
I agree that `z_faces` is clearer! I just wanted to be sure we were talking about the same changes.

I believe that specifying the grid with `z_faces` does indeed require knowledge of the number of grid points, because the user specification depends on the vertical _index_. The case of a uniform grid illustrates this point: `z_faces = k -> k * Lz / Nz`.

I think it'd be nice to have both a "discrete" interface that uses the `z_faces` or `z_cell_interfaces` keyword argument, as well as a "continuous" interface that I described above.

**Comment by francispoulin** [comment]
I agree that to define the grid with `z_faces` we need to know the number of grid points, but that can be done internally.  I don't believe we need that in the arguments.  In the example you showed previously, with a `cheb` grid, you specified it in terms of a function of `z`.  I can imagine the user specifying `z=(0, Lz)`, `Nz` and some `f(z)`, and then we compute what the grid is.  I guess if `f(z)=z`, then we get a linear or uniform grid.  

I imagine some people might prefer to be more hands on and specify it in terms fo indices.  Both clearly can work.

What your suggesting sounds very general, which is nice, but also a bit complicated.  I wonder if we might want to start with something simple, one of the two, and then as we get to use it then decide how we want to change it.

I'm perfectly fine with specifying the index form, since that is consistent with what we are currently doing, I think.

**Comment by glwagner** [comment]
> I agree that to define the grid with z_faces we need to know the number of grid points, but that can be done internally.

What do you mean? Can you provide an example?

**Comment by francispoulin** [comment]
Sure.  

This [code ](https://github.com/CliMA/Oceananigans.jl/blob/78f1e2910355ca4213241b23525b717c73d77900/test/test_stretched_grid.jl#L5) shows different functions that I have defined, similar to your `cheb` example above.

Passing the function, which in this context I've called `stretched` but agree we should change it,  [here](https://github.com/CliMA/Oceananigans.jl/blob/78f1e2910355ca4213241b23525b717c73d77900/src/Grids/stretched_rectilinear_grid.jl#L54) you will see that the function is evaluated to define the grid.

It's nothing fancy, but it does the trick.  

Sorry if I misunderstood your suggestion?

**Comment by glwagner** [comment]
Are you proposing a third interface that takes a 3-argument function of `x, L, N`?

**Comment by francispoulin** [comment]
It seems natural to me to have a function of 3 arguments, `x, L, N`, as those are all needed to define the grid.  There are other ways of doing it I'm sure, and I am open to other options.

I agree with you that given the current setup using `zF`, we do need the number of interfaces.  This other option would not as we are passing functions instead.

I very much like the examples you set up and think that would be very attractive from the user perspective.  

Another option that I think should be included in these functions, like the two you have above, is an argument saying where the center (or something else) is in the stretched grid.  It could be the left boundary, right boundary, center or anywhere else.  The physics should be the guide on where to concenrate the grid.

**Comment by glwagner** [comment]
A possible implementation of `QuadraticallyStretchedFaces` with the "z faces interface" might allow syntax like

```julia
grid = VerticallyStretchedRectilinearGrid(size = (Nx, Ny, Nz), 
                                          x = (0, 2π),
                                          y = (0, 2π),
                                          z_faces = QuadraticallyStretchedFaces())
```
