### ISSUE TITLE
Using `BackgroundField` is slower than I expected

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#1564]
In my attempt to study inertial instability I have two versions of the code.

1. Takes the solution to be a sum of the background and the perturbations, and **evolves the total** field.  [code here](https://github.com/CliMA/Oceananigans.jl/blob/fjp/inertia-instability-example/examples/NoDecomposition/Bickley_Gaussian_jet_total.jl)
2. Stores the basic state in `BackgroundField` and **evolves the perturbation**, like the Eady problem. [code here](https://github.com/CliMA/Oceananigans.jl/blob/fjp/inertia-instability-example/examples/Bickley_Gaussian_jet.jl)

Actually, the first one uses `BackgroundField` for the background stratification, but not for the jet.

Since evolving a solution that uses `BackgroundField` has three times as many advection terms, and in this 2D scenario advection is probably the most costly, I was expecting the slow down to be a factor of `3`.  What I actually find is a slow down of `16`!?

Is this to be expected?

**Comment by glwagner** [comment]
Doesn't it have 5 times as many advection terms? There are four advection terms associated with how the background velocity field advects the 3 momentum components and 1 tracer, and one more that describes how the perturbation velocity advects the background field.

More importantly, not all terms have the same computational cost. Here you are using a WENO advection scheme, which means that advection terms are particularly costly compared to other terms in the system.

I don't think I have enough information to say whether a slowdown of 16 is "correct" or reflects some bug / inefficiency. The result seems plausible, however, because WENO is an expensive advection scheme (especially on the CPU).

**Comment by francispoulin** [comment]
The [docs](https://clima.github.io/OceananigansDocumentation/stable/physics/navier_stokes_and_tracer_conservation/) show that in vector form there are three advection terms in momentum, because presumably the advection of the background state by the background state is zero.  That is also the case in my example.  However, even if all the terms are computed, then I would think that the 4 terms in the decomposition for both momentum and tracer equations are the following:

`Momentum -------------------- Tracer`
 `u \cdot grad u -------------- u \cdot grad c`,
`U \cdot grad u -------------- U \cdot grad c`,
`u \cdot grad U -------------- u \cdot grad C`,
`U \cdot grad U -------------- U \cdot grad c`,

compared to the one term that we have without the decomposition

`Momentum -------------------- Tracer`
`u \cdot grad u -------------- u \cdot grad c`,

Am I understanding this correctly or are there other terms that I have missed?

I agree that `WENO5` is the most expensive of the schemes, but relatively speaking should that matter?  Naively, I would think that if one term is computed with `WENO5` then 4 terms would be 4 times the cost.  I will certainly try another advection scheme and see if there is a similar scaling or not.

**Comment by tomchor** [comment]
I agree with @glwagner that we don't have enough info to say whether this slowdown in expected or not. But just as a note, does defining the parameters as `const` help? It did for me.

**Comment by francispoulin** [comment]
I am running everything on cpus and have used `const` everywhere I can. I thought `const` was mainly helpful for `gpus` but I haven't tried that yet.

**Comment by tomchor** [comment]
Mu understanding is that it is _required_ for GPU runs, but it also helps optimize CPU runs. In any case, you're using a `NamedTuple`, which is immutable, so it might not help here, but I think it's worth checking anyway.

**Comment by glwagner** [comment]
> Naively, I would think that if one term is computed with WENO5 then 4 terms would be 4 times the cost.

Okay, I understand what you're saying and I agree. Assuming that the advection term dominates the cost of a time-step, we could count the number of times the advection term is evaluated and calculate a multiplicative slowdown based on that assumption.

One issue with that assumption is that the advection terms compile to different code when using a `BackgroundField`. With a `BackgroundField` the velocity field is stored as a `FunctionField` (with almost no additional memory allocation) rather than raw data. Calling `getindex` on a `FunctionField` resolves to calling a function, whereas calling `getindex` on a `Field` / `Array` fetches data from memory. So they are different.

Naively I would expect that evaluating a complicated advection term involving `BackgroundField` would be cheaper than one that involved two concrete `Array`. But sometimes unexpected things happen (the compiler might decide to optimize the code differently...)

Can you try running the code on the GPU? I think it would be enlightening to see if there's a slowdown in that case.

We could potentially implement an interface whereby `Field`s can be used as `BackgroundField` rather than functions. That might give us some insight, because then the "additional" advection terms associated with `BackgroundField` would truly be identical to the "original" advection term.

> because presumably the advection of the background state by the background state is zero.

I would say that the background self-interaction terms are _neglected_ rather than presumed to be zero. Linear terms associated with the background fields are also neglected. The idea being that if there is a valid way to decompose a flow into background and perturbation components, then the equation that governs the background component is completely neglected (this includes both the nonlinear terms and any linear terms involving the background flow).

_Side note:_ some nonlinear terms are additionally neglected in the case of nonlinear viscosity. Ideally I think we would include these because the above argument doesn't justify neglecting them, but the implementation seemed too complicated the last time I thought about it so I put it off. I think it's a solvable problem but requires a bit of thought to integrate into the current algorithm seamlessly.

> Mu understanding is that it is required for GPU runs, but it also helps optimize CPU runs.

This is correct --- if you're missing a `const` on a variable that's used in a kernel, that kernel will fail to compile on the GPU (it won't just be slow).

**Comment by glwagner** [comment]
I believe to support concrete `BackgroundField` we need to add a method to `regularize_background_field` defined here:

https://github.com/CliMA/Oceananigans.jl/blob/7501c5325a0f7c77a89316d23ee7a56a3877dad9/src/Fields/background_fields.jl#L59-L63

that looks like

```julia
regularize_background_field(X, Y, Z, field::Field, grid, clock) = field
```

If you want to be super friendly you could also check that `location(field) == (X, Y, Z)` and `grid == field.grid` and throw an error if not so users don't get wrong results.

**Comment by francispoulin** [comment]
Thanks for the feedback @glwagner and @tomchor .  I will respond soon but I have an updated I wanted to share.

I did a simulation in each for 100 time steps a few times each. I found sometimes the second simulation was way faster than the first.  For different advection schemes I found, to my surprise, they do scale differently.

```
scheme   ratio
======   ===
C2       1.7
U3       2.4
C4       3
U5       2.4
W5       3.4
```

I would not call these offical benchmarks but more back of the envelop calculations (between friends).  But these numbers are, mostly, around 3, which is what I expected.  

For fun, I will do the same thing with GPUs (and will find out if my new code runs on a GPU).

I guess one mystery is why is it that my actual simulation ran so slowly?  I will try it again for 2 hours instead of 2 days and see how the scalings look.

**Comment by francispoulin** [comment]
For the GPU case, again for 128x128 (still rather coarse and results will depend on resolution I suspect)

```
scheme   ratio
======   ===
C2       1.2
U3       1.5
C4       2.4
U5       1.5
W5       7.0

```

In general the scalings tend to be better on GPUs vs CPUs (on this coarse grid).  It does seem that `WENO5` does much worst, relatively speaking.  

Benchmarks that I did with @ali-ramadhan found that on GPUs vs CPUs, shallow water model could be faster by a factor of `170`, which was for `U5`.  With `WENO5` it was double that.  I guess the moral of the story is that `WENO5` is very different and sometimes much better and sometimes much worst.

I should say that the difference from the first run to the second sometimes differed by a factor of `10`!

**Comment by francispoulin** [comment]
> One issue with that assumption is that the advection terms compile to different code when using a `BackgroundField`. With a `BackgroundField` the velocity field is stored as a `FunctionField` (with almost no additional memory allocation) rather than raw data. Calling `getindex` on a `FunctionField` resolves to calling a function, whereas calling `getindex` on a `Field` / `Array` fetches data from memory. So they are different.

Good to know.  Thanks for explaining.

> Naively I would expect that evaluating a complicated advection term involving `BackgroundField` would be cheaper than one that involved two concrete `Array`. But sometimes unexpected things happen (the compiler might decide to optimize the code differently...)

Agreed!   Often unexpected things happen, which keeps us on our toes.

> We could potentially implement an interface whereby `Field`s can be used as `BackgroundField` rather than functions. That might give us some insight, because then the "additional" advection terms associated with `BackgroundField` would truly be identical to the "original" advection term.

I don't pretend to  understand the details of this and don't know the potential pay off so not sure whether I think this will bear fruit or not.

> I would say that the background self-interaction terms are _neglected_ rather than presumed to be zero. Linear terms associated with the background fields are also neglected. 

Good.

> _Side note:_ some nonlinear terms are additionally neglected in the case of nonlinear viscosity.

Ah, I don't think I'm getting into that now but it's something to be aware of.

**Comment by francispoulin** [comment]
> I believe to support concrete `BackgroundField` we need to add a method to `regularize_background_field` defined here:
> 
> https://github.com/CliMA/Oceananigans.jl/blob/7501c5325a0f7c77a89316d23ee7a56a3877dad9/src/Fields/background_fields.jl#L59-L63
> 
> that looks like
> 
> ```julia
> regularize_background_field(X, Y, Z, field::Field, grid, clock) = field
> ```
> 
> If you want to be super friendly you could also check that `location(field) == (X, Y, Z)` and `grid == field.grid` and throw an error if not so users don't get wrong results.

That sounds pretty easy and would happily help work on this during a pair programming session but don't think I understand it well enough to tackle it myself.  But thanks a lot for explaining the nuances.

**Comment by glwagner** [comment]
@francispoulin still an issue?

**Comment by francispoulin** [comment]
I haven't used this for about a year so I don't know it's a problem.  I will close it for now and come back to it if I see strange behaviour in the current version of the code.
