### ISSUE TITLE
Circulation and vorticity operators need to be updated at the cubed sphere corners

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#1584]
https://github.com/CliMA/Oceananigans.jl/blob/28dadbcc52a2badd242e89ba30c8cc34f9117327/src/Operators/vorticity_operators.jl#L1-L2

At the cubed sphere corners the grid is not actually orthogonal and so the vector-invariant formulation breaks down unless we compute the circulation carefully for each corner.

![image](https://user-images.githubusercontent.com/20099589/114737069-a8183e80-9d14-11eb-9a9c-07b5243af3c2.png)

I've attached the appropriate reference (Adcroft et al., 2004):

[Adcroft et al, 2004, Monthly Weather Review, Implementation of an Atmosphere–Ocean General Circulation Model on the Expanded Spherical Cube.pdf](https://github.com/CliMA/Oceananigans.jl/files/6311899/Adcroft.et.al.2004.Monthly.Weather.Review.Implementation.of.an.Atmosphere.Ocean.General.Circulation.Model.on.the.Expanded.Spherical.Cube.pdf)

Here is the MITgcm implementation: https://github.com/MITgcm/MITgcm/blob/master/pkg/mom_common/mom_calc_relvort3.F

Once this is fixed, the Rossby-Haurwitz test case in PR #1570 with momentum advection should stop blowing up at the corners.

**Comment by glwagner** [comment]
If you have `Connected` I guess you can infer when you need to do something different right?

**Comment by ali-ramadhan** [comment]
Yeah at first glance https://github.com/MITgcm/MITgcm/blob/master/pkg/mom_common/mom_calc_relvort3.F suggests to me that the stencils are different for each corner but maybe once it's coded up we might find a pattern that makes it easy to come up with a more generic solution.

I'll take a stab at this later today. I'll start by trying `if` statements since it'll probably be the quickest to implement.

**Comment by siddharthabishnu** [comment]
In addition to the circulation, the vorticity operator also needs to be computed carefully at the corners of the orthogonal spherical shell grids (OSShGs) constituting the cubed sphere. In Oceananigans, the circulation at the ffc nodes are computed first using a line integral of the velocity along the boundaries of the areas A<sup>ffc</sup>. Vorticity being the microscopic version of circulation (as a measure of rotation), it is then obtained by dividing the circulation by the respective area A<sup>ffc</sup>. Now, referring to the schematic by @ali-ramadhan above, the special treatment of circulation around the corners of the OSShGs has been taken care of, when this issue was closed. However, when we compute the vorticity at these corner points, we need to divide by a smaller area A<sup>ffc</sup><sub>small</sub>. In the example of the above schematic, this smaller area would be 75% of the area A<sup>ffc</sup> in the interior of the grid. After noticing this issue, I had a discussion with @navidcy, and we decided it is better to not mess with the A<sup>ffc</sup> computations at the corners. This is because we want to maintain a consistent formulation of these (grid metric) areas, which change only for the OSShGs, and not necessarily for other multi-region grids. So, instead, I will redefine the vorticity computations at these corner points.

**Comment by navidcy** [comment]
I think it makes sense to only have a special vorticity operator for the corners. The circulation operator could be dropped all together since its only purpose is to compute the vorticity.

**Comment by navidcy** [comment]
@siddharthabishnu it's easier if we point to the code so I'll do that here.

The part that @siddharthabishnu is referring for the vorticity calculation is

https://github.com/CliMA/Oceananigans.jl/blob/8634ef1fcef021221a3486d5e2ede008a057a396/src/Operators/vorticity_operators.jl#L9

The code at the moment computes the vorticity by dividing the circulation by the surface area. But at the corners of the sphere this area is a bit smaller (see the schematic above). The code takes care in computing the circulation aware of the corners, e.g.,

https://github.com/CliMA/Oceananigans.jl/blob/8634ef1fcef021221a3486d5e2ede008a057a396/src/Operators/vorticity_operators.jl#L21

but it does not take care in dividing by the proper area.

**Comment by glwagner** [comment]
Yes @siddharthabishnu ! This is probably that mysterious last bug!

> Affcsmall is 75% of Affc in the interior of the grid

I think the corner area requires bespoke calculation --- it's not quite 3/4 of the area of the corner cell. Right @navidcy ?

**Comment by glwagner** [comment]
As discussed with @navidcy, I think that the corner metrics should be edited when the cubed sphere grid is built. The reason is that the corner area may be relevant to calculations other than vorticity. Or more generally, a corner metric that includes "ghost areas" has no physical meaning and therefore is probably less useful than a corner metric that "knows" it's on the cubed sphere.

If we edit the corner metrics appropriately then I don't think we need to change the operators.

**Comment by glwagner** [comment]
Always link to code and always be explicit 🖖

**Comment by navidcy** [comment]
> Yes @siddharthabishnu ! This is probably that mysterious last bug!
> 
> > Affcsmall is 75% of Affc in the interior of the grid
> 
> I think the corner area requires bespoke calculation --- it's not quite 3/4 of the area of the corner cell. Right @navidcy ?

The area of the corner related to the circulation integral should be *3 times* the area of the spherical quadrilateral defined by points:

```
    a = (φᶠᶠᵃ[1, 1], λᶠᶠᵃ[1, 1])
    b = (φᶜᶠᵃ[1, 1], λᶜᶠᵃ[1, 1])
    c = (φᶜᶜᵃ[1, 1], λᶜᶜᵃ[1, 1])
    d = (φᶠᶜᵃ[1, 1], λᶠᶜᵃ[1, 1])
```
where points `a`, `b`, `c`, `d` are depicted below. 

![Imported File (4)](https://github.com/CliMA/Oceananigans.jl/assets/7112768/b03a4704-af0e-4150-9f77-d308bb120fb0)

At the moment the area that corresponds to `Azᶠᶠᵃ[1, 1]` is 4 times that so probably that's why @siddharthabishnu says "75%".
