### ISSUE TITLE
`with_halo` throws an error for VerticallyStretchedRectilinearGrid

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1605]
`with_halo` throws an error for `VerticallyStretchedRectilinearGrid`:

https://github.com/CliMA/Oceananigans.jl/blob/6ff1f69e2bc5d66a0889fb3c62fb2a3b633ab535/src/Grids/vertically_stretched_rectilinear_grid.jl#L227-L231

despite that the stretched `z_faces` / `zF` kwarg can be inferred from `grid.zᵃᵃᶠ`.

**Comment by francispoulin** [comment]
Is this bad?  Sorry but I'm not sure what the problem is.

On a different note, line 216 (copied below) modifies the faces in case it is periodic.  I thought we wanted a stretched domain to be bounded?  Did we want to remove this or allow for periodic stretched domains?  I could see some utility in this if someone wanted to have a stretched domain in the center for example.

https://github.com/CliMA/Oceananigans.jl/blob/6ff1f69e2bc5d66a0889fb3c62fb2a3b633ab535/src/Grids/vertically_stretched_rectilinear_grid.jl#L216

**Comment by glwagner** [comment]
> Is this bad? Sorry but I'm not sure what the problem is.

It's not a major problem, just misleading since we can indeed write this function and don't need to throw an error.

> I thought we wanted a stretched domain to be bounded?

Only for `IncompressibleModel` with currently available Poisson solvers: `FourierTridiagonalPoissonSolver` can only solve the Poisson equation in domains that are vertically-bounded. But with other solvers (or problems that don't need Poisson solvers), its fine to have a vertically-periodic domain with a vertically-stretched grid, as far as I can tell.

**Comment by francispoulin** [comment]
Thanks for clarifying and good to know.

**Comment by francispoulin** [comment]
Will do!
