### ISSUE TITLE
Splash on a sphere small correction needed

### ISSUE THREAD

**Issue by AlexElmsley** [CliMA/Oceananigans.jl#1646]
I tried to run the example splash on the sphere  https://github.com/CliMA/Oceananigans.jl/blob/master/examples/spherical_splash.jl  under Julia 1.5.2 and in order to make it work I needed to change l 54

splash(λ, φ, z) = a * Gaussian(λ, φ - φ₀, L)

into 

splash(λ, φ) = a * Gaussian(λ, φ - φ₀, L)

Then it worked perfectly.

**Comment by glwagner** [comment]
(I'm happy to fix it myself, but don't want to take away your chance to contribute.)

You can submit a quick PR by clicking the little pencil in the top right:

![image](https://user-images.githubusercontent.com/15271942/117840174-63ef5f80-b228-11eb-9080-95822ed37669.png)


making the change you've suggested, and then following the prompt to open a PR.

Apparently this example is not tested...

**Comment by francispoulin** [comment]
Interesting that this works. in the `ShallowWaterModel` we define our functions to be `(x,y,z)` because that's what I thought we had to do.  But this example above suggests that in the spherical case we can define `(x,y)`.  Does this mean we might be able to define functions in `ShallowWaterModel` that don't depend on `z`, or am I missing something?
