### ISSUE TITLE
Combined ENO and WENO interpolation for "true" high-order advection stencils

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#1705]
Due to the staggered grid our WENO scheme (and other advection schemes) are effectively second order for momentum (though it should be noted that we have observed substancial benefit from using the WENO stencils for advection, in practice). It might behoove us anyways to implement a modified advection scheme following [Arbitrarily high-order (weighted) essentially non-oscillatory finite difference schemes for anelastic flows on staggered meshes](https://arxiv.org/pdf/1905.13665.pdf).

**Comment by glwagner** [comment]
Figure 8 in Mishra et al 2020 is

![image](https://user-images.githubusercontent.com/15271942/124528746-38bb6380-ddc6-11eb-8671-770af063bbfb.png)

I believe "Algorithm 1" is what we currently have, where as "Algorithm 5" is their proposal and the topic of this issue.

The differences between other advection schemes and WENO5 is dramatic compared with the naive and "improved" WENO scheme. So I'm not sure it's worth resolving this issue. It'd be good if someone else could read the preprint closely to confirm what I'm seeing.

**Comment by francispoulin** [comment]
I looked over the paper and I agree with what you say.  They prove that "Algorithm 1" is only formally second order accurate whereas "Algorithm 2" is more accurate, fifth I think?  That is a good reason to consider the change.

One concern that I have is, as nice as these figures are, I can't really tell much of a difference between column 1 and column 2.  Actually, they look pretty identical to me.  I can believe that the new method can behave better with the improved accuracy but this example, and the others they consider, don't make this obvous.  If they had plotted diagnostics and demonstrated that the new method conserved things better, that would have been more motivation to switch.  At the moment, it doesn't seen too pressing, but in principle I'm all for it.

Because I am interested in understanding the nuts and bolts of WENO, I will look deeper into this paper and try and figure out exactly what needs to change to upgrade to "Algorithm 5".

**Comment by tomchor** [comment]
> One concern that I have is, as nice as these figures are, I can't really tell much of a difference between column 1 and column 2. Actually, they look pretty identical to me.

Yeah, same here. But I guess the more important question is: how are the statistics affected? Does this loss of accuracy impact second order statistics significantly? That could happen with the solutions looking pretty identical to the naked eye. If that's the case then I'd say the case for solving this issue is pretty strong.

> Because I am interested in understanding the nuts and bolts of WENO, I will look deeper into this paper and try and figure out exactly what needs to change to upgrade to "Algorithm 5".

Awesome! :)

**Comment by glwagner** [comment]
Could be worth contacting the authors of that draft to figure out whether they tested statistics or not. I'm also not sure if the paper has been published. More info definitely welcome.
