### ISSUE TITLE
Should we do something about exponentiation with `Int64`?

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1832]
If you search for `grep -r "\^2" *` from Oceananigans' root dir, for example, you get many places where we exponentiate with an Int64.

Per the discussion in https://github.com/CliMA/Oceananigans.jl/pull/1770 it seems that this causes a pretty big performance drawback in Julia 1.6 on GPUs. What should be our approach here? Do we wait for this to be resolved upstream or do we change all exponentiation in critical places to use `Int32`?

CC: @maleadt @glwagner

**Comment by glwagner** [comment]
I think exponentiating with `Int32` is the right thing to do here.

I'm not sure what "resolution" would look like upstream. One possibility is that nvidia adds a function for exponentiating with `Int64`... ?

Another possibility is that we figure out how to translate `x^2` to `x*x` (eg hook into `Base.literal_pow`). But we could also do this manually without much trouble. But https://github.com/CliMA/Oceananigans.jl/pull/1783 suggests that this might be slower than `^Int32(2)`.

**Comment by glwagner** [comment]
I think we should talk about using `Base.literal_pow` for small integer exponentiation in a CUDA.jl issue also --- not here. I'm planning to open an issue but haven't gotten around to it yet.

**Comment by maleadt** [comment]
> Another possibility is that we figure out how to translate `x^2` to `x*x` (eg hook into `Base.literal_pow`).

Exponentiation by literals is covered by that, just not when using constants as in #1770 

```julia
julia> f(x) = x^2
f (generic function with 1 method)

julia> code_warntype(f, Tuple{Float64})
Variables
  #self#::Core.Const(f)
  x::Float64

Body::Float64
1 ─ %1 = Core.apply_type(Base.Val, 2)::Core.Const(Val{2})
│   %2 = (%1)()::Core.Const(Val{2}())
│   %3 = Base.literal_pow(Main.:^, x, %2)::Float64
└──      return %3
```
```julia
julia> const factor = 2
2

julia> g(x) = x^factor
f (generic function with 1 method)

julia> code_warntype(g, Tuple{Float64})
Variables
  #self#::Core.Const(g)
  x::Float64

Body::Float64
1 ─ %1 = (x ^ Main.factor)::Float64
└──      return %1
```

HOWEVER, on the CPU both result in good code:

```julia
julia> code_llvm(f, Tuple{Float64})
;  @ REPL[12]:1 within `f'
define double @julia_f_1923(double %0) {
top:
; ┌ @ intfuncs.jl:312 within `literal_pow'
; │┌ @ float.jl:332 within `*'
    %1 = fmul double %0, %0
; └└
  ret double %1
}

julia> code_llvm(g, Tuple{Float64})
;  @ REPL[6]:1 within `g'
define double @julia_g_342(double %0) {
top:
; ┌ @ math.jl:918 within `^'
; │┌ @ float.jl:332 within `*'
    %1 = fmul double %0, %0
; └└
  ret double %1
}
```

Whereas with CUDA, the non-literal version leads to expensive code:

```
julia> CUDA.code_llvm(f, Tuple{Float64})
;  @ REPL[12]:1 within `f'
define double @julia_f_1908(double %0) {
top:
; ┌ @ intfuncs.jl:312 within `literal_pow'
; │┌ @ float.jl:332 within `*'
    %1 = fmul double %0, %0
; └└
  ret double %1
}

julia> CUDA.code_llvm(g, Tuple{Float64})
;  @ REPL[6]:1 within `g'
define double @julia_g_1282(double %0) {
top:
; ┌ @ /home/tim/.julia/packages/CUDA/Ozu5O/src/device/intrinsics/math.jl:223 within `^' @ /home/tim/.julia/packages/CUDA/Ozu5O/src/device/intrinsics/math.jl:218
   %1 = call i32 @llvm.nvvm.d2i.hi(double %0) #4
   %2 = call i32 @llvm.nvvm.d2i.hi(double 2.000000e+00) #4
...
  ret double %t.7.i
}
```

I'm guessing this is due to const-prop and the definition of `^` in Base:

```
@inline function ^(x::Float64, y::Integer)
    y == -1 && return inv(x)
    y == 0 && return one(x)
    y == 1 && return x
    y == 2 && return x*x
    y == 3 && return x*x*x
    ccall("llvm.pow.f64", llvmcall, Float64, (Float64, Float64), x, Float64(y))
end
```

Would that cover Oceananigans cases?

**Comment by tomchor** [comment]
> Would that cover Oceananigans cases?

I'll let @glwagner answer this part since he knows much more about this than I do. But do you also suggest that we change the exponentiation in Oceananigans based on this issue? If so I'll start a PR and run some benchmarks.

**Comment by glwagner** [comment]
@maleadt thank you _very_ much for the clarification.

Note: @maleadt's demonstration suggests that the only reason #1770 helped was because

https://github.com/CliMA/Oceananigans.jl/blob/4e9e5b79407e287005aa28d03d2fe3ffd37da194/src/Advection/weno_fifth_order.jl#L95

and that the _other_ change (converting the literal `^2` to `^Int32(2)`) was irrelevant (like all good PRs #1770 contained two independent changes). In other words there's no reason to change `^2` to anything else. The thing to look out for is `x^c` where `const c = 2` (or something like it).

I'm still puzzled why #1783 (just manually inserting `x*x` for`x^2`) didn't speed things up, but there might be a mistake there.

@maleadt I was confused because I assumed that [`CUDA.@device_override`](https://github.com/JuliaGPU/CUDA.jl/blob/800b7b89c4c19b9b98a7d150a813a0e3d0e18be5/src/device/utils.jl#L13) didn't respect lowering of `x^2` to `Base.literal_pow(^, x, Val(2))`. If I'm understanding `CUDA.code_llvm` correctly then I was wrong.

By the way I get something different from the above code on CUDA 3.3.2:

```julia
julia> const factor = 2
2

julia> g(x) = x^factor
g (generic function with 1 method)

julia> CUDA.code_llvm(g, Tuple{Float64})
;  @ REPL[4]:1 within `g'
define double @julia_g_1624(double %0) {
top:
; ┌ @ /home/glwagner/.julia/packages/CUDA/fRSUT/src/device/intrinsics/math.jl:223 within `^' @ /home/glwagner/.julia/packages/CUDA/fRSUT/src/device/intrinsics/math.jl:218
   %1 = call i32 @llvm.nvvm.d2i.hi(double %0) #4
   %2 = call i32 @llvm.nvvm.d2i.hi(double 2.000000e+00) #4
   %3 = and i32 %2, 2146435072
   %4 = icmp eq i32 %3, 1062207488
   %5 = call double @llvm.fabs.f64(double %0) #4
   %6 = call fastcc double @__internal_accurate_pow(double %5, double 2.000000e+00) #4
   %7 = icmp slt i32 %1, 0
   %or.cond.i = and i1 %7, %4
   br i1 %or.cond.i, label %8, label %13
```

But wait, there's more...

```julia
julia> const factor32 = Int32(2)
2

julia> h(x) = x^factor32
h (generic function with 1 method)

julia> CUDA.code_llvm(h, Tuple{Float64})
;  @ REPL[9]:1 within `h'
define double @julia_h_2275(double %0) {
top:
; ┌ @ /home/glwagner/.julia/packages/CUDA/fRSUT/src/device/intrinsics/math.jl:221 within `^'
   %1 = fmul double %0, %0
; └
  ret double %1
```

Hm?

**Comment by glwagner** [comment]
> Would that cover Oceananigans cases?

As noted I think all Oceananigans cases are `^2` (squaring with a literal) rather than squaring with a constant. Despite that I think it makes sense to copy / use something similar to Base's `^` in CUDA with `Int64`.

**Comment by tomchor** [comment]
Okay, if I understand correctly, no further action is needed on the Oceananigans side. Should I close this issue?

**Comment by glwagner** [comment]
@tomchor there might be some work to do here re: AbstractOperations.

**Comment by tomchor** [comment]
> @tomchor there might be some work to do here re: AbstractOperations.

I don't really see where though. Do you mind clarifying?

**Comment by glwagner** [comment]
`^` is one of the operations we define on `AbstractField`:

https://github.com/CliMA/Oceananigans.jl/blob/927630699aac7d071b87cc87350fce6f69dbbd07/src/AbstractOperations/AbstractOperations.jl#L71

I think users will hit `Float64` exponentiation if they use this (unless they convert to `Int32`) since it the operation doesn't get compiled until after the exponent is stored:

```julia
julia> using Oceananigans
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]
[ Info: Oceananigans will use 8 threads

julia> grid = RegularRectilinearGrid(size=(1, 1, 1), extent=(1, 1, 1)); c = CenterField(CPU(), grid)
Field located at (Center, Center, Center)
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1, 1, 1)
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=1)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)

julia> op = c^2
BinaryOperation at (Center, Center, Center)
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=1)
│   └── domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
└── tree:
    ^ at (Center, Center, Center)
    ├── Field located at (Center, Center, Center)
    └── 2

julia> op.b
2
```

Further work needed to dig into this though.

**Comment by tomchor** [comment]
> `^` is one of the operations we define on `AbstractField`:

Oh yeah, I meant more in the sense of: where in the code should I make that change. Tbh I understand very little of how abstract operations are implemented, so it's not obvious to me how to make that change. But as you said, "further work needed to dig into it". :)

**Comment by glwagner** [comment]
Here's a few options for optimizing AbstractOperations with `^`:

1. Auto-convert exponents to `Int32`

For this we'd define

```julia
Base.^(L, a::AbstractField, b::Int64) = ^(L::Tuple, a, Int32(b))
```

Basically implementing the approach CUDA previously took. For us it's a "less egregious" hack since, unlike CUDA.jl, we can "almost surely" guarantee that users won't exponentiate with integers larger than `2^31-1 = 2147483647`. Probably the easiest thing to do in the near term.

2. Convert small-power exponents to literal multiplications

Like `Base.literal_pow`:

```julia
Base.^(L::Tuple, a::AbstractField, b::Integer) = our_literal_pow(L, a, Val(b))

our_literal_pow(L, a, Val{0}) = one(eltype(a))
our_literal_pow(L, a, Val{1}) = a
our_literal_pow(L, a, Val{2}) = *(L, a, a) # binary operation
our_literal_pow(L, a, Val{3}) = *(L, a, a, a) # multiary operation
our_literal_pow(L, a, Val(b)) where b = # directly construct BinaryOperation with `^`?
```

etc. I guess 2 would instead happen under the hood when abstract operations are compiled, hopefully, in the best of worlds.

**Comment by glwagner** [comment]
Let's wait and see the impact of https://github.com/JuliaGPU/CUDA.jl/pull/1033 before doing anything.

**Comment by glwagner** [comment]
JuliaGPU/CUDA.jl#1033 was merged which probably resolves this. Resurrect if not...
