### ISSUE TITLE
Should we rename the model option `coriolis` to `background_rotation`?

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1905]
Related to https://github.com/CliMA/Oceananigans.jl/issues/1904, but I didn't wanna distract from the main discussion there.

It might make sense to rename the model constructor option `coriolis` to `background_rotation`, since that's really what it is. If we're running a rotating GFD simulation then `coriolis` is an appropriate term. But one could envision using Oceananigans for more idealized simulations with a rotating domain where calling the rotation `coriolis` wouldn't really make much sense.

Thoughts?

CC: @glwagner @francispoulin

**Comment by glwagner** [comment]
One thought I had during that discussion is that "background rotation" is a physical concept, while "Coriolis" is more or less the name of the terms we add to a momentum equation to describe that physical concept.

Most of the keyword arguments for models refer to the math (rather than the physics), which might be preferred because in a sense its more precise. In other words, Oceananigans solves a discretization of a partial differential equations; it's up to users to interpret the solution in light of some physical problem that's being modeled.

**Comment by francispoulin** [comment]
Since Coriolis is very much a common term in the field and it describes the terms in the equation, I would vote for keeping it, even though I agree that background_rotation is more descriptive.

**Comment by navidcy** [comment]
Coriolis is widely used... Let's keep it, please!
