### ISSUE TITLE
Choice of constant for the Smagorinsky model

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1907]
I have a feeling that I've asked this before but I looked and couldn't find anything. So forgive me if this is double-posting.

Usually the Smagorisnky eddy viscosity is defined as:

![Screenshot from 2021-07-28 19-06-04](https://user-images.githubusercontent.com/13205162/127420375-fa1781b0-f274-43d7-80f2-b747bb562d44.png)

and with `C_s=0.165`. 

Looking at the code I can see that the formulation is a bit different: https://github.com/CliMA/Oceananigans.jl/blob/32c5c5a2d0f441a4b663866d511807d0f9413c90/src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl#L94

Unless I'm missing something, this means that the coefficient `C` of the closure is different from the coefficient `C_s` as it is usually defined (and also as it is defined in [the docs](https://clima.github.io/OceananigansDocumentation/stable/numerical_implementation/large_eddy_simulation/#Smagorinsky-Lilly-model)). I'm curious as to why this choice was made.

Also, assuming `ς=1`, the default value of `C=0.23` doesn't seem to match the default value in the literature for `C_s=0.165`.

Am I missing something here? Could someone please clarify?

**Comment by glwagner** [comment]
I'm not sure what part of the formula you're pointing out is specifically different from the image you've pasted, but it does look like something is fishy. Here's what I found:

From [Pressel et al. 2015](https://agupubs.onlinelibrary.wiley.com/doi/pdfdirect/10.1002/2015MS000496) --- which we should cite in our code since I believe it was used as a reference ---

![image](https://user-images.githubusercontent.com/15271942/127506519-abf62a01-f28e-44b1-a45f-c58619fd27f4.png)

The formula in Oceananigans is

https://github.com/CliMA/Oceananigans.jl/blob/32c5c5a2d0f441a4b663866d511807d0f9413c90/src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl#L94

which is called here:

https://github.com/CliMA/Oceananigans.jl/blob/32c5c5a2d0f441a4b663866d511807d0f9413c90/src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl#L102

with `Δᶠ` from here:

https://github.com/CliMA/Oceananigans.jl/blob/924843759db187dafed9e0d899f4af6543033190/src/TurbulenceClosures/turbulence_closure_utils.jl#L23

and, apparently, `Σ² = S_ij S_ij` (if we believe we understand the notation here):

https://github.com/CliMA/Oceananigans.jl/blob/32c5c5a2d0f441a4b663866d511807d0f9413c90/src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl#L97

This means that our formula is identical to Pressel et al (2015), but the constant is wrong (0.23 instead of 0.17).

Amusingly, 

```julia
julia> 0.165 * sqrt(2)
0.23334523779156072
```

which is probably not a coincidence. However, I'm not sure how an extra factor of `sqrt(2)` snuck into our constant.

As for _clarification_, I don't have much to offer. Perhaps the constant was taken from some reference that used a different formulation than either us or Pressel et al. 2015.

As a historical note, the paper cited by both Pressel et al (2015) and us is Lilly (1962), which does indeed use the same formulation:

![image](https://user-images.githubusercontent.com/15271942/127507507-c7d11dfc-733a-4472-8216-dca4e5844b3f.png)

where

![image](https://user-images.githubusercontent.com/15271942/127507737-94aa05d4-6fa5-4d38-9a9d-b1bbcc8a1e79.png)

@tomchor I can't tell if the formula you've pasted is actually different from ours (or what the definition of `|S|` is). Where does it come from?

It'd be fine to change the constant because there's no validation test. So the best we can do is theorize, and theorization on this issue suggests changing the default to `C=0.17`. If one wanted to set up a validation test, it could be nice to reproduce [Compte-Bellot and Corrsin (1964)](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/abs/simple-eulerian-time-correlation-of-fulland-narrowband-velocity-signals-in-gridgenerated-isotropic-turbulence/A3D7B0DD621DE46CB6CC543F65A66F93) (this wasn't possible when the closures were written because we didn't support triply periodic domains, but is possible now). This could also be used to validate Anisotropic Minimum Dissipation. Here's a figure with such a comparison from [Rozema et al 2015](https://aip.scitation.org/doi/pdf/10.1063/1.4928700):

![image](https://user-images.githubusercontent.com/15271942/127508527-e5f7d150-56c4-4949-ad8e-90d67fdbee64.png)

I believe for shear flows it has also been found that the constant needs to be as small as `C=0.1` or smaller? It'd be nice to mention and cite these in the docstring as well, if we can find those references.

**Comment by tomchor** [comment]
> @tomchor I can't tell if the formula you've pasted is actually different from ours (or what the definition of |S| is). Where does it come from?

That was my bad, forgot to cite the source. It comes from [Chamecki et al. 2019](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2019RG000655). But you're right that the definition is identical. I misinterpreted the code.

> It'd be fine to change the constant because there's no validation test

I indeed think we should change constant default to match the most common value used in the literature. I'd also like to change the notation used in the code from `ς` to `\Upsilon`, so as to match [the docs](https://clima.github.io/OceananigansDocumentation/stable/physics/turbulence_closures/) (just to make the code easier for contributors).

I'll open a PR.

**Comment by glwagner** [comment]
Sounds good to update the code! Perhaps we should also add a warning or note of some kind about the lack of validation (we've taken to doing this recently and I think it's a good thing).

@navidcy would be happy not to use `ς`!

`\Upsilon` is disturbingly similar to "Y":

```julia
julia> Υ = 1
1
```

maybe there's a better choice? We could also change the docs.

**Comment by tomchor** [comment]
> Sounds good to update the code! Perhaps we should also add a warning or note of some kind about the lack of validation (we've taken to doing this recently and I think it's a good thing).
> 
> @navidcy would be happy not to use `ς`!
> 
> `\Upsilon` is disturbingly similar to "Y":
> 
> ```julia
> julia> Υ = 1
> 1
> ```
> 
> maybe there's a better choice? We could also change the docs.

Yeah, and I ended up realizing the same thing. I changed the docs instead.
