### ISSUE TITLE
Changing notation from "resolution" to "grid size" in grids show methods

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#1927]
Currently this is the output of a regular grid:

```julia
┌ Info: 
│   grid =
│    RegularRectilinearGrid{Float64, Flat, Bounded, Bounded}
│                       domain: x ∈ [0.0, 0.0], y ∈ [0.0, 1.0], z ∈ [0.0, 1.0]
│                     topology: (Flat, Bounded, Bounded)
│      resolution (Nx, Ny, Nz): (1, 2048, 2048)
│       halo size (Hx, Hy, Hz): (0, 1, 1)
└    grid spacing (Δx, Δy, Δz): (0.0, 0.00048828125, 0.00048828125)
```

One thing that I've noticed recently is that the following line seems odd:

```julia
resolution (Nx, Ny, Nz): (1, 2048, 2048)
```

It calls `Nx` etc "resolution", when really it's the grid size, no? This isn't a huge issue but if all agree I'd like to change that to `grid size` in the grids show methods.

**Comment by glwagner** [comment]
Why not just `size`?

**Comment by glwagner** [comment]
I think "resolution" is ordinary usage, in the sense of

https://en.wikipedia.org/wiki/Image_resolution#Pixel_count

I do agree though that the term "resolution" has several definitions, which is a reason to consider changing to more precise terminology. The keyword argument to grid constructors is `size`, so that's a good choice.

I think the distinction between "grid size" and "halo size" is ambiguous (isn't the halo part of the grid?) But perhaps we can reinforce these notions with more distinct terminology (eg using just "size" and just "halo" rather than "halo size").

All of the grid constructors should be updated with this change.

**Comment by tomchor** [comment]
> I think "resolution" is ordinary usage, in the sense of
> https://en.wikipedia.org/wiki/Image_resolution#Pixel_count

I think this is only used to mean number of points in the context of images.

I had originally suggested `grid size` to differentiate from `halo size`, but I'm okay with just `size` if we also do just `halo`. This has the advantage to match the arguments we pass to the constructor.

Really it would be good to come up with more precise words for the "numerical" domain size (as in number of points), "physical" domain size (now called `extent`), and the size of the halo. But I'm not sure if that's possible without being super verbose.

**Comment by glwagner** [comment]
> I think this is only used to mean number of points in the context of images.

It is also used to mean the number of points or DOF in a numerical simulation.

**Comment by glwagner** [comment]
> Really it would be good to come up with more precise words for the "numerical" domain size (as in number of points), "physical" domain size (now called extent), and the size of the halo. But I'm not sure if that's possible without being super verbose.

"extent" was introduced to have precise terminology that distinguishes between a "number" and a physical length. We did not use "length" because this is used in julia to refer to the number of elements in an array.
