### ISSUE TITLE
Checkpointer that checkpoints the model to a NetCDF files

### ISSUE THREAD

**Issue by Sumanshekhar17** [CliMA/Oceananigans.jl#1929]
Greetings everyone,
I was recently started writing my outputs into a NetCDF file. Now I realize that I have to use checkpointer that can checkpoint the model to a NetCDF files, But I haven't found any method. There is for JLD2 files. So can you please look into this?

**Comment by tomchor** [comment]
I don't use JLD2 files at all so it would be good if someone else chimed in here. That said, JLD2 is a native Julia format and apparently it lets you save much more stuff to the disk much easier than a NetCDF file, which is probably why the checkpointing feature uses JLD2 and not NetCDF. So I don't think we even want a NetCDF-based. 

That said, JLD2 is [HDF5-comptible](https://github.com/JuliaIO/JLD2.jl) so if you want to open the checkpoint files for whatever reason you can use any HDF5 library in any software you want.

Like you, I don't use JLD2. So when I run a simulation that will take too long I set-up my checkpointer (which is for picking up a simulation only) and a `NetCDFOutputWriter` to open the results somewhere else.

Cheers

**Comment by Sumanshekhar17** [comment]
Thank you so much @tomchor for replying. I am sorry, this is very new to me. If it is possible can you show me the procedure by some example. I really need this.

**Comment by tomchor** [comment]
No problem! The docs have a few examples help. You can see the NetCDF examples [here](https://clima.github.io/OceananigansDocumentation/v0.60.0/model_setup/output_writers/#Examples). And you can see the options for the checkpointer [here](https://clima.github.io/OceananigansDocumentation/v0.60.0/appendix/library/#Oceananigans.OutputWriters.Checkpointer-Tuple{Any}).

A pseudo-code that illustrates how you could do it is:

```julia
using Oceananigans
# create grid
# create model
# create simulation

outputs = (u=model.velocities.u, v=model.velocities.v) # for example

# Add the netcdf output
simulation.output_writers[:netcdf] = NetCDFOutputWriter(model, outputs,
                                                        filepath="netcdf_output.nc", schedule=TimeInterval(60))

# Add the checkpointer
simulation.output_writers[:checkpoint] = Checkpointer(model;
                                         schedule = TimeInterval(18hours),
                                         )

run!(simulation, pickup=true) # run with pickup=true and if a checkpointer is found, the simulation will pick up from there
```

Right now we're facing a couple of [issues with our docs](https://github.com/CliMA/Oceananigans.jl/issues/1909) so the docs for the latest versions aren't being generated. So basically you should disregard the function `restore_from_checkpoint`. It doesn't exist anymore in the most current version of Oceananigans.

**Comment by glwagner** [comment]
I think @tomchor is hitting on the right solution: we should separate "output for analysis" from "output for checkpointing", if possible. Typically we need output for analysis more frequently than output for checkpointing, and we don't require things like the tendency fields for analysis. This motivates creating multiple output writers that are dedicated to their specific tasks. 

On the possibility of a NetCDF checkpointer: the first checkpointer design that utilized `restore_from_checkpoint` attempted to serialize as much of a model's data structures as possible. This requirement prevented us from using NetCDF and motivated using JLD2 (there are a few other data formats that can serialize, but JLD2 is fast, simple, and HDF5 compatible, which means it can be loaded from python with `h5py`).

However, we now support a simpler paradigm whereby the original run script needs to be modified with `run!(simulation, pickup=true)` in order to "pick up" a simulation from a checkpoint. With this simpler design we require only all the prognostic fields and tendencies (for AB2) in the checkpointer file and we could in principle support NetCDF. This has the downside that it would require us to maintain more code.

If you do need to inspect, plot, or analyze data in JLD2 files, check out the [JLD2 documentation](https://juliaio.github.io/JLD2.jl/dev/).

**Comment by Sumanshekhar17** [comment]
Thank you @tomchor and @glwagner for advice and solution. I got my answer and I am closing this issue.
