### ISSUE TITLE
About Stratified Couette Flow validation case

### ISSUE THREAD

**Issue by ilyascfd** [CliMA/Oceananigans.jl#1981]
Dear Oceananigans team,

I am new to Julia and Oceananigans.
I installed Julia version 1.6.2 (2021-07-14) on Ubuntu 20.04 LTS, then Oceananigans v0.62.1 as instructed.

I am interested in "stratified plane Couette flow" .
When I run the case using "julia run_stratified_couette_flow_simulations.jl",  I am having following error;

**"
ERROR: LoadError: UndefVarError: Value not defined
Stacktrace:
 [1] simulate_stratified_couette_flow(; Nxy::Int64, Nz::Int64, arch::GPU, h::Int64, U_wall::Int64, Re::Int64, Pr::Float64, Ri::Int64, Ni::Int64, end_time::Int64)
   @ Main ~/Desktop/stratified_couette_flow/stratified_couette_flow.jl:103
 [2] top-level scope
   @ ~/Desktop/stratified_couette_flow/run_stratified_couette_flow_simulations.jl:3
in expression starting at /home/ilyas/Desktop/stratified_couette_flow/run_stratified_couette_flow_simulations.jl:3
"****

It complaints about undefined Boundary Condition Value (stratified_couette_flow.jl:103).
Can you help me to fix it?

Please forgive me if I missed something obvious or made a trivial mistake.
Thanks,

Ilyas

**Comment by glwagner** [comment]
@ilyascfd welcome and thanks for opening this issue, it's very helpful!

The problem here is that `Value` is not exported by default when we write `using Oceananigans` anymore. As a result, these lines:

https://github.com/CliMA/Oceananigans.jl/blob/ff19b7e0d328557dc198eb23349db5eed0680c65/validation/stratified_couette_flow/stratified_couette_flow.jl#L103-L110

do not work. 

The recommended syntax nowadays is, for example,

```
bc = ValueBoundaryCondition(0)
```

rather than `BoundaryCondition(Value, 0)`. This change was made to avoid name conflicts with some common names in the Julia ecosystem (like `Flux`). But, it looks like the validation script was not updated when this change was made to our exported names.

I opened a PR to fix it in #1982. You can fix the script yourself as well by replacing `BoundaryCondition(Value, ` with `ValueBoundaryCondition(`.

PS @ilyascfd here are a few tips for writing issues that will help us solve your problem as fast as possible
* Include links to the lines that are failing so we don't have to look for them ourselves. Github is really handy for this!
* When including code in an issue, please format it with triple backticks (```)

Note: we run this script during CI, so at first I was surprised that we hadn't caught this yet. But when we run the tests, we do indeed import `Oceananigans.BoundaryConditions.Value` via

https://github.com/CliMA/Oceananigans.jl/blob/ff19b7e0d328557dc198eb23349db5eed0680c65/test/runtests.jl#L20

and

https://github.com/CliMA/Oceananigans.jl/blob/ff19b7e0d328557dc198eb23349db5eed0680c65/src/BoundaryConditions/BoundaryConditions.jl#L3-L4

**Comment by ilyascfd** [comment]
@glwagner Thanks for warm welcome and response.
It works now.

Ilyas
