### ISSUE TITLE
Switching off non - required equations

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2046]
Is there a way to switch off the momentum equations which are not required?

For example in case of a 3D diffusion equation or in case of advection by a constant (background) velocity you don't want to be solving the momentum equations....

If yes, cool, if not we should implement it

**Comment by glwagner** [comment]
Yes! The `HydrostaticFreeSurfaceModel` constructor permits the kwarg `velocities = PrescribedVelocities()`. This can be used to prescribe velocity fields rather than solving for them directly. when `velocities isa PrescribedVelocities`, then neither prognostic fields nor tendencies are allocated the velocity fields or free surface. With the addition kwarg `tracer_advection=nothing`, then advection can be omitted, permitting the solution of a diffusion equation.

This feature is not documented; it can only be found in a few `validation` cases such as

https://github.com/CliMA/Oceananigans.jl/blob/main/validation/curvilinear_diffusion/spot_tracer_diffusion.jl

**Comment by glwagner** [comment]
The syntax is

https://github.com/CliMA/Oceananigans.jl/blob/057e25cea75a0da5e2e0f2328d39205ebaf2b0dc/validation/curvilinear_diffusion/spot_tracer_diffusion.jl#L24-L29

The infrastructure that supports this is in 

https://github.com/CliMA/Oceananigans.jl/blob/main/src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl

**Comment by glwagner** [comment]
For a more complicated case on the cubed sphere, see https://github.com/CliMA/Oceananigans.jl/blob/main/validation/cubed_sphere_tracer_advection/cubed_sphere_tracer_advection.jl

**Comment by simone-silvestri** [comment]
Cool, nice!

**Comment by glwagner** [comment]
Yes, there's no free surface because

https://github.com/CliMA/Oceananigans.jl/blob/24e766481cebbc8f61099b386623d175218acedb/src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl#L72
