### ISSUE TITLE
Option for `NaNChecker` to exit with error

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2086]
Before the recent overhaul to callbacks, `NaNChecker` exited with an error. While I agree that exiting without an error is convenient at times, it would be good to have the built-in option to keep the original behavior.

For example, consider a code that runs a simulation and then writes a checkpointer after it's done running. The legacy behavior was that if the simulation blew up, `run!` threw an error and the rest of the script (including the checkpointing) wouldn't happen. That would allow the user to restart the simulation from the latest checkpointer (possibly with a lower cfl threshold). Now if the simulation blows up, a checkpointer (full of NaNs) is still written, possibly overwriting the previous checkpointer.

I know we can cook up a callback that manually throws an error, but this seems like a common enough case that there should be a built-in option for it. (Or maybe it's just me?)

**Comment by glwagner** [comment]
Perhaps the feature being asked for here is a checkpointer that avoids writing NaNs --- is that correct?

**Comment by glwagner** [comment]
We could certainly add a field `error` to `NaNChecker` and throw an error if `error=true`, too.

Another possibility though is to design a new `schedule` that doesn't actuate if NaNs are detected. This could be used generically for output writing and checkpointing. Maybe a wrapper like

```julia
schedule = WithoutNaNs(TimeInterval(100))
```

Then when the scheduled is queried, `WithoutNaNs` returns `false` if `fields(sim.model)` has NaNs; otherwise the "child schedule" (`TimeInterval(100)` in this case) is queried.

**Comment by glwagner** [comment]
On the skip condition `hasnan`: we currently have

https://github.com/CliMA/Oceananigans.jl/blob/be424494c720e2f5152c485178a963c96b110a0f/src/Simulations/nan_checker.jl#L14

but for the above pattern we'd need something like

```julia
hasnan(sim::Simulation) = hasnan(first(fields(sim.model)))
```

With generic "skip conditions" users can also write things like

```julia
schedule = Skip(sim -> hasnan(sim.model.pressures.pNHS), TimeInterval(100))
```

(or something)

**Comment by glwagner** [comment]
Another possibility is to create an abstraction for combining schedulers. I've thought this would be a neat pattern for a while. Then we could have something like

```julia
schedule = Both(model -> !hasnan(model.velocities.u), TimeInterval(100))
```

Then the schedule is actuated if both conditions are met.

This is also nice for transition to turbulence studies, where we may want something like

```julia
schedule = Both(model -> maximum(abs, model.velocities.w) < 1e-2, TimeInterval(100))
```

This schedule doesn't acutate until the maximum vertical velcoity is greater than 1e-2. After that, it actuates on an interval of 100 seconds.

**Comment by tomchor** [comment]
> Perhaps the feature being asked for here is a checkpointer that avoids writing NaNs --- is that correct?

I actually think having an `error=true` option to `NaNChecker` would be useful for other purposes than avoiding a nan-filled checkpoint, so I personally still think that's the best solution here, since it's also pretty simple. If the script has plots or other analyses after `run!()`, a user might not want to waste resources running all that stuff if a `NaN` is detected. (Or they might! And hence the option :) )

Unless there's a reason why that's a bad idea that I'm missing...

**Comment by glwagner** [comment]
> I actually think having an error=true option to NaNChecker would be useful for other purposes than avoiding a nan-filled checkpoint

Okay.

> I personally still think that's the best solution here

I disagree, because it only solves the problem for a narrow range of checkpointer schedules. If you checkpoint based on `TimeInterval` and check for NaNs based on `IterationInterval`, there is no guarantee that you won't write NaNs to a checkpoint file whether or not the NaNChecker throws an error.

> Unless there's a reason why that's a bad idea that I'm missing...

I don't think there is an intrinsic problem with throwing an error.
