### ISSUE TITLE
Index for Reduced fields

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2177]
Where is a reduced field located in the `Nothing` direction?

It is natural to locate the free surface at the surface,  (`k = grid.Nz`), but for other fields which are Averages or sums the choice is not that natural

This is important in the context of Immersed boundaries to check if a Reduced Field is immersed or not (and eventally mask it). For the free surface it is enough to check `solid_interface(i, j, grid.Nz, grid)`, for averaged fields it might be necessary to check the whole column `all(solid_interface(i, j, 1:grid.Nz, grid))`

**Comment by glwagner** [comment]
Yes, this is interesting!

To clarify: we identify a field as "reduced" if one of its locations is `Nothing`, rather than `Face` or `Center`.

I think the issue here is that there are a few flavors of "reduced fields":

* "Sliced fields", which have reduced dimensionality, but still have a "position" in 3D space. These may be fields that exist only on boundaries, like the free surface, ice concentration, boundary conditions, etc. It should also be valid to define field "slices" at other positions / indices, inside the domain. We might say these fields are "2.5 dimensional"... ?
* _Truly_ two-dimensional fields derived from a reduction operation, like `Average` or `Integral`. These fields have no position in the reduced dimension.

I need to think about the masking issue. For 2.5D fields, the answer is clear: we need to evaluate `solid_interface` at the actual "location" of the field. Right now `Nothing` in the vertical means `k -> 1`. But this is _wrong_, as this issue identifies.

For truly 2D fields, it's murkier. I think in _general_ if one wants to identify whether an _entire_ dimension is masked, there's little choice but to evaluate the masking function at every index in that dimension. But there are special cases for which the job is a bit easier. For example, `GridFittedBottom` assumes that masking occurs at every location _below_ a specified depth. Thus, a column can be identified as masked by evaluating `solid_interface` at the upper grid point, eg `k = grid.Nz`.

So, we have a design problem on our hands to figure out how to represent these ideas in the code. We might need more types ;-)

**Comment by glwagner** [comment]
Another solution is to add a property to `Field` (rather than overloading the location `LX`, `LY`, `LZ`). This new property could be called `indices` and might work similar to `SubArray.indices`:

```julia
julia> a = rand(3, 3, 3)
3×3×3 Array{Float64, 3}:
[:, :, 1] =
 0.482184  0.754916  0.775214
 0.305473  0.813324  0.662735
 0.877661  0.28685   0.564257

[:, :, 2] =
 0.799881  0.575096  0.631413
 0.357241  0.479499  0.0708911
 0.922986  0.979659  0.117883

[:, :, 3] =
 0.868073  0.0576275  0.328323
 0.522754  0.663369   0.840316
 0.40434   0.631349   0.577748

julia> b = view(a, :, 2:3, 2)
3×2 view(::Array{Float64, 3}, :, 2:3, 2) with eltype Float64:
 0.575096  0.631413
 0.479499  0.0708911
 0.979659  0.117883

julia> typeof(b)
SubArray{Float64, 2, Array{Float64, 3}, Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Int64}, true}

julia> b.indices
(Base.Slice(Base.OneTo(3)), 2:3, 2)
```

One key difference with `SubArray` is that we want to offset indices. For example with `SubArray` we have

```julia
julia> b[1, 1, 1]
0.5750957798298579

julia> a[1, 2, 2]
0.5750957798298579
```

But I think we instead want offset indices that behave something like

```julia
julia> c = OffsetArray(view(a, :, 2:3, 2:2), 0, 1, 1)
3×2×1 OffsetArray(view(::Array{Float64, 3}, :, 2:3, 2:2), 1:3, 2:3, 2:2) with eltype Float64 with indices 1:3×2:3×2:2:
[:, :, 2] =
 0.575096  0.631413
 0.479499  0.0708911
 0.979659  0.117883

julia> c[1, 2, 2]
0.5750957798298579
```

With `indices`, we can compute the intersection between indices for computation purposes.

I think this makes a lot of sense. For example if we want to compute something like

```julia
u * η
```

right now our infrastructure would assume this is a 3D computation defined at every level.

But what we probably want is to return an object that just computes `u * η` at the _surface_. This will work if `η.indices = (:, :, Nz:Nz)` for example; then the product `u * η` is also defined there.

We can also use this feature to support `FieldTimeSeries` of sliced output.

**Comment by simone-silvestri** [comment]
It makes a lot of sense! Like this it would also easy to modify the `AbstractOperations` to allow for indexed operations!
