### ISSUE TITLE
Conditional fluxes for Biharmonic operator and Immersed Boundaries

### ISSUE THREAD

**Issue by simone-silvestri** [CliMA/Oceananigans.jl#2209]
Biharmonic operator requires more halo cells than the classical Laplacian, so the `conditional_flux` method for the immersed boundary must be adapted to shut down fluxes from biharmonic diffusion up to 2 cells distance from an immersed boundary

Or maybe find a more sustainable solution, for example refactoring the biharmonic diffusivity to be calculated `∇²κ∇²` (which might require some work)

**Comment by simone-silvestri** [comment]
I think the best bet is to ensure that all derivatives inside the immersed boundary are zero. 

To do that we need to have fully 3D derivatives (i.e. no more `∂xᶜᵃᵃ`, `∂yᵃᶜᵃ` and `∂zᵃᵃᶜ`) so that we can mask them with the `solid_interface` function.

**Comment by glwagner** [comment]
I would first of all do _nothing_ that's intended to support `AnisotropicBiharmonicDiffusivity`. Instead we should delete this closure in favor of `HorizontallyCurvilinearAnisotropicBiharmonicDiffusivity` (or more appropriately, simply replace the existing `AnisotropicBiharmonicDiffusivity` with `HorizontallyCurvilinearAnisotropicBiharmonicDiffusivity`). See #2113 and a few other issues referenced there.

Since `HorizontallyCurvilinearAnisotropicBiharmonicDiffusivity` uses `diffusive_flux_x` (unlike `AnisotropicBiharmonicDiffusivity` --- one of its many problems), there are no spurious _fluxes_ across immersed boundaries:

https://github.com/CliMA/Oceananigans.jl/blob/80c7064b42a47e68c90690d7ab32db187bbdf26a/src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_biharmonic_diffusivity.jl#L67

https://github.com/CliMA/Oceananigans.jl/blob/80c7064b42a47e68c90690d7ab32db187bbdf26a/src/ImmersedBoundaries/conditional_fluxes.jl#L48

But I think the point here is that the fluxes are calculated using "wrong gradients". Note that `conditional_flux_fcc` doesn't shut down fluxes within "X" cells of a boundary. It shuts down fluxes _across_ an immersed boundary.

I think this issue is proposing to use `conditional_flux_fcc` for a _different_ purpose than what it's used for now --- to nullify fluxes for biharmonic diffusion in a buffer region around the boundary. The reason is that biharmonic fluxes are not correct on interfaces within one cell width of an immersed boundary, because they involve second order operators?

It's a little unclear to me what the right thing to do here is --- @simone-silvestri can you clarify what mathematical model you would like to implement when we have biharmonic diffusion in the presence of immersed boundaries?

**Comment by glwagner** [comment]
> To do that we need to have fully 3D derivatives (i.e. no more `∂xᶜᵃᵃ`, `∂yᵃᶜᵃ` and `∂zᵃᵃᶜ`) so that we can mask them with the `solid_interface` function.

This certainly might be an improvement. But, practically speaking, I think we only need to ensure that `∂x_∇²h_cᶠᶜᶜ` and `∂y_∇²h_cᶜᶠᶜ` are correct in the presence of immersed boundaries:

https://github.com/CliMA/Oceananigans.jl/blob/80c7064b42a47e68c90690d7ab32db187bbdf26a/src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_biharmonic_diffusivity.jl#L69

https://github.com/CliMA/Oceananigans.jl/blob/80c7064b42a47e68c90690d7ab32db187bbdf26a/src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_biharmonic_diffusivity.jl#L79

right?

**Comment by simone-silvestri** [comment]
Yeah, that's correct. We just have to ensure that those ones are correct. But you only want to nullify the first order derivatives . In this way, instead of having the whole `∂y_∇²h_cᶜᶠᶜ` going to zero only the part associated with a flux across or inside the immerse boundary is cancelled.

**Comment by glwagner** [comment]
My question is: what is the physically/mathematically correct biharmonic flux adjacent to an immersed boundary? Do we need to use an inward-looking stencil?
