### ISSUE TITLE
Is it worth considering a more general way to define the directions of `ScalarDiffusivirty` closures?

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2265]
This is related to the discussion in https://github.com/CliMA/Oceananigans.jl/pull/2262

Instead of defining structs specifically to symbolize directions (`Vertical`, `ThreeDimensional`, `Horizontal`) to use with `ScalarDiffusivity`, is it possible/worth it to use arrays, similar to what `Average()` does?

In this way, instead of specifying a `ConstantDiffusivity` as 

```julia
horizontal_closure = ScalarDiffusivity(ν=1e-3, κ=2e-3, isotropy=Horizontal())
```

a user would write

```julia
horizontal_closure = ScalarDiffusivity(ν=1e-3, κ=2e-3, isotropy=(1,2))
```

Seems to me like this would be more general and it would also decrease the amount of code used, but I'm not very familiar with that part of the code (especially since the recent refactor) so can't be sure. I thought it was worth posting about this though.

@glwagner @simone-silvestri

**Comment by glwagner** [comment]
This is an API change but it won't reduce source code. For `(1, 2)` (eg `HorizonalDirections()`) we use [a scheme from MITgcm](https://mitgcm.readthedocs.io/en/latest/algorithm/algorithm.html#horizontal-dissipation) with special conservation properties (eg conserves potential vorticity), whereas for `(1, 2, 3)` we use the standard 3D isotropic formulation in terms of the strain tensor. Each case `1`, `2`, `3` has to be written out because our code isn't written to be "n-dimensional"; instead we write out `x, y, z` explicitly.

**Comment by simone-silvestri** [comment]
the problem with this method it that it seems to imply (at least from how I see it) that `ScalarDiffusivity(isotropy=(1, 2))` would be equal to `ScalarDiffusivity(isotropy=(1,)) + ScalarDiffusivity(isotropy=(2,))`, whiich is not the case

**Comment by tomchor** [comment]
I see, thanks for the explanation (and @glwagner thanks for the link, which clarifies it a lot). I was not aware of these details. I'll close this issue.

**Comment by glwagner** [comment]
It's possible we'll be able to support that kind of thing someday, just not there yet. Worth mentioning that our 3D formulation isn't actually valid in curvilinear domains (doesn't diffuse vectors correctly). So our numerics haven't reached the stage of ideal abstractions.
