### ISSUE TITLE
Odd behavior using `ImmersedBoundary` while specifying scratch data for `Field` computation

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2581]
I'm facing this very weird behavior that appears when I do something like the example below (I'll show a MWE later):

```julia
using Oceananigans
using Oceananigans.Units
using Oceananigans.ImmersedBoundaries: ImmersedBoundaryGrid, GridFittedBottom

grid_base = RectilinearGrid(CPU(), size=(24, 24, 6), extent=(500, 500, 100))
grid = ImmersedBoundaryGrid(grid_base, GridFittedBottom(-50))
@info grid

model = NonhydrostaticModel(grid = grid, timestepper = :RungeKutta3,)
@info "" model
v_i(x, y, z,) = 0.1 + 1e-2*randn()
set!(model, v=v_i)


simulation = Simulation(model, Δt=10seconds, stop_time=0.5day,)


using Oceananigans.AbstractOperations: @at
using Oceananigans.Grids: Center, Face

ccc_scratch = Field{Center, Center, Center}(model.grid)
u, v, w = model.velocities

u1 = Field((@at (Center, Center, Center) 1*u), data=ccc_scratch.data)
v1 = Field((@at (Center, Center, Center) 1*v), data=ccc_scratch.data)

outputs = (; u1, v1,)
overwrite_existing = true

simname = "mwe.nc"
simulation.output_writers[:hr1_writer] =
        NetCDFOutputWriter(model, outputs,
                           filename = "data/hr1.$(simname)",
                           schedule = TimeInterval(15minutes),
                           overwrite_existing = overwrite_existing)

xz_average(F) = Field(Average(F, dims=(1,3)))
outputs_avg = map(xz_average, outputs)

simulation.output_writers[:avg_writer] =
        NetCDFOutputWriter(model, outputs_avg,
                           filename = "data/avg.$(simname)",
                           schedule = TimeInterval(15minutes),
                           overwrite_existing = overwrite_existing)

run!(simulation)
```

The output for `hr1_writer` appears to be fine, but when I open the outputs for `ave_writer` I get that both outputs are always _exactly_ the same, and they have the value that the xz-average of `u1` should:

![Screenshot_20220526_114754](https://user-images.githubusercontent.com/13205162/170556118-5e7cfb5b-6491-4e1e-919c-2ea9d5db5211.png)

The two left pictures are `u1` and `v1` from `avg_writer`. The figure on the right is the xy-average computed separately. In other words: in this example the xz-average of `u1` gets computed correctly, but the xz-average of `v1` gets assigned the value of the xz-average of `u1`.

A couple of notes:

- Using a regular grid instead of an immersed grid solves the issue (although I can't do that since that's the point of my whole simulation)
- Removing the scratch space specification solves the issue, but I also can't do that since I'm severely constrained in memory and this reduces my memory footprint in about 50% (maybe after https://github.com/CliMA/Oceananigans.jl/pull/2523 is merged)

I've got no idea what's causing this, so any help is appreciated.

**Comment by tomchor** [comment]
A more minimal working example is

```julia
using Oceananigans
using Oceananigans.Units
using Oceananigans.ImmersedBoundaries: ImmersedBoundaryGrid, GridFittedBottom

grid_base = RectilinearGrid(CPU(), size=(24, 24, 6), extent=(500, 500, 100))
grid = ImmersedBoundaryGrid(grid_base, GridFittedBottom(-50))
@info grid

model = NonhydrostaticModel(grid = grid, timestepper = :RungeKutta3,)
@info "" model
v_i(x, y, z,) = 0.1 + 1e-2*randn()
set!(model, v=v_i)


simulation = Simulation(model, Δt=10seconds, stop_time=0.5day,)


using Oceananigans.AbstractOperations: @at
using Oceananigans.Grids: Center, Face

ccc_scratch = Field{Center, Center, Center}(model.grid)
u, v, w = model.velocities

u1 = Field((@at (Center, Center, Center) 1*u), data=ccc_scratch.data)
v1 = Field((@at (Center, Center, Center) 1*v), data=ccc_scratch.data)

compute!(u1)
compute!(v1)

outputs = (; u1, v1,)
overwrite_existing = true
xz_average(F) = Field(Average(F, dims=(1,3)))
outputs_avg = map(xz_average, outputs)

compute!(outputs_avg.u1)
compute!(outputs_avg.v1)

@show interior(outputs_avg.u1) == interior(outputs_avg.v1)
```

**Comment by glwagner** [comment]
It's because the two fields use the same data:

```julia
u1 = Field((@at (Center, Center, Center) 1*u), data=ccc_scratch.data)
v1 = Field((@at (Center, Center, Center) 1*v), data=ccc_scratch.data)
```

therefore, the problem is that we are not "recomputing" the dependent operands of `outputs_avg.u1` correctly. If we don't recompute the operands of `outputs_avg.u1` and `outputs_avg.v1` when we compute them, then they can be identical (and thus wrong) because they are both computed using the same array.

**Comment by tomchor** [comment]
> It's because the two fields use the same data:
> 
> ```julia
> u1 = Field((@at (Center, Center, Center) 1*u), data=ccc_scratch.data)
> v1 = Field((@at (Center, Center, Center) 1*v), data=ccc_scratch.data)
> ```
> 
> therefore, the problem is that we are not "recomputing" the dependent operands of `outputs_avg.u1` correctly. If we don't recompute the operands of `outputs_avg.u1` and `outputs_avg.v1` when we compute them, then they can be identical (and thus wrong) because they are both computed using the same array.

That makes sense, especially because if I don't specify the scratch data it goes away. But any guesses as to why it only pops up when using IBMs?

https://github.com/CliMA/Oceananigans.jl/pull/2582 seems to suggest that it's because the Average is only computed at fluid nodes and therefore is applied conditionally. Is that it?

**Comment by glwagner** [comment]
It's because on an immersed boundary grid, reduced operations are wrapped in `ConditionalOperation` in order to mask the reduction --- and `ConditionalOperation` had a bug; namely it was missing a definition of `compute_at!` (which all the other abstract operations have, eg `BinaryOperation`).

For `compute!` on a reduction to be correct, we first have to compute all of the fields that are involved in the reduction. To make this work, we call `compute_at!` on `reduction.operand`. This in turn has to trigger the computation of _any_ fields that are in the expression tree associated with `reduction.operand`. Thus all `AbstractOperations` with field operands must define `compute_at!`.

The difference between `compute_at!` and `compute!` is that `compute_at!` has a "time" associated with it. This allows us to avoid "recomputing" fields --- if possible (eg, if a field is not sharing its data with another field).

PS I think a better descriptor than "Odd behavior" would be "Wrong behavior". "Odd" is a bit too general... by the title, it's not clear that something is actually amiss! "Odd" might just mean "unexpected", but somehow technically correct. Here that's not the case, the results are definitely wrong.

**Comment by tomchor** [comment]
> PS I think a better descriptor than "Odd behavior" would be "Wrong behavior". "Odd" is a bit too general... by the title, it's not clear that something is actually amiss! "Odd" might just mean "unexpected", but somehow technically correct. Here that's not the case, the results are definitely wrong.

I've been accused of being too harsh with my words before in issues, so I try to be conservative with by adjectives whenever I can :)

Thanks for the explanation! It makes perfect sense
