### ISSUE TITLE
Advection in `ShallowWaterModel`

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#2615]
Inspired by trying to resolve #1866, I have been looking over `shallow_water_advection_operators.jl`.

The first cocern is with[ line 22.](https://github.com/CliMA/Oceananigans.jl/blob/e76deefc1fdf115e05856a18977c593d0b5d3b0d/src/Models/ShallowWaterModels/shallow_water_advection_operators.jl#L22) .  We are trying to discretize a term the term

$\partial_x (h u u)$

Using `_advective_momentum_flux_Uu` is a good idea, since then we can use a variety of advections schemes.  However, we are advecting `solution[1]`, $uh$, with `solution[1]`, $uh$, and then dividing by $h$.  I fear that the dividing by $h$ afterward is going to eliminate any higher order that we might achieve by say `WENO5`.  Anyone know whether this is true?

A few ideas come to mind of how we could do things differently.

1. We could advect `solution[1]/solution[3]`, $uh/h$, by `solution[1]`, $uh$.
2. We could advect `solution[1]`, $uh$, by `solution[1]/solution[3]`, $uh/h$.
3. We could store $u$ and $v$ as `solution[4]`, and `solution[5]` and then change either of the `solution[1]/solution[3]` above to `solution[4].

I don't know which is better but is this something we should consider?

Thoughts @glwagner @simone-silvestri ?

**Comment by glwagner** [comment]
I suggest creating a model property called "velocities" and storing objects that represent the velocity components there. For ConservativeFormulation these will be AbstractOperations.

**Comment by glwagner** [comment]
Should we discuss this on #1866?

**Comment by simone-silvestri** [comment]
I was just now trying to assess the impact of the different formulations and advection scheme orders in the `shallow_water_bickley_jet` example. I ll let you know the results, but it seems like the conservative formulation as it is implemented right now is quite nice. The problem with dividing the advecting velocities before it's that they are at a different location, by reconstructing the flux before and then diving you preserve location for at least two fluxes

**Comment by simone-silvestri** [comment]
By the way, WENO (and other advection schemes) are always going to be at most second order as they are implemented right now. So the _order_ might not be the correct metric to look at the performance, the truncation error is probably what we want to look at

**Comment by simone-silvestri** [comment]
Maybe just as a preliminary example, the vortex merger experiment (at N =400) from https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2021MS002663

Conservative formulation `WENO(order=5)`
![vortex_merger_400_WENO](https://user-images.githubusercontent.com/33547697/175327205-5bec27da-c59d-443e-b7ca-54c52e47f454.png)

Vector Invariant Formulation `WENO(order=5, vector_invariant=VorticityStencil())`
![vortex_merger_400_VorticityStencil](https://user-images.githubusercontent.com/33547697/175327346-531d76ac-b55d-4759-84b3-9a50349dbf97.png)

Vector Invariant Formulation `WENO(order=5, vector_invariant=VelocityStencil())`
![vortex_merger_400_VelocityStencil](https://user-images.githubusercontent.com/33547697/175327408-433482ae-5e3d-4fb7-9047-b15bcca2e3d9.png)

So the conservative formulation does not seem to be bad at all (I ll be more quantitative with the growth rate of the bickley jet). There is a problem near the boundaries but it is just because of the interpolation of `h` which will be solved with the new operators

**Comment by francispoulin** [comment]
Those look great!  I agree that they are very similar, yet all a bit different.  What resolution are you using?  It would be  interesting to compare with the results in the paper.

Also, just to point out that the  height deviations in this example is 20% of the whole domain, which is pretty big.  This is a good example that should illustrate problems with significant changes in depth.

**Comment by glwagner** [comment]
Why don't we just fix the bugs?

**Comment by francispoulin** [comment]
I am including the link from above [here](https://github.com/CliMA/Oceananigans.jl/blob/e76deefc1fdf115e05856a18977c593d0b5d3b0d/src/Advection/centered_second_order.jl#L30).  

This shows that areas, or lenghts for shallow water, do appear but they are at the last step of the inbedded functions.

It's not clear to me that points 1 and 2 are a bug since the areas do appear in the calculations.  The evidence to support that is the above plots where the conservative scheme is very similar to the vector invariant scheme.

Point 3 no long is relevant to the code.

Point 4 is not a bug but a matter of maybe reducing the accuracy to second order, which might be the highest we can do anyhow.

**Comment by simone-silvestri** [comment]
I would have rather left the volume in the flux divergence to avoid this type of confusion. In a finite volume scheme, the advection tendency is $\frac{\sum_k F_k}{V_c}$ , where there is no mention of areas because they should be embedded in the fluxes calculation.

Then the cell volume `V_c` is a 1D metric in a 1D problem, a 2D metric in a 2D problem and a 3D metric in a 3D problem.

**Comment by francispoulin** [comment]
I see your point @simone-silvestri .  I thought these changes would make things clearer but perhaps they have done the opposite.  My apologies.

If you wanted to change them back to volumes, I'm perfectly happy with that.

Also, can you confirm that we don't need any extra metrics on the calculation of the momentum, as @glwagner originaly asked about it #1866 ?

**Comment by francispoulin** [comment]
Thanks for confirming!

So the two outstanding issues are:

1. Do we want to divide by volumes instead of areas to be more general?  (Cosmetic but maybe worth fixing)
2. Figure out how the height field should be included to achieve higher accuracy, which neither formulation is able to do.

**Comment by simone-silvestri** [comment]
Another outstanding issue is the formulation of tracer evolution. At the moment we are evolving tracers but maybe we want to advect thickness weighted tracers

**Comment by francispoulin** [comment]
Thanks @simone-silvestri .  I agree.  I changed my list to a checked boxes, to help with monitoring the progress.

I can also change the main script to go back to volumes, if we decide this is what we perfer.

**Comment by glwagner** [comment]
Should we close this?
