### ISSUE TITLE
`ShallowWaterModel` only filling in one halo point

### ISSUE THREAD

**Issue by francispoulin** [CliMA/Oceananigans.jl#2650]
Starting with the shallow water model example, we (@writingindy) have noticed that only the inner most halo points in the height field is being filled.  How can we make sure that all three halo points are being filled?

cc: @simone-silvestri

**Comment by simone-silvestri** [comment]
`Periodic` boundary conditions should fill the whole halos, while flux, value and gradient BC should fill only the first because advection schemes have reduced order approaching boundaries.

Did you notice this in a bounded direction or a periodic direction? In the latter case it is definitely a bug

**Comment by francispoulin** [comment]
Thanks for explaining. 

With periodic boundary conditions, everything goes well.  This does arsie with bounded boundary conditions.

The problem is that the height field is 0 at the first two halo points.  Any calculations that use these points are going to be wrong.  Two questions: 
1. How do we set the first two halo points manually?
2. Is this something that we want to do in general for the shallow water model, where zero heights often causes problems?

**Comment by francispoulin** [comment]
I agree that  your example does assign the first halo points correct.  

We are using the main branch now and indeed we are trying to use higher order schemes near the boundary, a bad idea, and we will try and avoid that. 

I looked over #2603 and can you point out where, say 3rd order upwinding switches to 1st order near the boundaries?  That should help us to modify our forcing function appropriately.

A more general piont is, if we never want to use the extra two halo points, why do we define them?  Wouldn't it be more cost efficientive to only define them in the periodic case, and have smaller halos in the bounded case?

**Comment by simone-silvestri** [comment]
If you didn't define new advection schemes but use the implemented ones they automatically lower the order near the boundaries. The implementation is in `topologically_conditional_interpolation.jl`.

If you did not define new `symmetric_left_biased_interpolation_xᶠᵃᵃ` functions you should be ok. 
Otherwise you have to add your methods in the above mentioned file. If you are using an immersed boundary, the limiting is performed in the `conditional_fluxes.jl` file in the ImmersedBoundaries module
