### ISSUE TITLE
Advection for the Flat Direction Momentum Equation Seems Missing 

### ISSUE THREAD

**Issue by fucent** [CliMA/Oceananigans.jl#2742]
Hi all,

I run a 2D grid setup (y-z) for a while and I get advection terms through a kernel function below. 
With the recent upgrade, I switched the advection scheme from WENO5() to WENO(). 
However,  the output of the u advection (fluctuation and background) becomes zero. And x-momentum is perfectly balanced between Coriolis force and viscosity.
The problem only happens in the flat direction and it remains with 5th order upwind too.

I wonder if I write the function wrong, or the model really does not calculate the advection for the velocity in the flat direction.

```
@inline function _Duu_div(i,j,k,grid,dep,params)
return div_𝐯u(i, j, k, grid,params.adv,params.vel,params.tracer);
end
Duu_div = Field(KernelFunctionOperation{Face, Center, Center}(_Duu_div,model.grid;parameters=(; adv = model.advection, vel = model.velocities, tracer = model.velocities.u),computed_dependencies = (1)));
```

_My model Setup:_

```
## Grid 
L = 1e3;
H = 100;

Ny = 1024;
Nz = 128;

## Streched Grid
hc = 1.37;
theta_s = 3.53;

@inline Space_z(k) = (hc*(k-Nz-1)/Nz + (H-hc)*sinh(theta_s*(k-Nz-1)/Nz)/sinh(theta_s));

grid = RectilinearGrid(GPU(); topology = (Flat, Periodic, Bounded),
                      size = (Ny, Nz),
                       y = (0, L),
                       z = Space_z,
                      );
```

```
model = NonhydrostaticModel(; grid, buoyancy = BuoyancyTracer(),
                       advection = WENO(; grid = grid),
                          timestepper = :RungeKutta3,
                            tracers = (:b), 
                           coriolis = FPlane(f=f),`
                            forcing = (b=b_force, u=u_force, v=v_force, w=w_force),
                            closure = (vertical_diffusive_closure, horizontal_diffusive_closure),
                           boundary_conditions = (u = u_bcs,),
                            background_fields = (u = U_bfield, b = B_bfield))
```
Let me know if more information is needed.

**Comment by simone-silvestri** [comment]
Hello! Yes, a Flattened direction entails a purely 2D Domain, so, not only the advection in the flattened direction is not calculated, but also the advection _due_ to the velocity in the flattened direction is not present. 

Probably to achieve the result you want you can use a `Periodic` direction with `Nx = 1`. This would give you a "quasi" 2D simulation

**Comment by glwagner** [comment]
@fucent can you include the grid you are using, just for the sake of documentation?

Note that triple ticks ``` are best for formatting blocks of code: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by fucent** [comment]
Hi @simone-silvestri 
Thank for the suggestion.
I see the change  in `flat_advective_fluxes`. I will do some test to see if I can reproduce my previous result. 
However, I think it is quite weird to keep other terms without the advection. Why don't we turn off whole u momentum calculation? Also, I think several examples still treat flat as a flat periodic boundary (e.g., Tilted BBL). 

@glwagner I update the grid layout in the main text.

**Comment by simone-silvestri** [comment]
@fucent, you are right that there is a discrepancy, we should probably think about what `Flat` means and fix the inconsistencies.

**Comment by simone-silvestri** [comment]
Having a `Flat` "Periodic" direction might work well for `RectilinearGrid`s, but if we want to use `Flat` for a `LatitudeLongitudeGrid`, we might incur in problems assuming that `Flat == Periodic`. 

I would always use `Periodic` to describe a homogeneous direction. This said, I agree with you that maybe we should just shut off the evolution of the `Flat` direction

**Comment by fucent** [comment]
@simone-silvestri  Yes, I agree the definition of `flat` need to be clarified. I almost believed I saw a super interesting process. I will use `Periodic` in the future.

**Comment by glwagner** [comment]
Derivatives (and interpolation) are turned off in `Flat` directions. This is a statement about the domain geometry --- the domain has no thickness (or is infinite and homogeneous) in the `Flat` direction. It is not a statement about the dimensionality of the physical space; ie we are not reducing the dimensionality of the problem from 3 to 2 dimensions.

As a result, the velocity normal to `Flat` is not zero. This case has important applications in geophysical fluid dynamics. A common case is when Coriolis forces are present; for "slice models" in x-z and y-z, we still need to prognose the velocity component normal to the flattened dimension to describe motions like inertial waves.

This is sometimes referred to as a "2.5D model".

A more severe reduction is to decrease the dimensionality of the _space_ by 1, ie to make a statement not just about the geometry of the domain, but the dimensionality of the physical space in which we solve the problem. This is "true 2D", and in this case there would be no x-component for momentum at all. This case is not directly supported in Oceananigans, and I'm not sure we should because it's applications are relatively more limited for ocean modeling. To achieve this we actually need `Bounded` with 1 grid point in the flat direction. This reflects the physical scenario being modeled as well --- in our world, 2D scenarios like this arise when a film of fluid is pressed between solid boundaries (or constrained in some other way).

**Comment by fucent** [comment]
The traditional 2.5D model retains $\partial_y vu + \partial_z wu$. Even in a QG setup, background field advection is still important. 
`flat` in the previous version means no variation in the `flat` direction but it now assumes no momentum flux variation in all directions for the `flat` direction velocity. 

That's why I don't think turning off $\nabla \cdot \vector{u} u$ as `flat` default fits GFD intuitive. Especially, it is not clearly indicated in the documentation.

**Comment by simone-silvestri** [comment]
Ok, if `flat` has a well defined GFD meaning we can leave it on then

**Comment by glwagner** [comment]
Oh, of course div(uu) shouldn't be turned off. I didn't realize that's the problem was.

**Comment by glwagner** [comment]
The problem is this file:

https://github.com/CliMA/Oceananigans.jl/blob/main/src/Advection/flat_advective_fluxes.jl

**Comment by navidcy** [comment]
What should they be? Let's fix it! :)

**Comment by glwagner** [comment]
They just have to be deleted! It's easy!
