### ISSUE TITLE
`calc_κᶜᶜᶜ()` is only defined for AMD and questions about its default behavior

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#2751]
Sorry in advance if I'm packing too much stuff into one issue. Let me know if that's the case and I can separate this into other issues.

The function `calc_κᶜᶜᶜ()` is only defined for the AMD closure, so for every other closure it silently defaults to https://github.com/CliMA/Oceananigans.jl/blob/56c70fb07eeeb8171958dc62ed7948ff2617cf7a/src/TurbulenceClosures/turbulence_closure_utils.jl#L33

So one obvious thing is that we definitely should define `calc_κᶜᶜᶜ()` for other closures.

A bigger question regards the use of multiple dispatch to create this "default" behavior for when the desired behavior isn't implemented yet. In this case, silently defaulting to `zero()` made be lose some hours of work because I thought there was something wrong with my script, when in reality `calc_κᶜᶜᶜ()` just wasn't defined for the closure I was using. Sure, this is a bit my fault for not checking the code thoroughly, but from a user perspective my opinion is that it would have been better to throw a "method not found" error or a warning then have the code fail silently. So I propose we either get rid of that general default behavior and just let the code fail with an error for the unimplemented cases, or at least add a warning to the lines above. Thoughts?

A follow-up question/comment regards the organization of the `TurbulenceClosure` module. Part of the reason for my delay in catching the  `calc_κᶜᶜᶜ()` issue is that I often get confused about the organizational aspect in that module. For example, there are several functions that, based on name, appear to do the same thing (`νᶜᶜᶜ`, `calc_νᶜᶜᶜ`, `getdiffusivity`; there's also a `calc_κᶜᶜᶜ` but no `κᶜᶜᶜ` function) and often the naming of the variables also doesn't help much. For example in these lines:

https://github.com/CliMA/Oceananigans.jl/blob/56c70fb07eeeb8171958dc62ed7948ff2617cf7a/src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl#L138

https://github.com/CliMA/Oceananigans.jl/blob/56c70fb07eeeb8171958dc62ed7948ff2617cf7a/src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl#L160

it's not clear to me what's `c`, `C`, `U`. It takes some amount of digging for me (who, admittedly, am not super familiar with the code) to conclude that `c` is the `tracer` and `U` is the `velocities` tuple. (I'm still not 100% sure what `C` is).

I understand that, again, I'm not super familiar with the code, so most Oceananigans developers would understand that module faster than me, but I think it's advantageous to make the code in general more easily understandable for people like me, who aren't experts in the code. 

I also understand that that is an incredibly complicated module, with no obvious way to organize it concisely. But I think using more verbose names would make it a lot more clear. So I propose we make variable and function names more verbose there.

Thoughts?

**Comment by simone-silvestri** [comment]
I agree we can make the functions a little more verbose in that sense. 
We can change `calc_ κᶜᶜᶜ` to `calc_nonlinear_ κᶜᶜᶜ` and `calc_νᶜᶜᶜ` to `calc_nonlinear_νᶜᶜᶜ`. 
(`κᶜᶜᶜ` does not exist because diffusivity is needed at faces)

For the variables we can make them verbose or agree to have a _concise_ naming convention (parallel to the verbose one) that is always consistent (i.e., `U` is `velocities`, `C` is `tracers`, `b` is `bouyancy` and so on)

**Comment by simone-silvestri** [comment]
For the general behaviour, I agree to just remove the general `calc_νᶜᶜᶜ` and `calc_κᶜᶜᶜ` which shouldn't be used unintentionally

**Comment by glwagner** [comment]
I'm not sure that this kind of function should be defined for all closures (not all closures even have a diffusivity). If we want to have a more uniform interface, I'd focus on `AbstractScalarDiffusivity` which is specific to closures with a single scalar diffusivity. I think there is already an interface there too.

**Comment by glwagner** [comment]
These functions do not all have the same purpose. Functions like `νᶜᶜᶜ`, which are defined starting here:

https://github.com/CliMA/Oceananigans.jl/blob/main/src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl#L80

are designed to return the diffusivity at the specific index `i, j, k` and location `ᶜᶜᶜ`, given a closure and possibly _precalculated_ diffusivity fields.

`calc_κᶜᶜᶜ` pertains to the precalculation itself, which is associated with the interface function `calculate_diffusivities!`. As you've noted, there is no standardized interface for _precalculating_ diffusivities --- because it's not clear what purpose that interface would serve. Therefore, for convenience, closures are allowed to use any code they like to precalculate the diffusivity.

@tomchor, are you proposing to define an interface for _precalculating_ diffusivities? What's the purpose of that interface?

**Comment by simone-silvestri** [comment]
I have a practical example that might demand a better interface for `calculate_diffusivities!` (or at least defining it for `ScalarDiffusivities`)

I am now using quite complex formulations to calculate the viscosity for `ScalarBiharmonicDiffusivity`. Because of the staggering of the variables, the viscosity can only be calculated at `Center`s
I am using now `DiscreteDiffusionFunction`, which interpolates my formulation to the desired location in space.
This is very inefficient because I am recomputing the expensive viscosity multiple times in the same place.
It would be nice to have an option to have a precomputed diffusivity also in case of a `ScalarDiffusivity`, but provide the function to calculate the diffusivity as it is now done for `DiscreteDiffusionFunction`.
This would allow the code to be way more personalizable.

**Comment by glwagner** [comment]
Can't you just define a new turbulence closure that subtypes `AbstractScalarDiffusivity`? Or do we still have some boiler plate that you are trying to push under the rug?

**Comment by simone-silvestri** [comment]
We could define two new turbulence closures, but they would be the same as `ScalarDiffusivity` and `ScalarBiharmonicDiffusivity` in behaviour, just that they have a precalculated diffusivity. So maybe we don't need to do that, just define `calculate_diffusivities!` for `ScalarDiffusivity` and `ScalarBiharmonicDiffusivity` and give the option to precalculate

**Comment by simone-silvestri** [comment]
the precalculation can be done easily with `νᶜᶜᶜ` or something like that

**Comment by glwagner** [comment]
This is also the case for `AnisotropicMinimumDissipation` --- it's identical to `ScalarDiffusivity`, but defines a custom `calculate_diffusivities!`:

https://github.com/CliMA/Oceananigans.jl/blob/main/src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl

(as well as `viscosity`, `diffusivity`, `DiffusivityFields`).

**Comment by glwagner** [comment]
> So maybe we don't need to do that, just define calculate_diffusivities! for ScalarDiffusivity and ScalarBiharmonicDiffusivity and give the option to precalculate

What do you mean by "give the option" to precalculate? If we do this, shouldn't we also change `AnisotropicMinimumDissipation`?

This design is intentional by the way --- by requiring users to write a struct, we ask them to "openly declare" the parameters of the turbulence closure. This leads to more readable and sharable user scripts than allowing users to define "master functions" that close over innumerable free parameters with inscrutable closure code.

Let's just keep in mind that the goal is not only convenience, but also to further the cause of reproducible science and code sharing!

**Comment by tomchor** [comment]
> @tomchor, are you proposing to define an interface for _precalculating_ diffusivities? What's the purpose of that interface?

The specific purpose atm is to make this code on Oceanostics work (currently it does not):
https://github.com/tomchor/Oceanostics.jl/blob/29a544d3decd833d9f86da05b66a7392197c3b93/src/Oceanostics.jl#L25-L39

The bigger purpose is to make it easier for users to work with viscosities and diffusivities. As far as I know there isn't a unified interface to getting these fields. I've needed that many times in the past in my scripts and had to use `if-else` statements to get ν and κ for each closure. I think it'd help users if Oceananigans could provide a standard interface for that.

**Comment by glwagner** [comment]
Well, I agree this is a discussion worth having.

Users need not add a new turbulence closure in the source code --- they can be added externally (eg in a model script) easily via multiple dispatch. We've illustrated this before, but I can't find the issue (the closest is discussion https://github.com/CliMA/Oceananigans.jl/discussions/2344).

> we need a computationally feasible option for our more adventurous users that want to experiment with new viscosities/diffusivities.

Is the issue about what we define as "feasible"? It's simple to add a new struct with a custom `calculate_diffusivities!`. I agree though that this could result in more boilerplate.

So, the difference is really just "how much code" one needs to write to get to a custom `calculate_diffusivities!`.

I think I would prefer a simple interface that allows users to dispatch on the type of `closure.ν`, ie something like

```julia
calculate_diffusivities!(diffusivities, closure::ScalarDiffusivity, args...) =
    calculate_diffusivities!(closure.ν, closure.κ, diffusivities, closure, args...) =
```

Then if users have special viscosities that require computation, they can define a custom `calculate_diffusivities!(ν::MyCustomViscosity, ...)`.

Another interface could un-comment these fields:

https://github.com/CliMA/Oceananigans.jl/blob/1a288c175d07b3d4262e965c7e75376d5541e24d/src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl#L117-L121

and then users can define fields with custom `compute!` definitions.

If we have an interface like the one above, we may not need a separate struct for `AnisotropicMinimumDissipation` at all. It really boils down to where we put information about the closure, such as free parameters. Right now we have an interface that encourages a new struct that subtypes `AbstractScalarDiffusivity`. An alternative is to do away with "abstract" scalar diffusivity, and generalize the concrete `ScalarDiffusivity` to any computed viscosity / diffusivity. This would then cover cases like `AnisotropicMinimumDissipation`, and move the free parameters associated with AMD from the turbulence closure struct into the viscosity struct.

The first design is "flatter", and therefore exposes data like free parameters a bit more. The second design is more "hierarchical", which reduces boilerplate but is a little bit more complex. That's the trade-off I see.

**Comment by glwagner** [comment]
> As far as I know there isn't a unified interface to getting these fields.

The interface for `AbstractScalarDiffusivity` is the function `viscosity(closure, diffusivities)`.
