### ISSUE TITLE
Allowing `NonhydrostaticModel` with grids that are irregular in either `x` or `y`

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#3116]
I wanted to extend the code to allow `NonhydrostaticModel`s with irregular grids in all directions, not just the `z` direction.

As @glwagner mentioned, it would be good to discuss the approach here, although I started the draft PR https://github.com/CliMA/Oceananigans.jl/pull/3111 already extending `FourierTridiagonalPoissonSolver` to all directions.

Apparently `BatchedTridiagonalSolver` needs to be generalized first, which I didn't anticipate/notice.

**Comment by tomchor** [comment]
cc @glwagner

**Comment by glwagner** [comment]
From the standpoint of `NonhydrostaticModel`, the only requirement (I think?) is a pressure solver that's valid on more grids.

The `FourierTridiagonalPoissonSolver` combines FFTs with a tridiagonal solve in one direction to solve the Poisson equation. Thus, this method can be used if the grid is stretched in just one (1) direction. Right now, we only support grids that are stretched in `z`, the third direction / index. Presumably it's at most a matter of copy and paste and index permutation to support grids that are stretched in `x` (and regular in `y, z`) or stretched in `y` (and regular in `x, z`).

Under the hood, the `FourierTridiagonalPoissonSolver` relies on the `BatchedTridiagonalSolver` to perform the tridiagonal solve:

https://github.com/CliMA/Oceananigans.jl/blob/4551a78b1f3fe4bb3b238676c128dc751be9b934/src/Solvers/fourier_tridiagonal_poisson_solver.jl#L81-L82

The `BatchedTridiagonalSolver` launches a kernel over `xy` and performs a tridiagonal solve in `z`:

https://github.com/CliMA/Oceananigans.jl/blob/4551a78b1f3fe4bb3b238676c128dc751be9b934/src/Solvers/batched_tridiagonal_solver.jl#L79-L80

So the first task is to extend the tridiagonal solver to support integrals in `x` and `y`. 

This could be straightforwardly supported by adding some kind of tag to indicate the "tridiagonal direction" (ie `:x`, `:y`, or `:z`), and copy-pasting the functionality for each case. It's a bit of code duplication but pretty straightforward...

Alternatively we could introduce some kind of abstraction that permutes array dimensions. Then we just have one algorithm which assumes the tridiagonal index is `k`, and support `i` or `j` under the hood via an array wrapper that performs an index permutation.

I'm leaning towards copy/paste because it's a little easier to understand and it's not that much code in this case...

**Comment by glwagner** [comment]
Note that we may also have the capacity to solve the Poisson equation on any grid using preconditioned conjugate gradient method (@xkykai)

**Comment by tomchor** [comment]
> So the first task is to extend the tridiagonal solver to support integrals in `x` and `y`.
> 
> This could be straightforwardly supported by adding some kind of tag to indicate the "tridiagonal direction" (ie `:x`, `:y`, or `:z`), and copy-pasting the functionality for each case. It's a bit of code duplication but pretty straightforward...
> 
> Alternatively we could introduce some kind of abstraction that permutes array dimensions. Then we just have one algorithm which assumes the tridiagonal index is `k`, and support `i` or `j` under the hood via an array wrapper that performs an index permutation.
> 
> I'm leaning towards copy/paste because it's a little easier to understand and it's not that much code in this case...

I also prefer the copy/paste method (that's what I used in https://github.com/CliMA/Oceananigans.jl/pull/3111).

If I understand correctly these two functions are the only ones that need to be generalized, no?: 

https://github.com/CliMA/Oceananigans.jl/blob/4551a78b1f3fe4bb3b238676c128dc751be9b934/src/Solvers/batched_tridiagonal_solver.jl#L74-L83

https://github.com/CliMA/Oceananigans.jl/blob/4551a78b1f3fe4bb3b238676c128dc751be9b934/src/Solvers/batched_tridiagonal_solver.jl#L88

if so, that's not too bad.

Is duplicating one of the tests in [test_batched_tridiagonal_solver.jl](https://github.com/CliMA/Oceananigans.jl/blob/main/test/test_batched_tridiagonal_solver.jl) but rotating everything to two different directions enough to test this new functionality?

**Comment by glwagner** [comment]
I think we should also add a property `tridiagonal_direction` or something like that.

We can write something like

```julia
launch_config = 
    if solver.tridiagonal_direction == :x
        :yz
    elseif solver.tridiagonal_direction == :y
        :xz
    elseif solver.tridiagonal_direction == :z
        :xy
    end

launch!(architecture(solver), grid, launch_config, 
             solve_batched_tridiagonal_system_kernel!, ϕ, a, b, c, rhs, t, grid, parameters, Tuple(args)) 
```

**Comment by tomchor** [comment]
> I think we should also add a property `tridiagonal_direction` or something like that.
> 
> We can write something like
> 
> ```julia
> launch_config, kernel_function = 
>     if solver.tridiagonal_direction == :x
>         :yz, solve_batched_x_tridiagonal_system_kernel!
>     elseif solver.tridiagonal_direction == :y
>         :xz, solve_batched_y_tridiagonal_system_kernel!
>     elseif solver.tridiagonal_direction == :z
>         :xy, solve_batched_z_tridiagonal_system_kernel!
>     end
> 
> launch!(architecture(solver), grid, launch_config, kernel_function, ϕ, a, b, c, rhs, t, grid, parameters, Tuple(args)) 
> ```

This can be inferred from `solver.grid` directly already so I don't think we need any extra properties:

```julia
launch_config(::YZRegRectilinearGrid) = :yz
launch_config(::XZRegRectilinearGrid) = :xz
launch_config(::XYRegRectilinearGrid) = :xy

function solve!(ϕ, solver::BatchedTridiagonalSolver, rhs, args... )
    a, b, c, t, parameters = solver.a, solver.b, solver.c, solver.t, solver.parameters
    grid = solver.grid

    launch!(architecture(solver), grid, lauch_config(grid),
            solve_batched_tridiagonal_system_kernel!, ϕ, a, b, c, rhs, t, grid, parameters, Tuple(args))

    return nothing
end
```

**Comment by tomchor** [comment]
> Can we open a PR that's dedicated to just changing the tridiagonal solver, and pursue a new fourier tridiagonal solver in a separate, subsequent PR?

Sure! That's what I was planning on doing :)
