### ISSUE TITLE
`ShallowWaterModel` example in docs takes much longer to run, even when compared to 3D examples

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3169]
In #3151 it was discovered that the shallow water example in the docs needs ~25 min to run while all other examples need from ~1min (2D) or up to ~7min (Baroclinic instability).

Was this always the case? Did something happen to impede the performance of the SWE model?

#3168 is relevant; it does not resolve the issue but nevertheless minimizes the toll that this issue has on the overall building time for the docs.

**Comment by glwagner** [comment]
Probably this was always the case.

**Comment by simone-silvestri** [comment]
It's a matter of the computational details; the shallow water example is just much heavier.

The baroclinic instability case runs for about 1440 time steps on a 48X48X8 (~18000 points) grid using Adams-Bashforth (1 tendency evaluation), the shallow water example runs for 15000 time steps (~10X more) on a 128X128 grid (~16000 points) using Runge-Kutta 3 (3 tendency evaluations).

The relative execution time seems reasonable to me. The question is, do we want to make the shallow water example leaner?

**Comment by navidcy** [comment]
I think, for now, since all docs built in 1h then let's not bother. But if we want to reduce it we'd know we have to start from the SWE example.

**Comment by glwagner** [comment]
You're saying that the SWE example accounts for half of the total docs build time?

**Comment by glwagner** [comment]
Running the example to t = 100 rather than t=150 would yield a quick 2/3. I think we can also decrease the resolution and increase the time-step.

The resolution also is not isotropic, which essentially wastes grid points. The x dimension is 2pi but y is width 20. So if we use Ny = 128 then we might as well use something like Nx = 64 or 48.

https://github.com/CliMA/Oceananigans.jl/blob/a1f4f4e75e51a83cf9dec9e671866cff67de1211/examples/shallow_water_Bickley_jet.jl#L118-L122

I think the writing and notation can also be improved. It's confusing to use `L_z` to refer to the reference depth. The `ShallowWaterModel` calls this variable `h`, and it's easy to confuse with the vertical extent of a 3D grid.
