### ISSUE TITLE
Immersed boundary conditions invalidate all non-immersed BCs?

### ISSUE THREAD

**Issue by hdrake** [CliMA/Oceananigans.jl#3208]
I've been playing around with the `immersed_couette_flow.jl` validation experiment and think I discovered a bug in the immersed boundaries implementation which causes non-immersed boundary conditions to be ignored.

The BCs specified are here:
https://github.com/CliMA/Oceananigans.jl/blob/f7acd8d0bd30dbe1ccb72854b6ea0ccab1eae0b5/validation/immersed_boundaries/immersed_couette_flow.jl#L16-L23

It is clear from the movie produced by the script that the flow adjusts to the immersed value BCs of u(0.1)=1 and c(0.1)=1 but does not adjust to meet the top BCs of u(1)=-1 and c(1)=-1.

https://github.com/CliMA/Oceananigans.jl/assets/12971166/fb6ac2a8-7081-4edf-b363-87850b47fc6a

I ran into the same problem when adding an immersed boundary to the `horizontal_convection.jl` experiment. Adding an immersed boundary invalidated the surface buoyancy forcing, even when no `immersed` boundary condition was explicitly specified.

Has anyone run into this issue or know what might be going on?

**Comment by hdrake** [comment]
It looks like something happened in between early stages of this PR (https://github.com/CliMA/Oceananigans.jl/pull/2437#issuecomment-1100709220) and the main branch of [v.086.0](https://github.com/CliMA/Oceananigans.jl/releases/tag/v0.86.0).

**Comment by glwagner** [comment]
That looks wrong. What is

```julia
@show model.velocities.u
```

?

**Comment by glwagner** [comment]
@simone-silvestri regularly uses immersed boundaries with surface boundary conditions so he might have something to comment. I think he's using `FluxBoundaryCondition` though so something might have slipped through the cracks for `ValueBoundaryCondition`.

**Comment by glwagner** [comment]
I get the same problem, and it looks like the boundary condition is added correctly:

```julia
julia> model.velocities.u
1×1×32 Field{Face, Center, Center} on ImmersedBoundaryGrid on CPU
├── grid: 1×1×32 ImmersedBoundaryGrid{Float64, Flat, Flat, Bounded} on CPU with 0×0×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Nothing, east: Nothing, south: Nothing, north: Nothing, bottom: ZeroFlux, top: Value, immersed: ImmersedBoundaryCondition
└── data: 1×1×38 OffsetArray(::Array{Float64, 3}, 1:1, 1:1, -2:35) with eltype Float64 with indices 1:1×1:1×-2:35
    └── max=-0.0857023, min=-0.972122, mean=-0.393485
```

I think `FluxBoundaryCondition` is tested here:

https://github.com/CliMA/Oceananigans.jl/blob/f7acd8d0bd30dbe1ccb72854b6ea0ccab1eae0b5/test/test_boundary_conditions_integration.jl#L231-L241

(though only for `NonhydrostaticModel`)...

Might make sense to build up those boundary condition integration tests for `HydrostaticFreeSurfaceModel` and also for `ValueBoundaryCondition` and `GradientBoundaryCondition`.

@simone-silvestri is this broken because we are now using "boundary-aware" derivatives?

**Comment by glwagner** [comment]
The horizontal convection example also uses `ValueBoundaryCondition`:

https://github.com/CliMA/Oceananigans.jl/blob/f7acd8d0bd30dbe1ccb72854b6ea0ccab1eae0b5/examples/horizontal_convection.jl#L55

**Comment by glwagner** [comment]
I think the reason `ValueBoundaryCondition` doesn't work is because differences have been modified to return `0` if one of the cells involved is "inactive", ie:

https://github.com/CliMA/Oceananigans.jl/blob/f7acd8d0bd30dbe1ccb72854b6ea0ccab1eae0b5/src/ImmersedBoundaries/conditional_differences.jl#L13

(A side comment is that this code is difficult to understand --- that's another thing we should strive to improve...)

A quick fix would be to swap `inactive_node` in the above code for `immersed_inactive_node`:

https://github.com/CliMA/Oceananigans.jl/blob/f7acd8d0bd30dbe1ccb72854b6ea0ccab1eae0b5/src/ImmersedBoundaries/ImmersedBoundaries.jl#L220-L221

This would preserve the desired behavior across immersed boundaries.

I have a hazy memory of discussing this @simone-silvestri but it looks like the current code is indeed broken. I can't remember if there was a specific reason to use `inactive_node` rather than `immersed_inactive_node` for conditional differences.

**Comment by glwagner** [comment]
The fix seems to work

https://github.com/CliMA/Oceananigans.jl/assets/15271942/76c68f20-930b-4286-a483-b817c28da5bb

PR incoming
