### ISSUE TITLE
`WENOVectorInvariant` method cleanup?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#3449]
These two definitions look very similar.

https://github.com/CliMA/Oceananigans.jl/blob/075d42cf3487532c14b9cca7356d5de11061e5eb/src/Advection/vector_invariant_advection.jl#L111-L117

https://github.com/CliMA/Oceananigans.jl/blob/075d42cf3487532c14b9cca7356d5de11061e5eb/src/Advection/vector_invariant_advection.jl#L181-L189

Is the second only for the `weno_kw`? Why can't the `weno_kw` be included from the first definition?

cc @simone-silvestri

**Comment by navidcy** [comment]
The docs end up showing only the docstring of the second method, which is empty.

https://clima.github.io/OceananigansDocumentation/stable/appendix/library/#Oceananigans.Advection.WENOVectorInvariant-Tuple{}

**Comment by glwagner** [comment]
Can you be explicit about the change you're suggesting?

**Comment by navidcy** [comment]
Yes.

Firstly I'm asking why we need two different methods and we can't have one method with `weno_kw = nothing` as default and if `weno_kw != nothing` then it's passed over to the other relevant constructors. Is there a reason I don't quite see?

**Comment by glwagner** [comment]
Well, `VectorInvariant` is for any vector-invariant-type advection scheme, whereas `WENOVectorInvariant` is specifically for vector invariant scheme with WENO interpolation (ie what Simone is developing in his paper). So `WENOVectorInvariant` is just a convenience function that hopefully reduces boiler plate a bit for hopefully what will become the most-used version of `VectorInvariant`.

There are a few other differences, like `vertical_order` instead of `vertical_scheme`.

We should get rid of `WENOVectorInvariant` though if it doesn't help much...

**Comment by navidcy** [comment]
Damn! I missed they had a different name! Omg sorry!
