### ISSUE TITLE
Should have an option to apply `Forcing` only at specific nodes?

### ISSUE THREAD

**Issue by tomchor** [CliMA/Oceananigans.jl#3525]
It seems to me that the use of `Forcing` as sponge/nudging layers that are only active in a small part of the domain is pretty common for code written with Oceananigans. I've done that in pretty much every doubly-periodic upper ocean LES that I've run. With open boundary conditions being implemented in https://github.com/CliMA/Oceananigans.jl/pull/3482, it looks like the use of these thin sponge layers will become even more common.

Currently implementing these layers as `Forcing` means they'll be calculated at every point in the domain, regardless of them being useful only in a small region. I wonder if it's worth adding some mapping of active nodes so that we can save computational resources by only calculating `Forcing` where it's needed.

If I understand correctly, `ImmersedBoundaryGrid` already has something like that?:

https://github.com/CliMA/Oceananigans.jl/blob/4367d422fd5780396da4ef660acd81a7fccce6df/src/ImmersedBoundaries/active_cells_map.jl#L91-L109

Although I do remember some discussion in the past about how it wasn't always worth passing a map, which is probably why this feature is optional.

I'm curious about what people think of this.

**Comment by glwagner** [comment]
This kind of feature can't be implemented directly in `Forcing`, because all explicit tendency terms are evaluated in the same kernel. So we have to evaluate `forcing` in every cell that requires a tendency.

It is possible to expose a feature that allows kernels to be launched over some subset of cells. Then users could implement this kind of optimization in their script by using an array to represent the forcing, and then by precomputing the forcing into that array using a kernel that only evaluates some subset of all the cells in a callback. Or something like that.

If forcing functions are expensive there may be simpler ways to do performance optimization though. For example, we can recommend piecewise linear masking functions for sponge layers instead of tanh or exp.

**Comment by tomchor** [comment]
> If forcing functions are expensive there may be simpler ways to do performance optimization though. For example, we can recommend piecewise linear masking functions for sponge layers instead of tanh or exp.

From my tests I think this optimization can shave off 10% of time on the CPU and 25% on the GPU. This isn't bad, but I anticipate launching `Forcing` only where necessary would shave of much more in the situations I mentioned. Although when I originally posted the issue I thought it could be directly implemented in `Forcing`, but you make a good point that it can't, so it might not be worth the effort (at least not right now).

I'll close this for now but feel free to re-open it if you think it's worth discussing.

**Comment by glwagner** [comment]
If you want to give an example of an expensive forcing function it could be instructive to discuss the options for performance optimization! Perhaps there will be some unexpectedly useful tips. A discussion might be a better place for that though.
