### ISSUE TITLE
Check boundary condition arrays are CuArrays if arch=GPU

### ISSUE THREAD

**Issue by suyashbire1** [CliMA/Oceananigans.jl#419]
The code segfaults otherwise.

**Comment by glwagner** [comment]
I don't think this is resolved. However, I think we should discourage using arrays for boundary conditions. We should encourage users to use functions because they are more portable, faster, and easier to interpret the meaning of when reading a script. Should we close this issue as a result?

**Comment by ali-ramadhan** [comment]
Hmmm, I think there are still valid reasons to use an array instead of a function, e.g. where the value of the boundary condition is expensive to compute.

But otherwise I think this issue falls under the broader category of having extra checks to make sure a model is consistent before running it. We could, e.g. check that the grid's halo size is consistent with the advection scheme chosen.

**Comment by ali-ramadhan** [comment]
This could be added to #1453.

**Comment by glwagner** [comment]
Right, this might fall under the purview of `validate_boundary_conditions`. We can use a function similar (identical?) to

https://github.com/CliMA/Oceananigans.jl/blob/6d350c17e2be03fb2b4429af8452e78dcaf3bae5/src/AbstractOperations/multiary_operations.jl#L132-L147

to check all boundary conditions and their consistency with `field.data`.

**Comment by navidcy** [comment]
is this resolved?

**Comment by glwagner** [comment]
I don't think so.
