### ISSUE TITLE
Confusing API for specifying parameters in low-level forcing functions versus `SimpleForcing`

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#565]
Forcing functions use `model.parameters` while `SimpleForcing` have their own parameters. Could be confusing as boundary condition functions also rely on `model.parameters`.

To be consistent and clearer to users, I feel like `SimpleForcing` should use `model.parameters` instead of storing its own. But maybe I'm missing something and there was a good reason for this.

https://github.com/climate-machine/Oceananigans.jl/blob/7080929008182b8d8e2d09e6a1de5d2f23f276d7/src/forcing.jl#L1-L13

**Comment by glwagner** [comment]
It's used for dispatch: the primary purpose of `SimpleForcing` is to provide a way for users to define a function of `x, y, z, t`. However, there are other cases, perhaps less common but still important, where one might want `x, y, z, t, parameters`. 

In the case that parameters are `nothing` (the default), the `SimpleForcing` function assumes that `func` is a function of `x, y, z, t`. If parameters are specified in the construction of the `SimpleForcing` object, eg

```julia
forcing = SimpleForcing((x, y, z, t, p) -> p.a * x^2, parameters = (a=2,))
```
then `func` must have the signature `x, y, z, t, parameters`, where `parameters` corresponds to the parameters object passed by the user to `SimpleForcing`.

We could delete the `parameters` field in `SimpleForcing` and replace it with a boolean type parameter, say `with_parameters`, which indicates that `func` is a function of `x, y, z, t, p` and that `p` corresponds to `model.parameters`. Do you think this is better? 

At the time this code was written I considered this possibility, but I felt the "non-locality" of that usage made it a bit trickier (ie, one builds `SimpleForcing` but adds `parameters` to `Model`, rather than building `SimpleForcing` and specifying parameters in `SimpleForcing`). 

It seems local straightforward things like that are preferred over seemingly more elaborate interlocking systems --- but maybe I'm wrong? The advantage of local usage realizes itself when you might consider many alternative `SimpleForcing` functions. Then, rather than having to change two lines when you want to change the forcing function (since you'd have to both change the definition of your forcing function *and* change `model.parameters`), you can just change the definition of a single `SimpleForcing` object. This seems better to me. But maybe its not.

Note that we have common names for subfields in many other places. For example, each field has a subfield called `data`, and we know through context that `u.data` is not the same as `v.data`. Doesn't the same logic apply here?

**Comment by glwagner** [comment]
The real problem I think is with `model.parameters` --- the use of `model.parameters` is extremely open ended (but this creates problems when we think it *must* be used only for certain applications). Maybe we should require objects for all user-defined forcing functions and boundary condition functions? Then we can get rid of `model.parameters` to avoid "confusion".

**Comment by glwagner** [comment]
By the way, I'm not sure this issue is correctly named. There is no inconsistency anywhere. The issue here is whether the API and our chosen nomenclature is easy to understand for users.

**Comment by glwagner** [comment]
There's no `model.parameters` anymore.
