### ISSUE TITLE
Implicit design of pressure solver hinders interpretability

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#594]
This function:

https://github.com/climate-machine/Oceananigans.jl/blob/72f1f5a770f3939c8bb16f29926f0bd776dc3756/src/Solvers/solve_for_pressure.jl#L3

is strongly implicit: the `RHS` is apparently isolated in the first few lines, but subsequently, the `RHS` is not an argument to `solve_poisson_equation!(solver, grid)`. 

It might be better just to pass both the `RHS` and the solution ϕ as explicit arguments to `solve_poisson_equation!`. An additional benefit may be that `RHS` and the `ϕ` can be specified as different for cases where one may want to retain `RHS` rather than overwriting it.

**Comment by ali-ramadhan** [comment]
Hmmm, seems that the central issue is that the `PressureSolver` struct holds the `RHS` and `ϕ` in `solver.storage`.

I agree that it would be nicer to separate it out so that the solver can be reused for other purposes.

A 3D array would have to be stored somewhere and it cannot be a field with halos as FFTW/CuFFT won't work on views.

Should we take `storage` out of the `PressureSolver` struct which would involve finding another place to store it?

Or should we just change the function signature to
```julia
solve_poisson_equation!(solution, RHS, solver, grid)
```
and call it via
```julia
solve_poisson_equation!(solver.storage, solver.storage, solver, grid)
```
?

**Comment by glwagner** [comment]
The second suggestion is what I am proposing. There are concomitant changes that must be in the function definition.

Using `solver.storage` for both `R` and `φ` is fine --- I understand that the objective is to minimize memory usage, which seems to require a compromise in the code design.

Changing the function signature of `solve_poisson_equation!`, however, costs nothing in performance or memory usage and will increase the utility and readability of the `solve_poisson_equation!` function.

**Comment by glwagner** [comment]
What is the purpose of `storage1` and why are these if statements needed?

https://github.com/climate-machine/Oceananigans.jl/blob/9f72d847feff7614695ac27851e4f93a3a52d104/src/Solvers/solve_for_pressure.jl#L4
