### ISSUE TITLE
Seeing only partial function index from Documenter

### ISSUE THREAD

**Issue by christophernhill** [CliMA/Oceananigans.jl#599]
@ali-ramadhan etc... the function index here

https://climate-machine.github.io/Oceananigans.jl/stable/function_index/

 seems to miss a bunch of functions. It would be more useful if it had all the functions. 

For example ```compute_w_from_continuity!``` appears from ``` Oceananigans.jl/src/TimeSteppers/kernels.jl```, but lots of other functions in their don't. Looking at code its not clear to me why that is. Is there a way to get all functions in the index?

**Comment by glwagner** [comment]
Does it only index exported functions?

**Comment by ali-ramadhan** [comment]
Hmmm, it's generated by Documenter's [`@index`](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@index-block-1) which "generates a list of links to docstrings that have been spliced into a document".

So I believe it only indexes exported functions right now because only exported functions are included in the library or public API documentation: https://climate-machine.github.io/Oceananigans.jl/stable/library/

I've been meaning to add a second page that documents the private API (unexported functions) as a lot of them have docstrings too.

Would just have to copy paste https://github.com/climate-machine/Oceananigans.jl/blob/master/docs/src/library.md and change `private = false` to `private = true`.

**Comment by ali-ramadhan** [comment]
PS: Not sure how Literate.jl (from the title) is related to the issue in your original post @christophernhill.

**Comment by christophernhill** [comment]
@glwagner and @ali-ramadhan that is probably it - but that may not be that helpful if you want to understand the code etc...!  I think an index for all functions would be useful.

**Comment by ali-ramadhan** [comment]
Agreed. I will add a second page to splice in all the private API docstrings and then function index should update to include all the unexported functions too.

**Comment by navidcy** [comment]
I'll close this.
