### ISSUE TITLE
Resume from checkpoint should be integrated with model constructor

### ISSUE THREAD

**Issue by suyashbire1** [CliMA/Oceananigans.jl#602]
This feature makes more semantic sense and would hopefully minimize modifications to parent script.

**Comment by suyashbire1** [comment]
#603 attempts to fix this.

**Comment by ali-ramadhan** [comment]
I definitely think we should make restoring from a checkpoint as seamless as possible within scripts. Ideally you would just have to change one line to restore from checkpoint and continue time stepping.

A common use case is running a long simulation on a cluster with strict time limits (e.g. 12 hour job time limits). Basically you just keep submitting jobs with the same script in which case being able to automatically "restart from the most recent checkpoint" might be a useful feature. This could be done via something like
```julia
restore_from_checkpoint(find_most_recent_checkpoint_file("."))
```

A couple of thoughts from discussion with @suyashbire1 yesterday:

1. To avoid have to enclose sections of code that set initial conditions with `if model.clock.iteration == 0`, we can introduce `set_initial_condition!(model, ...)` alongside `set!(model, ...)` that only sets fields if `model.clock.iteration == 0`.

2. A `Simulation` type could make implementing something like this easier. Although I think adding another struct or additional similar terminology (`Model` vs. `Simulation`) isn't the way to go. I think we can implement all the ideas we want via a function like
```julia
run_model!(model, time_step=TimeStepWizard(...), end_time=10day, progress_message=print_terse_message, ...)
```

**Comment by glwagner** [comment]
Hmm. I just want to be sure that I understand the workflow here. Presumably in an ideal world one does not have to use the original setup script at all --- right? In other words, I'd think the ideal command for restarting would be a one-liner, so that in a terminal or slurm script one might type

```
julia -e 'run_from_checkpoint("checkpoint_prefix", iteration=2342)'
```

Doesn't that make sense? Or no?

In our case, we can't achieve this ideal in many cases due to the fact that we cannot checkpoint functions. Therefore, in order to restore a model from a checkpoint we *sometimes* need to utilize the original run script. Is this the workflow we are discussing?

**Comment by glwagner** [comment]
For cases in which we need to utilize the original set-up script, would a function that looks something like 

```julia
set_to_checkpoint!(model, "checkpoint_filename")
```

do the trick? If the set-up script is provided, checkpointing should be really easy because we only need to load the solution and tendencies onto the CPU and then copy to the already-initialized GPU field, and set `model.clock.iteration` and `model.clock.time`. The more difficult case, at least from a model initialization point of view, is initializing a model when the original set-up script is not available.

The above line can be placed just prior to time-stepping, and commented out when users want to run from the initial condition. So only one line needs to be changed.
