### ISSUE TITLE
Hard-coded thread-size code should be commented

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#645]
These lines:

https://github.com/climate-machine/Oceananigans.jl/blob/9f72d847feff7614695ac27851e4f93a3a52d104/src/TimeSteppers/kernels.jl#L12

need comments to explain why, for example, the number `256` is showing up.

**Comment by ali-ramadhan** [comment]
Oh yeah I think I found that having 256 threads per block gave decent performance (a long time ago...) which is what I've used for those thread-block layouts. We always used 1 thread in z (number of z blocks = Nz) so for 3D grids Tx = Ty = 16 so that we have 16^2 = 256 threads per block while for 2D grids we set Tx or Ty = 256 so that Tx*Ty = 256 and we still have 256 threads per block. Just ensuring that large 2D models can saturate the GPU.

But yeah, it should be documented in there unless `launch_config` can perform just as well as the hand-picked thread-block layout then we can get rid of all this.
