### ISSUE TITLE
Internal wave verification experiment

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#674]
Right now we have a simple interval wave test in `test_dynamics.jl` (vertically propagating and only 10 time steps) and an example (@glwagner thinks it looks off).

We should turn them into a rigorous verification experiment. Would be a good test of the pressure gradient term, and we can compare with an analytic solution.

**Comment by navidcy** [comment]
#752 fixed the `example/internal_wave.jl`

Perhaps if you increase `k` in
https://github.com/CliMA/Oceananigans.jl/blob/b3b8162209409024c6847989ccd33780693f597c/test/test_dynamics.jl#L100
you may get the numerical solution in the test to agree with analytical at much better accuracy than `1e-4` as is now?

**Comment by glwagner** [comment]
The test is actually different from the example, since the amplitude,

https://github.com/CliMA/Oceananigans.jl/blob/b3b8162209409024c6847989ccd33780693f597c/test/test_dynamics.jl#L115

is horizontally uniform.

Therefore the continuity equation should be satisfied for this one, since we do have scale separation.

**Comment by glwagner** [comment]
Though oy I just noticed that the scale of the Gaussian is a factor 2 smaller than it should be.

**Comment by navidcy** [comment]
Perhaps it's only a hunch, but if the amplitude of the wave is small enough so that nonlinearity doesn't kick in, then I feel that more accuracy than 1e-4 should be obtained. (Take this hunch with a grain of salt though.)

**Comment by glwagner** [comment]
Hmm. Remember that Oceananigans.jl is using a second-order differences, rather than a spectral method. 1e-4 is a relative tolerance, which is pretty good. But actually the fact that the Gaussian is slightly narrower than I originally thought may play a role. When I set this up, I remember spending almost a whole day plotting the exact solution and convincing myself that 1e-4 was reasonable. The difference is almost undetectable by eye as I recall. Could be worth revisiting...

**Comment by ali-ramadhan** [comment]
@glwagner @navidcy I'm going to close this since the internal wave example seems like it might be better now but feel free to reopen if not.

https://clima.github.io/OceananigansDocumentation/stable/generated/internal_wave/
