### ISSUE TITLE
ERROR: LoadError: UndefVarError: SolutionBoundaryConditions not defined

### ISSUE THREAD

**Issue by truedichotomy** [CliMA/Oceananigans.jl#686]
I tried to run the `eady_turbulence.jl` example in Oceananigans v0.25.0 in Julia 1.4 RC2 on macOS 10.15.3 and got the following error:

```
julia> include("eady_turbulence.jl")
[ Info: CUDAdrv.jl failed to initialize, GPU functionality unavailable (set JULIA_CUDA_SILENT or JULIA_CUDA_VERBOSE to silence or expand this message)
N² = ((Rᵈ * f) / Lz) ^ 2 = 0.0004
α = sqrt(N²) / (f * σᵇ) = 0.02314814814814815
ERROR: LoadError: UndefVarError: SolutionBoundaryConditions not defined
Stacktrace:
 [1] top-level scope at /Users/truedichotomy/GitHub/Oceananigans.jl/examples/eady_turbulence.jl:138
 [2] include(::String) at ./client.jl:439
 [3] top-level scope at REPL[1]:1
in expression starting at /Users/truedichotomy/GitHub/Oceananigans.jl/examples/eady_turbulence.jl:138
```
I noticed that there are a lot of recent commits with regards to boundary conditions, may be the example is using an older interface?

**Comment by ali-ramadhan** [comment]
Ah sorry about that but thank you @truedichotomy for reporting this error!

`eady_turbulence.jl` isn't one of the examples that we currently compile to a tutorial/example in the documentation (https://climate-machine.github.io/Oceananigans.jl/stable/) so it has fallen a bit out of date. We should probably flesh it out into a full example/tutorial.

It requires PyPlot.jl and PyCall.jl which is why we don't run it as part of Travis CI right now.

I have updated the example as part of PR #671. Here is a link to the updated `eady_turbulence.jl` (just had to update a few lines): https://github.com/climate-machine/Oceananigans.jl/blob/2836e727283de8032a6791c2262fdb31825b6d79/examples/eady_turbulence.jl

As the example is a little half-baked and has gotten a bit out of date, it's a bit clunky and doesn't make use of some of the newer abstractions like the `Simulation` type, but you should be able to run it and see a plot like this that live updates every 100 iterations when you set `makeplot = true`:

![image](https://user-images.githubusercontent.com/20099589/76051435-c3712180-5f38-11ea-9c15-315e00f99cce.png)

@glwagner might have more to say about the example.

**Comment by ali-ramadhan** [comment]
Sorry didn't mean to automatically close this issue.

**Comment by glwagner** [comment]
This issue should probably be closed?

**Comment by ali-ramadhan** [comment]
Yes, closing. I think this was back when we weren't testing the Eady turbulence example.
