### ISSUE TITLE
User interface for adding topography/boundaries

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#694]
Bouncing off PR #693 I was thinking of letting users specify topography/boundaries by allowing them to specify the topography/boundary via a function [`boundary(x, y, z)` or `boundary(x, y, z, t)`] or an array `boundary[i, j, k]` and the damping constant used in the immersed boundary method.

So #693 would implement the cylinder like
```julia
@inline radius(x, z) = x^2 + z^2
@inline boundary(x, y, z) = radius(x, z) <= R ? 1.0 : 0.0
K = 50.0  # Damping constant
model = IncompressibleModel(..., topography=ImmersedBoundary(boundary, K))
```
and the immersed boundary method is implemented behind the scenes by adding terms like
```julia
 @inline u_immersed_boundary(i, j, k, grid, t, U, C, p) = @inbounds -boundary(grid.xF[i], grid.yC[j], grid.zC[k]) * p.K * U.u[i, j, k]
```
to the momentum equation.

I think the kwarg `boundary=ImmersedBoundary(...)` would be more accurate but we already have `boundary_conditions` and you can't actually enforce boundary conditions on the immersed boundary so a `boundary` kwarg might be misleading. `topography` might be less misleading but a cylinder is not a surface feature so `topography` is not strictly accurate...

**Comment by glwagner** [comment]
I'm not sure what the boundary conditions associated with this immersed boundary are, but I think that we should support arbitrary boundary conditions on immersed boundaries. Both the `Value` and `Flux` boundary conditions are important (for DNS with no slip, DNS with free-slip, and LES with a wall model). `Gradient` conditions on immersed boundaries may also be important in some cases, though I don't think it often arises in computational oceanography.

We may want to define a type called `ImmersedBoundary` that combines the physical definition of the boundary location (a function of `x, y, z, t`) as well as any numerical aspects of the immersed boundary's implementation (eg the width of the regularization region, damping constants, order of interpolation for setting gradient / value boundary conditions, etc). 

For interfacing with `model`, I think adding a field `immersed_boundaries` to `grid` could make sense. Then boundary conditions are applied in `6+n` places: along the 6 boundaries in `x, y, z`, and along the `n` immersed boundaries. The user may specify a single immersed boundary or a tuple of `n` immersed boundaries when constructing the `grid`.

Finally, we can define functions that implement the immersed boundary continuous forcing for momentum and tracers within their respective tendency functions (rather than adding it as a user-defined forcing). We can implement the continuous forcing in a naive manner for small numbers of immersed boundaries, and consider optimizations in the future for large numbers of immersed boundaries should that need arise.

**Comment by ali-ramadhan** [comment]
Closing as @whitleyv implemented this via an `immersed_boundary` kwarg in the model constructor.
