### ISSUE TITLE
Cubic lattice grid with missing nodes

### ISSUE THREAD

**Issue by ma-sadeghi** [CliMA/Oceananigans.jl#743]
Hi,

I wonder if `Oceananigans` is capable of solving fluid flow on cubic lattice grid with missing nodes. What I mean is basically adding solid walls to the original domain through deleting some of the nodes. For instance, consider the original domain to be 5 by 10:
```
o o o o o o o o o o
o o o o o o o o o o
o o o o o o o o o o
o o o o o o o o o o
o o o o o o o o o o
```
Now, let's introduce a solid block of size 3 by 4 to the bottom row:
```
o o o o o o o o o o
o o o o o o o o o o
o o o x x x x o o o
o o o x x x x o o o
o o o x x x x o o o
```

Thanks!

**Comment by ali-ramadhan** [comment]
Hi @ma-sadeghi, thanks for opening an issue. This should be possible using a continuous forcing immersed boundary method. It's somewhat crude as it just damps the velocity inside the boundary but is simple to implement and requires no significant changes to the model. For fast flows you might need to damp more strongly (and thus decrease the time step) but the solution should converge as you do so.

It's not a built-in feature but is pretty easy to implement by adding appropriate forcing functions to an Oceananigans model.

For example, in PR #693 we used such a method to simulate viscous flow around a cylinder (in 2D).

Here is the simulation script: https://github.com/climate-machine/Oceananigans.jl/blob/ar/flow-around-cylinder/verification/flow_around_cylinder/flow_around_cylinder.jl

These are the most relevant lines: https://github.com/climate-machine/Oceananigans.jl/blob/a921fc3edbf795bf4a2193cca84cad41ebdd5625/verification/flow_around_cylinder/flow_around_cylinder.jl#L18-L27

In this case the boundary was described analytically and `boundary(x, y, z)` evaluates to `1` inside the cylinder and to `0` outside.

In your case maybe it's easier to describe the boundary or missing nodes with a mask or array (also updated snippet for v0.29):
```julia
# ... Create boundary[i, j, k] array that's 1 inside the boundary and 0 outside ...

K = 50.0 # "Spring constant" for immersed boundary method 
parameters = (boundary=boundary, K=K)

# Continuous forcing immersed boundary method 
@inline u_immersed_boundary(i, j, k, grid, clock, state, params) =
    @inbounds -params.boundary[i, j, k] * params.K * state.velocities.u[i, j, k] 
@inline w_immersed_boundary(i, j, k, grid, clock, state, params) =
    @inbounds -params.boundary[i, j, k] * params.K * state.velocities.w[i, j, k] 

u_forcing = ParameterizedForcing(u_immersed_boundary, parameters)
w_forcing = ParameterizedForcing(w_immersed_boundary, parameters)

forcing = ModelForcing(u=u_forcing, w=w_forcing) 
```

Note that the API has changed a bit since PR #693 so the example is a little out of date. See release notes for details, especially for v0.26.0 onward: https://github.com/climate-machine/Oceananigans.jl/releases

Let us know if this helps and if you run into any issues. We're more than happy to help with setting up simulations and debugging them.

**Comment by glwagner** [comment]
The discussion on this issue has gone a bit stale for the current Oceananigans API. @ma-sadeghi , has your issue been resolved?

**Comment by ali-ramadhan** [comment]
@ma-sadeghi I'm going to close this issue but please re-open if you have any questions.
