### ISSUE TITLE
More streamlined interface for boundary functions?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#769]
We may have discussed this in the past or proposed similar ideas but just thought I'd open a suggestion issue as I think it might make model construction simpler for future users.

Right now, for example, creating a parameterized boundary function takes 5 steps
```julia
B_params = (
    Ly = Ly,
    B½ = 1.96e-7,    # Buoyancy flux at midchannel [m²/s³]
    Lᶠ = 10kilometer # Characteristic length scale of the forcing [m]
)
B(x, y, p) = p.B½ * (tanh(2 * (y - p.Ly/2) / p.Lᶠ) + 1)  # Surface buoyancy flux [m²/s³]
B_bf = BoundaryFunction{:z, Cell, Cell}(B, B_params)
top_b_bc = FluxBoundaryCondition(B_bf)
b_bcs = TracerBoundaryConditions(grid, top=top_b_bc)
```

I wonder if we can brush a lot of this under the hood so the user just has to type
```julia
B_params = (
    Ly = Ly,
    B½ = 1.96e-7,    # Buoyancy flux at midchannel [m²/s³]
    Lᶠ = 10kilometer # Characteristic length scale of the forcing [m]
)
B(x, y, p) = p.B½ * (tanh(2 * (y - p.Ly/2) / p.Lᶠ) + 1)  # Surface buoyancy flux [m²/s³]
b_bcs = TracerBoundaryConditions(grid, top=FluxBoundaryCondition(B))
```
I guess it really only skips one step but with 3 arguments it can be inferred to be a parameterized boundary function and the location `{:z, Cell, Cell}` can be inferred from the fact that the BC is being applied at the `top` and it's for a tracer field.

Other construction patterns can probably be streamlined too.

**Comment by glwagner** [comment]
Well, two q's --- 1) where does the user put the parameters for the `BoundaryFunction`? 2) How do we tell the difference between a function that's intended to be part of a boundary function and an ordinary function?

On 2), we could try to infer this based on the number of arguments that the function has, but this is fragile I feel, and implicit.

There is the syntax

```julia
b_bcs = TracerBoundaryConditions(grid, top=TracerBoundaryCondition(Flux, :z, B, p))
```

which is defined here:

https://github.com/CliMA/Oceananigans.jl/blob/master/src/BoundaryConditions/boundary_function.jl#L82

Definitely agree all of this can use improvement.

**Comment by glwagner** [comment]
Here's a few idea:

1. Write more constructors for `BoundaryCondition`. The simplest constructor is what we often use, when the boundary condition is a constant or array. But we should add more constructors that support specifying boundary condition parameters. We should assume that by default the user wants to use `BoundaryFunction`, rather than the current default assumption that the function being specified is low-level. We can have a public constructor for `BoundaryCondition` that takes the argument parameters, which is designed to work with what we currently call "`BoundaryFunction`".

2. Add support for a lower-level, non-default boundary condition function signature (the current default) that gives the user access to more of the model state, should they need it.

3. Never ask the user to tell `BoundaryCondition` what field / boundary is being used. Instead, add interpretation to `TracerBoundaryConditions`, `UVelocityBoundaryConditions`, etc that rebuilds the boundary conditions objects as needed. Use defaults in the `BoundaryCondition` constructor as temporary placeholders, and rewrap as needed in `TracerBoundaryConditions`.

**Comment by glwagner** [comment]
Here's a possible implementation...

# New constructor for `BoundaryCondition` for function boundary conditions

```julia
function BoundaryCondition(Tbc, condition::Function; parameters=nothing, long_function_signature=false)
    if !long_function_signature # convert condition to a BoundaryFunction
        condition = BoundaryFunction{:x, Cell, Cell}(condition, parameters)
    elseif parameters != nothing
        condition = ParameterizedBoundaryConditionFunction(condition, parameters)
    end
    return BoundaryCondition(Tbc, condition)
end

BoundaryCondition(Tbc, condition::{BoundaryFunction, ParameterizedBoundaryConditionFunction}) =
    BoundaryCondition(Tbc, condition)
```

The last definition may not be needed; however in the case that `condition` is already a `BoundaryFunction` or a `ParameterizedBoundaryConditionFunction` we would not want to do any conversion.

# Modification to `FieldBoundaryConditions` constructor

Note that the conversion to `BoundaryFunction` is not correct in general. To handle this we can modify the `FieldBoundaryConditions` constructor. One solution is

```julia

relocate_function_boundary_condition(bc, args...) = bc # fallback

relocate_function_boundary_condition(bc::BoundaryCondition{C, <:BoundaryFunction}, boundary, loc1, loc2) where C =
    BoundaryCondition(C, BoundaryFunction{boundary, loc1, loc2}(bc.func, bc.parameters))

function FieldBoundaryConditions(grid, loc;
      east = DefaultBoundaryCondition(topology(grid)[1], loc[1]),
      west = DefaultBoundaryCondition(topology(grid)[1], loc[1]),
     south = DefaultBoundaryCondition(topology(grid)[2], loc[2]),
     north = DefaultBoundaryCondition(topology(grid)[2], loc[2]),
    bottom = DefaultBoundaryCondition(topology(grid)[3], loc[3]),
       top = DefaultBoundaryCondition(topology(grid)[3], loc[3]))

    east = relocate_function_boundary_condition(east, :x, loc[2], loc[3])
    west = relocate_function_boundary_condition(west, :x, loc[2], loc[3])
    south = relocate_function_boundary_condition(south, :y, loc[1], loc[3])
    north = relocate_function_boundary_condition(north, :y, loc[1], loc[3])
    bottom = relocate_function_boundary_condition(bottom, :z, loc[1], loc[2])
    top = relocate_function_boundary_condition(top, :z, loc[1], loc[2])

    TX, TY, TZ = topology(grid)
    x_default_bc = DefaultBoundaryCondition(topology(grid)[1], loc[1])
    y_default_bc = DefaultBoundaryCondition(topology(grid)[2], loc[2])
    z_default_bc = DefaultBoundaryCondition(topology(grid)[3], loc[3])

    validate_bcs(TX, west,   east, x_default_bc, :west,   :east, :x)
    validate_bcs(TY, south, north, y_default_bc, :south, :north, :y)
    validate_bcs(TZ, bottom,  top, z_default_bc, :bottom,  :top, :z)

    x = CoordinateBoundaryConditions(west, east)
    y = CoordinateBoundaryConditions(south, north)
    z = CoordinateBoundaryConditions(bottom, top)

    return FieldBoundaryConditions(x, y, z)
end
```

# Examples

Then users should be able to use syntax like

```julia
surface_flux(x, y, t) = sin(x) * cos(t)

tracer_bcs = TracerBoundaryConditions(top=BoundaryCondition(Flux, surface_flux))
```

and it will work. Other examples are

```julia
nonlinear_surface_flux(i, j, grid, clock, state, parameters) = 1/3600 * (state.tracers.T[i, j] - 20) * sin(x) * cos(t)

tracer_bcs = TracerBoundaryConditions(top=BoundaryCondition(Flux, nonlinear_surface_flux, long_function_signature=true))
```

and

```julia
parameterized_nonlinear_surface_flux(i, j, grid, clock, state, parameters) =
    parameters.mu * (state.tracers.T[i, j] - parameters.T0) * sin(x) * cos(t)

top_tracer_bc = BoundaryCondition(Flux, parameterized_nonlinear_surface_flux, 
                                  parameters=(mu=1/3600, T0=20), long_function_signature=true)

tracer_bcs = TracerBoundaryConditions(top=top_tracer_bc)
```

**Comment by glwagner** [comment]
There's a bit of verbosity in the implementation proposed above, so improvements definitely welcome.

@BrodiePearson may be interested in this issue.

**Comment by ali-ramadhan** [comment]
Ah the examples at the end seem they would be quite a bit nicer than what we already have, and if everything goes through the `BoundaryCondition` function that would be pretty clean.

Seems like we would end up with a signature like

```julia
BoundaryCondition(Tbc, condition::Function; parameters=nothing, field_in_forcing=false, long_function_signature=false)
```
where non-nothing `parameters` adds a `parameters` argument at the end of boundary condition functions (of all types), `long_function_signature` switches between `(x, y, t, p)` and `(i, j, grid, clock, state, p)`, and `field_in_forcing` switches between `(x, y, t, p)` and `(x, y, t, ϕ, p)` (only works together with `long_function_signature=false`).

If this means not having to juggle `SimpleForcing`, `ParameterizedBoundaryFunction`, etc. then it would be a huge upgrade.

**Comment by glwagner** [comment]
Ah. Well `SimpleForcing` cannot be used for boundary conditions --- only forcing functions. Also `BoundaryFunction` doesn't currently have a "field_in_signature" option. However, we can add that along with the keyword argument in `BoundaryCondition`.

As a side note, the `field_in_signature` boolean for `SimpleForcing` was added so that "Relaxation" boundary conditions could be implemented more easily. It'd be nice if we had a more generic solution for "specifying" the form of function signatures. For example, it's also fairly common to want to have the entire `state` available. We could add "`state_in_signature`" in addition to `field_in_signature`, but this solution seems awkward at best...
