### ISSUE TITLE
Issues with CUDA.jl

### ISSUE THREAD

**Issue by sandreza** [CliMA/Oceananigans.jl#784]
There seems to be an issue with running on GPUs with the latest master branch. Specifically one gets errors with launch, which could be due to GPUify loops requiring a specific version of cuda native. See for example,

<img width="1670" alt="Screen Shot 2020-06-20 at 5 23 11 PM" src="https://user-images.githubusercontent.com/22668662/86287910-b266b300-bbae-11ea-96a0-7b1e4fa6d250.png">

**Comment by vchuravy** [comment]
Supporting CUDA.jl will require Oceananigans to move from GPUifyLoops to
KernelAbstractions

**Comment by glwagner** [comment]
Update: we think this error arises because `CUDAnative` is not a dependency of `Oceananigans`. As a result, a `launch` function is not compiled by `GPUifyLoops`. In principle, this problem *could* be solved by adding `CUDAnative` to `Oceananigans`. However, this is not possible because `CUDAnative` and `CUDA` (which `Oceananigans` currently uses for CUDA functions / abstractions) cannot be used in the same environment due to conflicting requirements for `Adapt`.

cc @sandreza @ali-ramadhan

**Comment by glwagner** [comment]
Is this resolved ?

**Comment by ali-ramadhan** [comment]
Yes this has been resolved by PR #805.
