### ISSUE TITLE
Different output intervals for different field outputs using JLD2OuputWriter

### ISSUE THREAD

**Issue by raphaelouillon** [CliMA/Oceananigans.jl#826]
Hi all,
I was wondering if it possible to set different output intervals for different quantities using the JLD2OutputWriter, and to store the results in different files. I only need a small output interval on lower dimension quantities (slices, 2D,1D and 0D averages typically), but would still like to output the model velocities and tracers at regular, larger intervals. In a similar way, is it possible to write in a separate file for each interval (e.g. my_file_0.jld2, my_file_1.jld2...)?
Thanks a lot for your help!

**Comment by raphaelouillon** [comment]
Found an answer to my first question in  Oceananigans.jl/verification/stratified_couette_flow/stratified_couette_flow.jl

**Comment by glwagner** [comment]
Each instance of `JLD2OutputWriter` has its own `frequency` or `interval`, and two output writers do not interact in general. You can add an arbitrary number of output writers with independent `frequency` and `interval`.

We don't have a way to save each output in a new file, exactly. However, you can set the maximum size of the file. If you set the max size very small, it will create new files for each output.

In fact, the design of the `JLD2OutputWriter` implicitly assumes you would like to save a "time series" of data inside one file, rather than saving each piece of data in a different file. Do you want to save data in different files to keep the file size small, or is there another reason? If the reason is to keep the file size small, I think `max_filesize` will work for you. If there's another reason to save one piece of data in each file, lets talk about it and we can possibly modify the default behavior of `JLD2OutputWriter`.

Note that the keywords `frequency` and `interval` will likely change in the near future due to #672 .

**Comment by glwagner** [comment]
@raphaelouillon should we close this issue?
