### ISSUE TITLE
`Flux` boundary condition docstring should mention the sign convention

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#837]
https://github.com/CliMA/Oceananigans.jl/blob/42e073dcb6d7c6c9bef2afea223e07caae09faf4/src/BoundaryConditions/boundary_condition_types.jl#L17-L22

Pretty easy to get the sign wrong I think.

**Comment by glwagner** [comment]
"Fluxes are defined so that the flux of a quantity in the positive direction has positive sign."

**Comment by glwagner** [comment]
Or maybe "The sign convention is such that a positive flux represents the flux of a quantity in the positive direction. For example, the a positive vertical flux implies a quantity is flux upwards, in the +z direction."

**Comment by glwagner** [comment]
Might be worth elaborating further.

"Due to this convention, a positive flux applied to the top boundary species that a quantity is fluxed upwards across the top boundary and thus out of the domain. As a result, a positive flux applied to a top boundary leads to a reduction of that quantity in the interior of the domain. Conversely, a positive flux applied to the bottom boundary leads to an increase of the quantity in the interior of the domain. The same logic holds for east, west, north, and south boundaries."

**Comment by ali-ramadhan** [comment]
This is great! Will open a PR updating the `Flux` docstring.
