### ISSUE TITLE
Be careful of using `end` in forcing functions and boundary conditions

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#838]
The docstrings for forcing functions and boundary functions with `i, j, k` signatures should tell users not to use `end` as it'll reach into the halo regions when they probably meant `grid.Nz`, etc.

cc @sandreza

**Comment by glwagner** [comment]
I think we are moving towards hiding the "discrete form" of boundary condition functions and forcing functions beneath an abstraction layer. When this change is complete, we can write some documentation on how to use the "discrete form"s if needed that includes this information.

**Comment by ali-ramadhan** [comment]
That would be nice, especially #746, but on the topic of defining `lastindex`: is it possible that someone might want a forcing function to access halo information? Using `grid.H{x,y,z}` would be better than `end` but it would be weird if `end < grid.Nx + 2grid.Hx` when working with halos.

I can't think of a possible use case but might still be good to add a recommendation against using `end` to preserve flexibility.

**Comment by glwagner** [comment]
Yea agree that it might be considered an "abuse of abstraction" to define `end` to mean "the grid point corresponding to the physical edge of the domain". That's what @sandreza expected, however? #UsersComeFirst

**Comment by glwagner** [comment]
> it would be weird if `end < grid.Nx + 2grid.Hx` when working with halos.

I agree with this. This is better fixed with documentation. It _should not_ be surprising that `end` does not refer to the final physical grid point. When working with discrete data, a knowledge of the discrete grid is required.

**Comment by glwagner** [comment]
An alternative solution is to supply our own syntax for working with the boundary of fields, similar to

https://github.com/JuliaArrays/EndpointRanges.jl/blob/master/src/EndpointRanges.jl

For example, we can define `east, west, north, south, top, bottom`, so that one can write

```julia
top_flux(i, j, grid, clock, fields) = fields.c[i, j, top]
```

This will work best if we generalize `adapt_structure` for fields so that field location information is preserved, which will allow us to accurately interpret these indices when applied to fields at cell interfaces (currently we throw away the entire field wrapper and keep only `data`.)

**Comment by glwagner** [comment]
We could solve this by unwrapping field data into a `view` rather than exposing the entire `OffsetArray`. Not sure we want to do that though.
