### ISSUE TITLE
`Computation` has result at wrong location

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#876]
Disclaimer: I might be misunderstanding the way abstract operations work.

I'm trying to compute the horizontally-averaged wT at cell faces (of which there should be `Nz+1` values). X-Ref: https://github.com/ali-ramadhan/ClimateSurrogates.jl/pull/4

The abstract operation for wT ends up at `(Cell, Cell, Face)` by default which is where I want it, but it seems to be computed at `(Cell, Cell, Cell)` even when I explicitly specify `@at (Cell, Cell, Face)`.

```julia
using Oceananigans, Oceananigans.Grids,Oceananigans.Diagnostics, Oceananigans.AbstractOperations
grid = RegularCartesianGrid(size=(16, 16, 16), extent=(1, 1, 1))
model = IncompressibleModel(grid=grid)
u, v, w = model.velocities
T, S = model.tracers
wT = w*T
MultiaryOperation at (Cell, Cell, Face)
├── grid: RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}
│   ├── size: (16, 16, 16)
│   └── domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0625]
└── tree: 

* at (Cell, Cell, Face)
├── OffsetArray{Float64, 3, Array{Float64,3}}
└── OffsetArray{Float64, 3, Array{Float64,3}}
```

This is fine so far.

```julia
wT_avg = Average(wT, model, dims=(1, 2))

wT_avg.field.operation
MultiaryOperation at (Cell, Cell, Face)
├── grid: RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}
│   ├── size: (16, 16, 16)
│   └── domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0625]
└── tree: 

* at (Cell, Cell, Face)
├── OffsetArray{Float64, 3, Array{Float64,3}}
└── OffsetArray{Float64, 3, Array{Float64,3}}

wT_avg.field.result
Field located at (Cell, Cell, Cell)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (18, 18, 18)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=16, Ny=16, Nz=16)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)
```

Seems wrong that the result is at `(Cell, Cell, Cell)` when the operation is at `(Cell, Cell, Face)`.

Don't think `Average` has anything to do with this as constructing the `Computation` manually produces the same bug.

```julia
c = Computation(wT, model.pressures.pHY′)
c.result
Field located at (Cell, Cell, Cell)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (18, 18, 18)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=16, Ny=16, Nz=16)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)
```

Will try to look into this tomorrow.

**Comment by glwagner** [comment]
Ah, good catch!

I think we should do away with the syntax

```julia
wT_avg = Average(wT, model, dims=(1, 2))
```

What this does is that it constructs a `Computation` using the _hydrostatic pressure_ as scratch space. Because hydrostatic pressure is a field at `(Cell, Cell, Cell)`, that's what you see when you look at `wT.field.result`. In fact, `Computation` doesn't check to see whether `result` is correctly specified. `result` could also be an array, rather than a `Field`, and it would still work as long as it was big enough.

The reason it doesn't affect results is because the "field" nature of the scratch space is never used. Only the data is used:

https://github.com/CliMA/Oceananigans.jl/blob/6b65e66f7decdfd09064e0182d756987d2a9d158/src/AbstractOperations/computations.jl#L41

I'm not sure the right solution. It would be nice if `result` were a `Field` at the correct location.

Here's an idea: when `result` is a field, we check to make sure that it has the correct location. However, when `result` is an array, we don't worry about it. This allows both behaviors: users who want to save memory and re-use the same scratch space for `Computation`s at different locations can specify `result` as an array. Users who want to explicitly use the field abstraction for `result` (perhaps because they'd like to do subsequent manipulation` can do so.

**Comment by glwagner** [comment]
This might still be a bug but I think we should nuke `Computation`. Should we hold on to this issue?
