### ISSUE TITLE
Is the warning "This simulation will recalculate the time step every iteration which can be slow" correct?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#903]
If `iteration_interval=1` in the `Simulation` and the user is using a `TimeStepWizard` they recieve a warning: 

https://github.com/CliMA/Oceananigans.jl/blob/994eae3d4550898914309e535ccbfd4655854646/src/Simulations/simulation.jl#L65-L68

But calculating the value of a time-step has a trivial cost compared to advancing the model by one time-step. Is this warning correct?

**Comment by ali-ramadhan** [comment]
Calculating the advective and diffusive CFL could be non-trivial since you're calculating at least 3 mean values. I've never timed it but I don't imagine it adds more than 5~10%.

https://github.com/CliMA/Oceananigans.jl/blob/8d808881c5a277b44abff83f39dd470fe2f16324/src/Simulations/time_step_wizard.jl#L33-L36

**Comment by glwagner** [comment]
Ah, I see.
