### ISSUE TITLE
fourth-order advection tested?

### ISSUE THREAD

**Issue by navidcy** [CliMA/Oceananigans.jl#925]
Is the fourth-order advection tested?
https://github.com/CliMA/Oceananigans.jl/blob/master/src/Advection/centered_fourth_order.jl

I tried using it in an example I'm drafting and code blew up. With the same time-step but the default advection scheme everything seemed fine... That doesn't necessarily mean that there is a problem but I was a bit alarmed I must say..

**Comment by ali-ramadhan** [comment]
I think @glwagner was able to run the 2D turbulence example with the `CenteredFourthOrder` advection scheme but we never performed a convergence test. It's possible a smaller time step is needed. @glwagner also suggested trying `AnisotropicBiharmonicDiffusivity`.

Side note: Might be good to add two new convergence tests modified from
https://github.com/CliMA/Oceananigans.jl/blob/master/verification/convergence_tests/one_dimensional_gaussian_advection_diffusion.jl
https://github.com/CliMA/Oceananigans.jl/blob/master/verification/convergence_tests/one_dimensional_cosine_advection_diffusion.jl
to test advection only with `CenteredFourthOrder` to ensure we see fourth-order convergence. Advection-diffusion tests should only show 2nd order convergence.

**Comment by glwagner** [comment]
I think fourth order advection could create more noise when a solution is under resolved, leading to blow up when second-order advection is stable. That's why I recommended biharmonic viscosity, which more aggressively damps grid-scale noise due to numerical advection errors.

This modification to the two-dimensional turbulence example works for me:

```julia
using Plots, Statistics, Oceananigans, Oceananigans.AbstractOperations, Oceananigans.Grids
using Oceananigans.TurbulenceClosures: AnisotropicBiharmonicDiffusivity
using Oceananigans.Advection: CenteredFourthOrder

model = IncompressibleModel(grid = RegularCartesianGrid(size=(256, 256, 1), extent=(2π, 2π, 2π), halo=(2, 2, 2)),
                            advection = CenteredFourthOrder(),
                            buoyancy = nothing,
                            tracers = nothing,
                            closure = AnisotropicBiharmonicDiffusivity(νh=1e-7, κh=1e-7))

u₀ = rand(size(model.grid)...)
u₀ .-= mean(u₀)
set!(model, u=u₀, v=u₀)

u, v, w = model.velocities
vorticity_operation = ∂x(v) - ∂y(u)

ω = Field(Face, Face, Cell, model.architecture, model.grid)
vorticity_computation = Computation(vorticity_operation, ω)

# Finally, we run the model and animate the vorticity field.
Δ = model.grid.Δx
ν = model.closure.νx
simulation = Simulation(model, Δt=0.01 * Δ^4 / ν, stop_iteration=0)

anim = @animate for i=1:100
    simulation.stop_iteration += 100 
    run!(simulation)

    compute!(vorticity_computation)

    x, y = xnodes(ω)[:], ynodes(ω)[:]
    heatmap(x, y, interior(ω)[:, :, 1]', xlabel="x", ylabel="y",
            color=:balance, clims=(-0.1, 0.1))
end

mp4(anim, "2d_turbulence_vorticity.mp4", fps = 15) 
```

**Comment by navidcy** [comment]
Sounds good @glwagner. However, an advection-diffusion 1D test (in the lines of the suggestion by @ali-ramadhan) would help alleviate any lingering ambiguities whether there is something wrong or not ;)

**Comment by glwagner** [comment]
Both testing and documentation are definitely warranted!

**Comment by glwagner** [comment]
@navidcy I think its tested now! You should also try `WENO5` instead of 4th order!

**Comment by navidcy** [comment]
I will try `WENO5` -- which is also tested, right? ;)

**Comment by glwagner** [comment]
WENO5 is tested, and the stencils involving advection of a signal by a uniform advecting velocity field are tested. However, this test does not include the nonlinear advection terms (eg dx(u^2)). We actually haven't found examples of stringent convergence tests for these operators in the literature. In part, this is because these schemes may not actually be 5th-order convergence (since the _advecting_ velocity field is interpolated using a symmetric interpolation with order `n-1`.

The best way for a stringent test is to obtain high-order diffusion operators, or to find a nonlinear advection dominated problem (like the Lamb dipole) where convergence can be guaranteed.

**Comment by glwagner** [comment]
Feel free to close this issue if the testing is satisfactory for you.

**Comment by glwagner** [comment]
Here are some plots that were made by @sandreza in an eddying channel configuration:

`CenteredSecondOrder`:

![image](https://user-images.githubusercontent.com/15271942/94508191-68a65c80-01df-11eb-8cda-2be243d7aad7.png)


`WENO5`:

![image](https://user-images.githubusercontent.com/15271942/94508209-72c85b00-01df-11eb-9473-5632b36d7961.png)
