### ISSUE TITLE
Model immediately turns to `NaN` after 1 time step when grid length is zero along `Flat` dimensions

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#940]
Might get fixed with #35 and #902 but worth documenting this issue.

I guess you shouldn't need to specify the grid length/extent/domain along `Flat` dimensions, it's assumed to take on one value only. So maybe we should allow for e.g.
```julia
grid = RegularCartesianGrid(topology=(Periodic, Flat, Flat), size=(4, 1, 1), x=(-1, 1), z=2.5)
```

---

```julia
using Oceananigans
grid = RegularCartesianGrid(topology=(Periodic, Flat, Flat), size=(4, 1, 1), x=(-1, 1), y=(0, 0), z=(0, 0))
model = IncompressibleModel(grid=grid)
time_step!(model, 1, euler=true)
interior(model.velocities.u)[:]
```

```
4-element Array{Float64,1}:
 NaN
 NaN
 NaN
 NaN
```

**Comment by glwagner** [comment]
That's interesting. I think this could actually be solved when #902 is resolved, since I believe the 0/0 leading to NaNs would be elided in that case?

I think it does make sense to permit specification of a single coordinate in a `Flat` dimension. This is appropriate for a "slice" model. Note that a "slice" is not the only idealization that leads to a `Flat` topology --- an alternative idealization is a domain that is uniform in one direction (which includes domains that are infinitely extended in the `Flat` direction). But slices are important and I think we should support it.
