### ISSUE TITLE
Avoiding repeated computations in the evaluation of `AbstractOperations`

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#955]
We now have an infrastructure for embedding fields that require computation like `AveragedField` and `ComputedField` within abstract operations.

We currently use a robust, but expensive strategy for ensuring that a computation is correct: immediately prior to evaluating an `AbstractOperation`, we call `compute!` on all of its nodes. This ensures that all data used in the `AbstractOperation` is up to date.

A downside to this strategy is that it is more expensive than it needs to be in many common cases. An example is the calculation of three-dimensional buoyancy fluxes `u * b`, `v * b`, and `w * b`, where `b = BuoyancyField(model)`. Evaluating these three expressions will each trigger an evaluation of the model buoyancy. Two of those evaluations are unnecessary.

We should brainstorm ways to avoid superfluous recalculation of `ComputedField`s and `AveragedField`s.

**Comment by kburns** [comment]
Dedalus currently has a binary configuration option to cache the evaluation of every intermediate operation within a single timestep / sub-stage.  The recursive evaluation of an operator tree accepts and propagates a cache-key argument, which could be related to e.g. the simulation iteration and sub-stage.  If caching is enabled, each operator checks it's own size-1 cache for the cache-key, and returns the result if present.  Otherwise it evaluates itself, and stores the result under the cache-key.  

This eliminates the repeated evaluation of individual operators, but at the cost of storing the result of every intermediate operation.  We're currently working on an upgrade that first traverses the tree, counts the number of references to a given operator, and deallocates the cached result after the cache has been accessed the corresponding number of times.

**Comment by glwagner** [comment]
As discussed via zoom with @kburns, passing a key to computations to be stored and used to determine whether a computation needs to be performed is a simple method that may work for us. A simple option for a key is the current model time, which works for all the time stepping methods we employ and has the additional advantage of interpretability.

One complication is that we allow users to specify memory space for `ComputedField`s and `AveragedField`s. As a result, two `ComputedField`s that share memory space may have incorrect `data` if the memory is overwritten. This is, in fact, a problem even in the current code and not dependent on the optimizations discussed in this issue.

Since we think it is important to give users the option of avoiding unnecessary memory allocation by managing the allocation of scratch space for computations, we cannot prevent incorrect output resulting from overwriting of scratch space during operations with embedded averaged fields and computed fields. We simply have to document this potential "gotcha".

We can make avoiding repeated operations a bit safer by requiring users to enable it when a `ComputedField` or `AveragedField` is constructed by a keyword argument, something like `recompute_safely`: 

```julia
U = AveragedField(model.velocities.u, dims=(1, 2), data=scratch, recompute_safely=false)
```

When `recompute_safely` is disabled, the model time at computation will be cached. The cache can either be inside `AveragedField`, or in a global cache. (A global cache has the advantage of being on the CPU; a local cache has the advantage of being local).

**Comment by glwagner** [comment]
Hmm, I suppose in the case that new data is created for a field, we know we can always `recompute_safely`, so we can at least trip that switch for such easy cases.
