### ISSUE TITLE
Background tracer distributions and advecting velocity fields

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#960]
We may able to provide an interface for specifying background tracer distributions and velocity fields (which perform advection only?) using `FunctionField`s and the existing advection operators.

I think we would want this functionality to assume that the _linear_ balances between background terms are somehow separately satisfied. With that assumption we can include just the two nonlinear terms associated with 1) advection of the resolved field by the background field and 2) advection of the background field by the resolved fields.

For this to be easily implemented we need to change the function signature of the advection operators for momentum from

```julia
div_ũu(i, j, k, grid, advection, U)
```

to 

```julia
div_ũu(i, j, k, grid, advection, U, u)
```

which then enables us to include background terms via

```julia
div_ũu(i, j, k, grid, advection, U_background, u) + div_ũu(i, j, k, grid, advection, U, u_background)
```

for example.

Tracers are fine, since the current function is

```julia
div_uc(i, j, k, grid, advection, U, c)
```

which will become

```julia
div_uc(i, j, k, grid, advection, U_background, c) + div_uc(i, j, k, grid, advection, U, c_background)
```

**Comment by glwagner** [comment]
This might require adding a new property to `IncompressibleModel` called `background_fields` (or something). @ali-ramadhan thoughts?

**Comment by glwagner** [comment]
This would hopefully make implementing the `eady_turbulence.jl` example a lot easier. Right now it requires quite a bit of expert knowledge:

https://github.com/CliMA/Oceananigans.jl/blob/e808a821d78949b0482b8372533e992cabb5d65f/examples/eady_turbulence.jl#L92-L132

**Comment by ali-ramadhan** [comment]
This abstraction would also simplify the ECCO/SOSE LESbrary.jl setup although it's also messy due to other terms and me jamming in Interpolations.jl objects: https://github.com/CliMA/LESbrary.jl/blob/master/scripts/pilot_simulation.jl#L117-L145

It seems like some complex setups could benefit a lot from a background fields abstraction. It shouldn't affect performance since the two interaction terms should results in no-ops.

> I think we would want this functionality to assume that the linear balances between background terms are somehow separately satisfied.

Agree with this. Users are responsible for making sure that they impose sensible background fields (just like they are responsible for setting sensible fields).
