### ISSUE TITLE
`InterpolatedField` for Lagrangian particle tracking, output on custom grids, and restoring from checkpoint to a new grid.

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#975]
Shouldn't be too hard to implement an `InterpolatedField` object where

```julia
ℑc = InterpolatedField(model.tracers.c, new_grid)
ℑc(x, y, z)
```

evaluates the `model.tracers.c` field at the location `(x, y, z)` with tri-linear interpolation (for now, could support other interpolation schemes in the future but not sure if it's that beneficial).

This has at least three potential uses:
1. Lagrangian particle tracking where the velocities need to be evaluated in-between grid points.
2. Writing output to a custom grid (different from the model grid). This should be as easy as passing an `InterpolatedField` to one of the output writers.
3. If a custom grid is passed when restoring from checkpoint, i.e. `restore_from_checkpoint(filepath, grid=new_grid)`, the checkpointed fields are interpolated onto the new grid. This is useful for spinning up simulations on a coarse grid then restoring from checkpoint on a finer grid.

cc @sandreza from our Slack discussion on mesoscale channels

**Comment by glwagner** [comment]
I have a slightly different vision for an `InterpolatedField` implementation that subtypes `AbstractReducedField`. I was thinking we could support fields that are interpolated on planes (in one direction), lines (in two directions) and points (trilinear interpolation).

```julia
u_slice = InterpolatedField(u, y=4.5)
```

then `u_slice` is an `InterpolatedField{Face, Nothing, Cell, ...}`.

This will allow users to output fields at common locations, and we would support planes, lines, and points.

I think the proposal here is slightly different, correct? The proposal here is to produce a new 3D field?

For the functionality proposed here I would advocate for using the existing `ComputedField` and creating a new abstract operation type called `Interpolation`:

```julia
struct Interpolation{G1, G2, P} <: AbstractOperation
    grid :: G1
    parent :: P
    parent_grid :: G2
end
```

then we have something like

```julia
c_interpolation = Interpolation(c, new_grid)
c_interpolation[i, j, k]
```

To prepare such a field for output you might write

```julia
new_c = ComputedField(Interpolation(c, new_grid))
```

This will work out of the box with `ComputedField` and output writers. We'll need to take care regarding output writers and the possibility of writing to various grids. I believe we have baked in the assumption that the "grid" appropriate for output is the one associated with `model` in both output writers. 

The functionality proposed where the interpolation object is callable with `(x, y, z)` is a bit different I think. I think that object doesn't need to be associated with a new grid at all. It's just a generic interpolation object. I think that's not a terrible idea to provide --- I think we are essentially overloading the `interpolate` function provided by `Interpolations.jl` with a custom, speedy method?

A related feature is to provide `set!` function for fields on different grids. In other words:

```julia
coarse_c = CellField(CPU(), coarse_grid)
fine_c = CellField(CPU(), fine_grid)

set!(fine_c, interestion_data)
set!(coarse_c, fine_c)
```

This is similar to interpolation, but I think for such a `set!` method we actually want to ensure that the global budget is respected... ? Thus we want to use integration to `set!` one field to another, rather than interpolation.... ?

This kind of functionality is implemented in `OceanTurb` for the 1D case:

https://github.com/glwagner/OceanTurb.jl/blob/b0d21cddaaf9aa625146108b5ec96a2a544a2f9f/src/fields.jl#L280-L299

Agree that if we have functions for interpolation we can use them for particle advection.

**Comment by glwagner** [comment]
The functionality provided by `Interpolations.jl` is probably not exactly what we want.

Perhaps we can define an object called `Interpolator`:

```julia
ℑc = Interpolator(model.tracers.c)
ℑc(3.2, 4.5, 0.1) # interpolates `c` to this x, y, z position.
```

This would rely on an interpolation function of some kind. We can reuse that interpolation function for `InterpolatedField`, `Interpolation`, and also for Lagrangian particle tracking.

There might be a nice infix operator that we can hijack to construct `AbstractOperations` like `Interpolation`. Perhaps `⟶`, eg

```julia
fine_c = ComputedField(c ⟶ fine_grid)
```

**Comment by glwagner** [comment]
> If a custom grid is passed when restoring from checkpoint, i.e. restore_from_checkpoint(filepath, grid=new_grid), the checkpointed fields are interpolated onto the new grid. This is useful for spinning up simulations on a coarse grid then restoring from checkpoint on a finer grid.

This is easy once we can write `set!(coarse_c, fine_c)`.

**Comment by glwagner** [comment]
Might've been closed accidentally, but #1090 doesn't add `InterpolatedField` (just `interpolate` --- still massive progress towards closing this PR of course!)

**Comment by ali-ramadhan** [comment]
Ah sorry woops!

**Comment by sandreza** [comment]
Given the new field structures I'll close this issue.

**Comment by glwagner** [comment]
For sure --- we probably _mostly_ need field _regridding_ rather objects that interpolate on the fly (while super cool, it may have limited scope compared to the effort required to develop and maintain it).
