### ISSUE TITLE
Flatten `state` in boundary condition functions and forcing functions to single tuple?

### ISSUE THREAD

**Issue by glwagner** [CliMA/Oceananigans.jl#985]
Currently the argument `state` used in boundary condition functions and forcing functions adopts the hierarchy in `IncompressibleModel`:

https://github.com/CliMA/Oceananigans.jl/blob/d80be8cf1db4f97515346ae3140b7cbf3f2ddab4/src/Models/Models.jl#L30-L32

so that the `u`-velocity, for example, is accessed via `state.velocities.u`.

I'm wondering if we should flatten `state`:

```julia
@inline state(model) = merge(datatuple(model.velocities), datatuple(model.tracers), datatuple(model.diffusivities))
```

Life is a bit simpler because then all the fields are accessed via `state.u`, `state.v`, `state.T`, etc.

A related question is nomenclature: we can change `state` to `fields`, or maybe `model_fields`, as there is a similar function called `fields`:

https://github.com/CliMA/Oceananigans.jl/blob/d80be8cf1db4f97515346ae3140b7cbf3f2ddab4/src/Models/Models.jl#L34

`model_fields` is a bit more specific so might be a bit more interpretable than `state`. For users this is only a question of documentation of boundary condition forcing and forcing functions since they don't see the internal implementation anyways.

**Comment by ali-ramadhan** [comment]
`state` is kinda low-level and hopefully most users won't need to use it once the boundary condition and forcing functions API is completed and unified so I think we can do whatever feels most comfortable to us.

I guess we'll end up with something like `state.u`, `state.c`, `state.ν`, `state.κ.c` which looks pretty nice. Now you can't call your tracers u, v, or w but we probably don't want to allow that anyways (might already not work).

`model_fields` makes a lot of sense to me. I thought we used the word `state` since inside the time stepping kernels, `state` includes the tendencies as well? But without tendencies, `model_fields` also makes sense and is more interpretable like you said.

**Comment by glwagner** [comment]
> Now you can't call your tracers u, v, or w but we probably don't want to allow that anyways (might already not work).

Right, this doesn't work because of other flattened objects, like `model.forcing`.

**Comment by glwagner** [comment]
> I thought we used the word state since inside the time stepping kernels, state includes the tendencies as well?

Looks like `state` doesn't currently include tendencies. I think this actually makes sense since the tendencies are actually an auxiliary variable. In other words, at the time that a tendency is being calculated, the _current_ value of the tendency is not available (it's being calculated!) Due to that there's probably no advantage to having access to the tendencies in a forcing function or boundary condition function.
