### ISSUE TITLE
Potential performance improvement for upwind schemes

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/Oceananigans.jl#987]
To reduce the number of operations, the number of memory allocations, and register pressure in GPU kernels, we might want to try refactoring upwind schemes to convert this pattern

```julia
@inline upwind_biased_product(ũ, ψᴸ, ψᴿ) = ((ũ + abs(ũ)) * ψᴸ + (ũ - abs(ũ)) * ψᴿ) / 2

@inline function momentum_flux_uv(i, j, k, grid, scheme::AbstractUpwindBiasedAdvectionScheme, u, v)

    ṽ  =    _symmetric_interpolate_xᶠᵃᵃ(i, j, k, grid, scheme, v)
    uᴸ =  _left_biased_interpolate_yᵃᶠᵃ(i, j, k, grid, scheme, u)
    uᴿ = _right_biased_interpolate_yᵃᶠᵃ(i, j, k, grid, scheme, u)

    return Ayᵃᵃᶠ(i, j, k, grid) * upwind_biased_product(ṽ, uᴸ, uᴿ)
end
```

to something like

```julia
@inline function momentum_flux_uv(i, j, k, grid, scheme::AbstractUpwindBiasedAdvectionScheme, u, v)
    
    ṽ = _symmetric_interpolate_xᶠᵃᵃ(i, j, k, grid, scheme, v)
    u = ṽ > 0 ? _left_biased_interpolate_yᵃᶠᵃ(i, j, k, grid, scheme, u) :
                _right_biased_interpolate_yᵃᶠᵃ(i, j, k, grid, scheme, u)
    
    return Ayᵃᵃᶠ(i, j, k, grid) * ṽ * u
end
```

Could save a lot of operations and register pressure for higher-order schemes.

I actually don't see why `((ũ + abs(ũ)) * ψᴸ + (ũ - abs(ũ)) * ψᴿ) / 2` is used instead of if-statements. Maybe @christophernhill or @jm-c know?

**Comment by glwagner** [comment]
I'm limited by my ignorance, but at least on the GPU it seems plausible that register allocation has to occur when the kernels are launched; ie, it cannot occur dynamically depending on runtime information. Thus branches that depend on runtime values (like what you've proposed) can't alleviate register pressure, since the compiler is forced to allocate registers for _both_ branches anyways at compile time... ?

**Comment by glwagner** [comment]
Using short-circuiting logic inside GPU kernels would reduce performance rather than improve it.
